
import { useMemo } from "react";
import { TanzaniaTaxCalculationResult, TanzaniaTimeFrame, formatTanzaniaCurrency } from "../utils/tanzaniaTaxCalculator";

interface DynamicTaxOverviewParagraphProps {
  taxResult: TanzaniaTaxCalculationResult;
  timeFrame: TanzaniaTimeFrame;
  income: number;
}

const DynamicTaxOverviewParagraph = ({ taxResult, timeFrame, income }: DynamicTaxOverviewParagraphProps) => {
  const paragraph = useMemo(() => {
    const variations = [
      `With a ${timeFrame === "monthly" ? "monthly" : "yearly"} income of ${formatTanzaniaCurrency(taxResult.grossIncome)} in Tanzania Mainland, your PAYE tax would be approximately ${formatTanzaniaCurrency(taxResult.netTax)} per ${timeFrame === "yearly" ? "year" : "month"}, leaving you with a take-home pay of ${formatTanzaniaCurrency(taxResult.netIncome)} per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` This equals an annual income of ${formatTanzaniaCurrency(income * 12)} with annual take-home pay of ${formatTanzaniaCurrency(taxResult.netIncome * 12)}.` : ` This equals a monthly income of ${formatTanzaniaCurrency(Math.round(income / 12))} with monthly take-home pay of ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))}.`} Your effective tax rate is ${taxResult.effectiveTaxRate.toFixed(1)}%, while your marginal tax rate is ${taxResult.marginalTaxRate}%. Please note that PAYE is calculated after deducting NSSF or PSSSF contributions from your gross income.`,

      `Based on your ${timeFrame === "monthly" ? "monthly" : "yearly"} salary of ${formatTanzaniaCurrency(taxResult.grossIncome)} in Tanzania Mainland, you would pay approximately ${formatTanzaniaCurrency(taxResult.netTax)} in PAYE tax per ${timeFrame === "yearly" ? "year" : "month"}, resulting in a net take-home pay of ${formatTanzaniaCurrency(taxResult.netIncome)} per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` On an annual basis, this represents ${formatTanzaniaCurrency(income * 12)} gross income with ${formatTanzaniaCurrency(taxResult.netIncome * 12)} net income.` : ` This translates to ${formatTanzaniaCurrency(Math.round(income / 12))} monthly gross income with ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} monthly net income.`} Your effective tax rate stands at ${taxResult.effectiveTaxRate.toFixed(1)}%, with a marginal tax rate of ${taxResult.marginalTaxRate}%. Remember that PAYE calculations are made after deducting NSSF or PSSSF contributions.`,

      `For a ${timeFrame === "monthly" ? "monthly" : "yearly"} gross income of ${formatTanzaniaCurrency(taxResult.grossIncome)} in Tanzania Mainland, the PAYE tax liability amounts to ${formatTanzaniaCurrency(taxResult.netTax)} per ${timeFrame === "yearly" ? "year" : "month"}, which leaves you with ${formatTanzaniaCurrency(taxResult.netIncome)} in take-home pay per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` This corresponds to an annual gross of ${formatTanzaniaCurrency(income * 12)} and annual net of ${formatTanzaniaCurrency(taxResult.netIncome * 12)}.` : ` Breaking this down monthly, you earn ${formatTanzaniaCurrency(Math.round(income / 12))} gross and take home ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))}.`} The effective tax rate is ${taxResult.effectiveTaxRate.toFixed(1)}%, while the marginal rate is ${taxResult.marginalTaxRate}%. PAYE tax is computed after deducting NSSF or PSSSF contributions from gross income.`,

      `Earning ${formatTanzaniaCurrency(taxResult.grossIncome)} ${timeFrame === "monthly" ? "monthly" : "yearly"} in Tanzania Mainland means paying approximately ${formatTanzaniaCurrency(taxResult.netTax)} in PAYE tax per ${timeFrame === "yearly" ? "year" : "month"}, giving you a take-home income of ${formatTanzaniaCurrency(taxResult.netIncome)} per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` Annually, this means ${formatTanzaniaCurrency(income * 12)} gross income and ${formatTanzaniaCurrency(taxResult.netIncome * 12)} net income.` : ` On a monthly basis, this works out to ${formatTanzaniaCurrency(Math.round(income / 12))} gross and ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} net.`} Your effective tax rate is ${taxResult.effectiveTaxRate.toFixed(1)}%, and your marginal tax rate is ${taxResult.marginalTaxRate}%. Note that PAYE is calculated after NSSF or PSSSF deductions.`,

      `At ${formatTanzaniaCurrency(taxResult.grossIncome)} ${timeFrame === "monthly" ? "monthly" : "yearly"} income in Tanzania Mainland, your PAYE tax obligation is ${formatTanzaniaCurrency(taxResult.netTax)} per ${timeFrame === "yearly" ? "year" : "month"}, resulting in a net income of ${formatTanzaniaCurrency(taxResult.netIncome)} per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` This translates to ${formatTanzaniaCurrency(income * 12)} annual gross income with ${formatTanzaniaCurrency(taxResult.netIncome * 12)} annual take-home pay.` : ` Monthly, this equals ${formatTanzaniaCurrency(Math.round(income / 12))} gross income with ${formatTanzaniaCurrency(Math.round(taxDetails.netIncome / 12))} net income.`} You're subject to an effective tax rate of ${taxResult.effectiveTaxRate.toFixed(1)}% and a marginal tax rate of ${taxResult.marginalTaxRate}%. PAYE calculations are based on income after NSSF or PSSSF contributions.`,

      `Your ${timeFrame === "monthly" ? "monthly" : "yearly"} earnings of ${formatTanzaniaCurrency(taxResult.grossIncome)} in Tanzania Mainland attract a PAYE tax of ${formatTanzaniaCurrency(taxResult.netTax)} per ${timeFrame === "yearly" ? "year" : "month"}, leaving you with ${formatTanzaniaCurrency(taxResult.netIncome)} in disposable income per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` Over a full year, this represents ${formatTanzaniaCurrency(income * 12)} in gross earnings and ${formatTanzaniaCurrency(taxResult.netIncome * 12)} in net earnings.` : ` Per month, this amounts to ${formatTanzaniaCurrency(Math.round(income / 12))} gross and ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} net.`} The effective tax rate is ${taxResult.effectiveTaxRate.toFixed(1)}%, with a marginal rate of ${taxResult.marginalTaxRate}%. PAYE is assessed after deducting NSSF or PSSSF contributions.`,

      `With ${formatTanzaniaCurrency(taxResult.grossIncome)} in ${timeFrame === "monthly" ? "monthly" : "yearly"} income from Tanzania Mainland, you'll pay around ${formatTanzaniaCurrency(taxResult.netTax)} in PAYE tax per ${timeFrame === "yearly" ? "year" : "month"}, which gives you a net salary of ${formatTanzaniaCurrency(taxResult.netIncome)} per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` Annually, your gross income totals ${formatTanzaniaCurrency(income * 12)} with net income of ${formatTanzaniaCurrency(taxResult.netIncome * 12)}.` : ` Monthly, you earn ${formatTanzaniaCurrency(Math.round(income / 12))} gross with ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} take-home.`} Your effective tax rate works out to ${taxResult.effectiveTaxRate.toFixed(1)}%, while your marginal tax rate is ${taxResult.marginalTaxRate}%. Keep in mind that PAYE is calculated post NSSF or PSSSF deductions.`,

      `A ${timeFrame === "monthly" ? "monthly" : "yearly"} salary of ${formatTanzaniaCurrency(taxResult.grossIncome)} in Tanzania Mainland results in a PAYE tax burden of ${formatTanzaniaCurrency(taxResult.netTax)} per ${timeFrame === "yearly" ? "year" : "month"}, providing you with ${formatTanzaniaCurrency(taxResult.netIncome)} in after-tax income per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` This equates to ${formatTanzaniaCurrency(income * 12)} gross annually and ${formatTanzaniaCurrency(taxResult.netIncome * 12)} net annually.` : ` Breaking it down monthly: ${formatTanzaniaCurrency(Math.round(income / 12))} gross income and ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} net income.`} You face an effective tax rate of ${taxResult.effectiveTaxRate.toFixed(1)}% and a marginal tax rate of ${taxResult.marginalTaxRate}%. PAYE tax is levied after NSSF or PSSSF contributions are deducted.`,

      `If you earn ${formatTanzaniaCurrency(taxResult.grossIncome)} ${timeFrame === "monthly" ? "monthly" : "yearly"} in Tanzania Mainland, your PAYE tax liability is ${formatTanzaniaCurrency(taxResult.netTax)} per ${timeFrame === "yearly" ? "year" : "month"}, leaving you with a disposable income of ${formatTanzaniaCurrency(taxResult.netIncome)} per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` On an annual scale, this means ${formatTanzaniaCurrency(income * 12)} gross and ${formatTanzaniaCurrency(taxResult.netIncome * 12)} net income.` : ` Monthly, this breaks down to ${formatTanzaniaCurrency(Math.round(income / 12))} gross and ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} net.`} The effective taxation rate is ${taxResult.effectiveTaxRate.toFixed(1)}%, and the marginal rate is ${taxResult.marginalTaxRate}%. Remember, PAYE calculations exclude NSSF or PSSSF contributions from gross income.`,

      `On a ${timeFrame === "monthly" ? "monthly" : "yearly"} income of ${formatTanzaniaCurrency(taxResult.grossIncome)} in Tanzania Mainland, you would owe ${formatTanzaniaCurrency(taxResult.netTax)} in PAYE tax per ${timeFrame === "yearly" ? "year" : "month"}, resulting in net earnings of ${formatTanzaniaCurrency(taxResult.netIncome)} per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` Projected annually, your gross income would be ${formatTanzaniaCurrency(income * 12)} with net income of ${formatTanzaniaCurrency(taxResult.netIncome * 12)}.` : ` Per month, you would earn ${formatTanzaniaCurrency(Math.round(income / 12))} gross with ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} net.`} Your tax burden includes an effective rate of ${taxResult.effectiveTaxRate.toFixed(1)}% and a marginal rate of ${taxResult.marginalTaxRate}%. PAYE is calculated on income after NSSF or PSSSF deductions.`,

      `Drawing ${formatTanzaniaCurrency(taxResult.grossIncome)} ${timeFrame === "monthly" ? "monthly" : "yearly"} in Tanzania Mainland means your PAYE tax is ${formatTanzaniaCurrency(taxResult.netTax)} per ${timeFrame === "yearly" ? "year" : "month"}, which leaves ${formatTanzaniaCurrency(taxResult.netIncome)} as your take-home pay per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` Annually, this corresponds to ${formatTanzaniaCurrency(income * 12)} gross earnings and ${formatTanzaniaCurrency(taxResult.netIncome * 12)} net earnings.` : ` Monthly, this translates to ${formatTanzaniaCurrency(Math.round(income / 12))} gross earnings and ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} net earnings.`} You're taxed at an effective rate of ${taxResult.effectiveTaxRate.toFixed(1)}% with a marginal rate of ${taxResult.marginalTaxRate}%. Note that PAYE computations are done after removing NSSF or PSSSF contributions.`,

      `Receiving ${formatTanzaniaCurrency(taxResult.grossIncome)} ${timeFrame === "monthly" ? "monthly" : "yearly"} in Tanzania Mainland subjects you to ${formatTanzaniaCurrency(taxResult.netTax)} in PAYE tax per ${timeFrame === "yearly" ? "year" : "month"}, giving you ${formatTanzaniaCurrency(taxResult.netIncome)} in net income per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` This represents ${formatTanzaniaCurrency(income * 12)} in annual gross income and ${formatTanzaniaCurrency(taxResult.netIncome * 12)} in annual net income.` : ` Monthly, this equals ${formatTanzaniaCurrency(Math.round(income / 12))} in gross income and ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} in net income.`} The effective tax percentage is ${taxResult.effectiveTaxRate.toFixed(1)}%, while the marginal tax percentage is ${taxResult.marginalTaxRate}%. PAYE calculations factor in deductions for NSSF or PSSSF contributions.`,

      `For someone earning ${formatTanzaniaCurrency(taxResult.grossIncome)} ${timeFrame === "monthly" ? "monthly" : "yearly"} in Tanzania Mainland, the PAYE tax comes to ${formatTanzaniaCurrency(taxResult.netTax)} per ${timeFrame === "yearly" ? "year" : "month"}, providing a net salary of ${formatTanzaniaCurrency(taxResult.netIncome)} per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` Over twelve months, this totals ${formatTanzaniaCurrency(income * 12)} gross and ${formatTanzaniaCurrency(taxResult.netIncome * 12)} net.` : ` Per month, this works out to ${formatTanzaniaCurrency(Math.round(income / 12))} gross and ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} net.`} Your effective tax rate is ${taxResult.effectiveTaxRate.toFixed(1)}%, and your marginal tax rate reaches ${taxResult.marginalTaxRate}%. Please note that PAYE is assessed after NSSF or PSSSF contributions are subtracted.`,

      `When you earn ${formatTanzaniaCurrency(taxResult.grossIncome)} ${timeFrame === "monthly" ? "monthly" : "yearly"} in Tanzania Mainland, your PAYE tax responsibility is ${formatTarzaniaCurrency(taxResult.netTax)} per ${timeFrame === "yearly" ? "year" : "month"}, which results in ${formatTanzaniaCurrency(taxResult.netIncome)} take-home income per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` Calculated yearly, this means ${formatTanzaniaCurrency(income * 12)} gross income with ${formatTanzaniaCurrency(taxResult.netIncome * 12)} net income.` : ` Calculated monthly, this means ${formatTanzaniaCurrency(Math.round(income / 12))} gross income with ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} net income.`} The effective rate of taxation is ${taxResult.effectiveTaxRate.toFixed(1)}%, with a marginal rate of ${taxResult.marginalTaxRate}%. PAYE is determined after accounting for NSSF or PSSSF contributions.`,

      `At a ${timeFrame === "monthly" ? "monthly" : "yearly"} earning level of ${formatTanzaniaCurrency(taxResult.grossIncome)} in Tanzania Mainland, you'll pay ${formatTanzaniaCurrency(taxResult.netTax)} in PAYE tax per ${timeFrame === "yearly" ? "year" : "month"}, leaving you with ${formatTanzaniaCurrency(taxResult.netIncome)} in spendable income per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` This scales to ${formatTanzaniaCurrency(income * 12)} annual gross income and ${formatTanzaniaCurrency(taxResult.netIncome * 12)} annual spendable income.` : ` This scales to ${formatTanzaniaCurrency(Math.round(income / 12))} monthly gross income and ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} monthly spendable income.`} You're subject to an effective tax rate of ${taxResult.effectiveTaxRate.toFixed(1)}% and a marginal tax rate of ${taxResult.marginalTaxRate}%. PAYE calculations are performed after NSSF or PSSSF deductions.`,

      `Earning a ${timeFrame === "monthly" ? "monthly" : "yearly"} salary of ${formatTanzaniaCurrency(taxResult.grossIncome)} in Tanzania Mainland means a PAYE tax of ${formatTanzaniaCurrency(taxResult.netTax)} per ${timeFrame === "yearly" ? "year" : "month"}, giving you ${formatTanzaniaCurrency(taxResult.netIncome)} in after-tax earnings per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` Extrapolated annually, you earn ${formatTanzaniaCurrency(income * 12)} gross with ${formatTanzaniaCurrency(taxResult.netIncome * 12)} after-tax.` : ` Broken down monthly, you earn ${formatTanzaniaCurrency(Math.round(income / 12))} gross with ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} after-tax.`} The effective tax burden is ${taxResult.effectiveTaxRate.toFixed(1)}%, while the marginal tax burden is ${taxResult.marginalTaxRate}%. Remember that PAYE excludes NSSF or PSSSF contributions from taxable income.`,

      `With a ${timeFrame === "monthly" ? "monthly" : "yearly"} wage of ${formatTanzaniaCurrency(taxResult.grossIncome)} in Tanzania Mainland, your PAYE tax amounts to ${formatTanzaniaCurrency(taxResult.netTax)} per ${timeFrame === "yearly" ? "year" : "month"}, providing you with ${formatTanzaniaCurrency(taxResult.netIncome)} in net wages per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` This amounts to ${formatTanzaniaCurrency(income * 12)} in annual wages and ${formatTanzaniaCurrency(taxResult.netIncome * 12)} in annual net wages.` : ` This amounts to ${formatTanzaniaCurrency(Math.round(income / 12))} in monthly wages and ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} in monthly net wages.`} Your effective tax rate is ${taxResult.effectiveTaxRate.toFixed(1)}%, and your marginal tax rate is ${taxResult.marginalTaxRate}%. PAYE tax is calculated after deducting NSSF or PSSSF contributions from your gross income.`,

      `Based on ${formatTanzaniaCurrency(taxResult.grossIncome)} in ${timeFrame === "monthly" ? "monthly" : "yearly"} compensation in Tanzania Mainland, you would pay ${formatTanzaniaCurrency(taxResult.netTax)} in PAYE tax per ${timeFrame === "yearly" ? "year" : "month"}, netting ${formatTanzaniaCurrency(taxResult.netIncome)} in compensation per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` This projects to ${formatTanzaniaCurrency(income * 12)} annual compensation with ${formatTanzaniaCurrency(taxResult.netIncome * 12)} net annual compensation.` : ` This projects to ${formatTanzaniaCurrency(Math.round(income / 12))} monthly compensation with ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} net monthly compensation.`} The effective taxation stands at ${taxResult.effectiveTaxRate.toFixed(1)}%, with marginal taxation at ${taxResult.marginalTaxRate}%. Please note that PAYE is calculated after deducting NSSF or PSSSF contributions from your gross income.`,

      `Drawing a ${timeFrame === "monthly" ? "monthly" : "yearly"} income of ${formatTanzaniaCurrency(taxResult.grossIncome)} in Tanzania Mainland results in ${formatTanzaniaCurrency(taxResult.netTax)} PAYE tax per ${timeFrame === "yearly" ? "year" : "month"}, leaving ${formatTanzaniaCurrency(taxResult.netIncome)} as your net income per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` Annually, this equals ${formatTanzaniaCurrency(income * 12)} gross with ${formatTanzaniaCurrency(taxResult.netIncome * 12)} net.` : ` Monthly, this equals ${formatTanzaniaCurrency(Math.round(income / 12))} gross with ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} net.`} You're taxed at ${taxResult.effectiveTaxRate.toFixed(1)}% effective rate and ${taxResult.marginalTaxRate}% marginal rate. Please note that PAYE is calculated after deducting NSSF or PSSSF contributions from your gross income.`,

      `On ${formatTanzaniaCurrency(taxResult.grossIncome)} ${timeFrame === "monthly" ? "monthly" : "yearly"} earnings in Tanzania Mainland, your PAYE tax burden is ${formatTanzaniaCurrency(taxResult.netTax)} per ${timeFrame === "yearly" ? "year" : "month"}, resulting in ${formatTanzaniaCurrency(taxResult.netIncome)} take-home earnings per ${timeFrame === "yearly" ? "year" : "month"}.${timeFrame === "monthly" ? ` This translates to ${formatTanzaniaCurrency(income * 12)} annual earnings and ${formatTanzaniaCurrency(taxResult.netIncome * 12)} annual take-home.` : ` This translates to ${formatTanzaniaCurrency(Math.round(income / 12))} monthly earnings and ${formatTanzaniaCurrency(Math.round(taxResult.netIncome / 12))} monthly take-home.`} Your tax rates are ${taxResult.effectiveTaxRate.toFixed(1)}% effective and ${taxResult.marginalTaxRate}% marginal. Please note that PAYE is calculated after deducting NSSF or PSSSF contributions from your gross income.`
    ];
    
    // Use a simple hash of the income to ensure consistent selection for the same income
    const hash = taxResult.grossIncome.toString().split('').reduce((a, b) => {
      a = ((a << 5) - a) + b.charCodeAt(0);
      return a & a;
    }, 0);
    
    const index = Math.abs(hash) % variations.length;
    return variations[index];
  }, [taxResult, timeFrame, income]);

  return (
    <p className="text-gray-700 leading-relaxed">
      {paragraph}
    </p>
  );
};

export default DynamicTaxOverviewParagraph;
