
import { v4 as uuidv4 } from 'uuid';

// Define Celebrity interface
export interface Celebrity {
  id: string;
  name: string;
  slug: string;
  occupation: string;
  salary: number;
  currency: string;
  imageUrl?: string;
  description: string;
  age: number;
  country: string;
  company?: string;
  industry: string;
  source: string;
  lastUpdated: string;
  categories: string[];
}

// Sample celebrity data
export const celebrities: Celebrity[] = [
  {
    id: uuidv4(),
    name: "Lucas Ribeiro",
    slug: "lucas-ribeiro",
    occupation: "Football Player",
    salary: 850000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2023/10/a_%C2%ACKit-Shoot-1447.jpg",
    description: "Lucas Ribeiro is a highly-rated Brazilian professional footballer who excels as an attacking midfielder for Mamelodi Sundowns FC. Known for his ability to revamp the midfield and generate interest from top-flight clubs like Burnley, Ribeiro is considered one of the best players in the league. Born on October 9, 1998, making him 27 years old in 2025, his estimated monthly salary ranges from R700,000 to R1,000,000. He brings international experience and skill to the Mamelodi Sundowns squad.",
    age: 27,
    country: "Brazil",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Ronwen Williams",
    slug: "ronwen-williams",
    occupation: "Football Player",
    salary: 500000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Williams.jpg",
    description: "Ronwen Williams is a prominent South African professional footballer who plays as a goalkeeper for Mamelodi Sundowns FC and captains the South African national team. With over 12 years of professional experience, Williams joined Sundowns in 2022 after a long stint at SuperSport United. Born on January 21, 1992, making him 32 years old in 2025, his estimated monthly salary is R500,000. He is a key player for both club and country.",
    age: 32,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Denis Onyango",
    slug: "denis-onyango",
    occupation: "Football Player",
    salary: 450000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Onyango-4.jpg",
    description: "Denis Onyango is a highly experienced Ugandan professional footballer who serves as a goalkeeper for Mamelodi Sundowns FC. Having joined the club in 2014, Onyango has had a distinguished career, also representing Uganda in the Africa Cup of Nations and captaining the national team until his retirement in 2021. Born on May 15, 1985, making him 39 years old in 2025, his alleged monthly salary is R450,000. His leadership and goalkeeping skills are invaluable to Mamelodi Sundowns.",
    age: 39,
    country: "Uganda",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Marcelo Allende",
    slug: "marcelo-allende",
    occupation: "Football Player",
    salary: 430000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Allende.jpg",
    description: "Marcelo Allende is a talented Chilean professional footballer who plays as an attacking midfielder for Mamelodi Sundowns FC and the Chile national team. Regarded as a top youth prospect in Chile and having captained their team during the 2015 FIFA U-17 World Cup, Allende brings youthful energy and skill to the squad. Born on April 7, 2002, making him 22 years old in 2025, Marcelo Allende earns a monthly salary of R430,000. He is considered a key player for the future of Mamelodi Sundowns.",
    age: 22,
    country: "Chile",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Thapelo Morena",
    slug: "thapelo-morena",
    occupation: "Football Player",
    salary: 400000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Morena-2.jpg",
    description: "Thapelo Morena is a versatile South African professional footballer who plays as both a defender and midfielder for Mamelodi Sundowns FC. Joining the club in 2016 from Bloemfontein Celtic, where he began his professional career in 2013, Morena is a valuable asset to the team. Born on August 6, 1993, making him 31 years old in 2025, his estimated monthly salary is R400,000, making him one of the highest-paid players at Sundowns in 2024. He also represents the South African national team.",
    age: 31,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Peter Shalulile",
    slug: "peter-shalulile",
    occupation: "Football Player",
    salary: 400000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Shalulile-1.jpg",
    description: "Peter Shalulile is a Namibian professional footballer who plays as a striker for Mamelodi Sundowns FC. He also represents the Namibian national team, showcasing his talent on both club and international levels. Shalulile began his career in 2011 at Tura Magic and later moved to Highlands Park in 2015 before joining Sundowns. Born on October 23, 1993, making him 31 years old in 2025, his estimated monthly salary is R400,000. His striking prowess makes him a key player for Mamelodi Sundowns.",
    age: 31,
    country: "Namibia",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Keanu Cupido",
    slug: "keanu-cupido",
    occupation: "Football Player",
    salary: 450000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2025/02/Cupido-WHite-BAckground-Square.jpg",
    description: "Keanu Cupido is a South African defender who plays for Mamelodi Sundowns FC and the Bafana Bafana (South African national team). He recently joined Sundowns from Cape Town City FC before the close of the January 2025 transfer window. Born on January 15, 1998, making him 27 years old in 2025, his estimated monthly salary ranges from R350,000 to R570,000. Cupido is a promising defender strengthening the Sundowns' squad.",
    age: 27,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Teboho Mokoena",
    slug: "teboho-mokoena",
    occupation: "Football Player",
    salary: 400000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Mokoena.jpg",
    description: "Teboho Mokoena is a proficient South African professional footballer recognized for his skills as a midfielder. He has proudly represented South Africa in various international competitions, showcasing his talent on the global stage. Mokoena officially joined Mamelodi Sundowns on January 27, 2022. Born on January 24, 1997, making him 28 years old in 2025, his alleged monthly salary ranges between R300,000 and R500,000. He is a valuable midfielder for Mamelodi Sundowns.",
    age: 28,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Mosa Lebusa",
    slug: "mosa-lebusa",
    occupation: "Football Player",
    salary: 300000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Lebusa-2.jpg",
    description: "Mosa Lebusa is a South African professional footballer who plays as a centre-back and left-back for Mamelodi Sundowns FC. He had his youth career at Dinonyana FC and Ajax Cape Town, making his senior debut in 2012. Lebusa joined Mamelodi Sundowns in 2018 and has become a regular in the starting XI. Born on October 10, 1992, making him 32 years old in 2025, his estimated monthly salary is R300,000. He is a reliable defender for the team.",
    age: 32,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Aubrey Modiba",
    slug: "aubrey-modiba",
    occupation: "Football Player",
    salary: 290000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Modiba-2.jpg",
    description: "Aubrey Modiba is a South African professional footballer who plays as a left winger for Mamelodi Sundowns FC. He has achieved career highs, including representing the South African national team at the Rio De Janeiro 2016 Summer Olympics. Born on July 23, 1995, making him 30 years old in 2025, Modiba's rumored monthly salary at Sundowns is around R290,000. He is a dynamic winger known for his speed and skill.",
    age: 30,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Themba Zwane",
    slug: "themba-zwane",
    occupation: "Football Player",
    salary: 350000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Zwane-3.jpg",
    description: "Themba Zwane is a highly regarded South African professional football player who operates as an attacking midfielder for Mamelodi Sundowns FC and the national team. Known for his goal-scoring ability and playmaking skills, Zwane is a key figure in the Sundowns' midfield. Born on August 3, 1989, making him 36 years old in 2025, his alleged monthly salary at Sundowns ranges from R250,000 to R500,000. His experience and talent make him a vital player.",
    age: 36,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Mothobi Mvala",
    slug: "mothobi-mvala",
    occupation: "Football Player",
    salary: 250000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Mvala1.jpg",
    description: "Mothobi Mvala is a South African professional football central defender who plays for Mamelodi Sundowns FC and the South African national team. Mvala got his big break at Highlands Park and was part of the 2016 Rio Olympics squad. Born on June 14, 1994, making him 30 years old in 2025, his estimated monthly salary at Sundowns is R250,000. He is a solid defender with national team experience.",
    age: 30,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Iqraam Rayners",
    slug: "iqraam-rayners",
    occupation: "Football Player",
    salary: 350000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2024/08/Rayners-.jpg",
    description: "Iqraam Rayners is a highly regarded South African professional footballer who plays as a forward for Mamelodi Sundowns FC and the Bafana Bafana. Considered one of South Africa's best attackers, Rayners joined the Brazilians in 2024 from Stellenbosch. Born on December 19, 1995, making him 30 years old in 2025, his estimated monthly salary ranges from R200,000 to R500,000. He is a dynamic forward adding firepower to the Sundowns' attack.",
    age: 30,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Khuliso Mudau",
    slug: "khuliso-mudau",
    occupation: "Football Player",
    salary: 300000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Mudau-2.jpg",
    description: "Khuliso Mudau is a South African professional footballer who plays as a right-back for Mamelodi Sundowns FC and the South African national team. Currently regarded as one of the best right-backs in the league, Mudau signed for Mamelodi Sundowns in October 2020 on a five-year contract. Born on April 26, 1995, making him 30 years old in 2025, his estimated monthly salary is between R200,000 and R400,000. He is a key defender for both club and country.",
    age: 30,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Lucas Suarez",
    slug: "lucas-suarez",
    occupation: "Football Player",
    salary: 300000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2025/02/Suarez-WHite-BAckground-Square.jpg",
    description: "Lucas Suarez is an Argentine professional footballer who plays as a defender and left-back for Mamelodi Sundowns FC. He came on loan from Estudiantes de Río Cuarto and was previously on loan at Talleres, where he reportedly earned around R380,000 monthly. Born on March 17, 1995, making him 30 years old in 2025, his estimated monthly salary at Mamelodi Sundowns ranges from R200,000 to R400,000. He brings international defensive experience to the team.",
    age: 30,
    country: "Argentina",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Grant Kekana",
    slug: "grant-kekana",
    occupation: "Football Player",
    salary: 250000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Kekana-2.jpg",
    description: "Grant Kekana is a South African professional footballer who plays as a defender and centre-back for Mamelodi Sundowns FC. Kekana joined Mamelodi Sundowns in July 2021 from their rivals, SuperSport United. Born on October 31, 1992, making him 33 years old in 2025, his estimated monthly salary is between R200,000 and R300,000. He is an experienced defender in the Mamelodi Sundowns squad.",
    age: 33,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Arthur Sales",
    slug: "arthur-sales",
    occupation: "Football Player",
    salary: 250000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Sales.jpg",
    description: "Arthur Sales is a Brazilian professional footballer who plays as a centre-forward for Mamelodi Sundowns FC. He joined the Sundowns in July 2024 for a record transfer fee from Belgian side, Lomel. Born on July 3, 2002, making him 23 years old in 2025, his estimated monthly salary is between R200,000 and R300,000. Despite a shaky start, Sales has become a part of the Mamelodi Sundowns squad, bringing his attacking abilities to the team.",
    age: 23,
    country: "Brazil",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Rivaldo Coetzee",
    slug: "rivaldo-coetzee",
    occupation: "Football Player",
    salary: 200000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Coetzee-3.jpg",
    description: "Rivaldo Coetzee is a South African professional footballer who plays as a defender and central midfielder for Mamelodi Sundowns FC. He also plays for the South African national team and made his professional debut at Ajax Cape Town. Coetzee was part of the Bafana Bafana squad in the 2016 Rio Olympics. Born on October 16, 1996, making him 29 years old in 2025, his estimated monthly salary is R200,000. He is a versatile player with both club and national team experience.",
    age: 29,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
  {
    id: uuidv4(),
    name: "Jayden Adams",
    slug: "jayden-adams",
    occupation: "Football Player",
    salary: 200000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2025/02/Adams-WHite-BAckground-Square.jpg",
    description: "Jayden Adams is a young and promising South African professional footballer who plays as an attacking midfielder for Mamelodi Sundowns FC. He recently arrived at the club from Stellies, signing a deal until at least June 2028. Adams also plays for the South African national team. Born on May 5, 2001, making him 24 years old in 2025, his estimated monthly salary is in the region of R100,000 to R200,000. He is considered a talented midfielder with a bright future at Sundowns.",
    age: 24,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02",
    categories: ["football-players", "mamelodi-sundowns"]
  },
    {
    id: uuidv4(),
    name: "Nkosingiphile Ngcobo",
    slug: "nkosingiphile-ngcobo",
    occupation: "Football Player",
    salary: 30000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Nkosingiphile%20Ngcobo.jpg",
    description: "Ngcobo, a highly skilled midfielder, earns R30,000 monthly. At 25, he has developed into a creative playmaker with impressive dribbling and passing ability. As a South African talent nurtured at Kaizer Chiefs, he possesses great vision and composure on the ball. Though his salary is relatively modest, his potential remains significant. His performances reflect a player eager to make a lasting impact, and with more game time, he could become a crucial figure. His ability to control the tempo of matches and deliver key assists makes him an essential part of the team’s attacking strategy.",
    age: 25,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-03",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Happy Mashiane",
    slug: "happy-mashiane",
    occupation: "Football Player",
    salary: 50000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Happy%20Mashiane.jpg",
    description: "Mashiane is a versatile left-back earning R50,000 per month. At 27, he has gained valuable experience, solidifying his defensive capabilities while also contributing in attack. The South African full-back is known for his quick runs down the flank and accurate crosses. His salary reflects his squad role, but his adaptability allows him to play multiple positions when needed. His commitment to both defense and attack makes him a reliable option for Kaizer Chiefs. With his technical skills and tactical awareness, he has the potential to further establish himself as a key player in the coming seasons.",
    age: 27,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-04",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Brandon Petersen",
    slug: "brandon-petersen",
    occupation: "Football Player",
    salary: 70000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Brandon%20Petersen.jpg",
    description: "Petersen, a seasoned South African goalkeeper, earns R70,000 monthly. At 30, he brings experience and composure to the squad. His quick reflexes and ability to organize the defense make him a reliable shot-stopper. Having played for multiple clubs in the South African league, he understands the tactical demands of top-flight football. His leadership in the box ensures stability, and his distribution skills allow smooth transitions from defense to attack. Although he faces competition for the starting role, his performances prove he is a dependable choice when called upon, making him a valuable part of the team.",
    age: 30,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-05",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Dillan Solomons",
    slug: "dillan-solomons",
    occupation: "Football Player",
    salary: 120000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Dillan%20Solomons.jpg",
    description: "Solomons is a dynamic right-back earning R120,000 per month. At 28, the South African defender brings pace and versatility to Kaizer Chiefs. His ability to overlap and deliver dangerous crosses adds an attacking edge, while his defensive awareness ensures solidity at the back. His salary reflects his growing importance in the squad, as his energetic playing style allows him to excel in different tactical systems. His work ethic and determination to contribute in both offensive and defensive phases make him a valuable asset. With his consistency, he has the potential to become one of the league’s top full-backs.",
    age: 28,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Sibongiseni Mthethwa",
    slug: "sibongiseni-mthethwa",
    occupation: "Football Player",
    salary: 70000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Sibongiseni%20Mthethwa.jpg",
    description: "Mthethwa, a strong and disciplined defensive midfielder, earns R70,000 monthly. At 30, the South African enforcer provides balance and control in midfield. His role in breaking up opposition attacks and shielding the defense is crucial for Kaizer Chiefs. His ability to win duels, intercept passes, and distribute the ball effectively makes him a key component of the team. While his salary is moderate, his value to the squad cannot be overlooked. His leadership and work rate allow attacking players more freedom to create chances. His experience and tactical intelligence make him a vital presence in the midfield.",
    age: 30,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-07",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Tebogo Potsane",
    slug: "tebogo-potsane",
    occupation: "Football Player",
    salary: 70000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Tebogo%20Potsane.jpg",
    description: "Potsane, an experienced attacking midfielder, earns R70,000 per month. At 31, the South African playmaker continues to showcase his dribbling and passing skills. His creativity in the final third allows him to unlock defenses and create scoring opportunities. Despite not always being a starter, his ability to impact games as a substitute makes him a useful squad player. His salary reflects his contributions, as he offers valuable experience and depth to the attacking lineup. His vision, technical ability, and composure under pressure ensure he remains a reliable asset for the team as they compete at the highest level.",
    age: 31,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Bruce Bvuma",
    slug: "bruce-bvuma",
    occupation: "Football Player",
    salary: 75000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Bruce%20Bvuma.jpg",
    description: "Bvuma, a talented goalkeeper, earns R75,000 monthly. At 29, the South African shot-stopper has built a reputation for his sharp reflexes and ability to perform in high-pressure situations. He has been with Kaizer Chiefs for several seasons, proving to be a dependable backup option. His quick reactions and confidence in one-on-one situations make him a strong presence in goal. His salary reflects his growing experience and ability to step up when needed. As he continues to improve, he has the potential to solidify his role as a consistent first-choice goalkeeper for the team.",
    age: 29,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-09",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Zitha Kwinika",
    slug: "zitha-kwinika",
    occupation: "Football Player",
    salary: 370000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Zitha%20Kwinika.jpg",
    description: "Kwinika, one of the highest-paid players at Kaizer Chiefs, earns R370,000 per month. At 31, the South African center-back brings leadership and defensive stability. His aerial dominance, tactical awareness, and strong tackling ability make him a key figure in the squad. His salary highlights his importance, as he is entrusted with organizing the backline. His composure on the ball allows him to initiate attacks from defense, a crucial trait in modern football. His wealth of experience at the top level ensures he remains an essential leader for Kaizer Chiefs, helping to guide younger players in the squad.",
    age: 31,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-10",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Thabo Cele",
    slug: "thabo-cele",
    occupation: "Football Player",
    salary: 480000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Thabo%20Cele.jpg",
    description: "Cele, a hardworking central midfielder, earns R120,000 monthly. At 28, the South African playmaker brings energy, passing accuracy, and defensive contribution. His ability to dictate the tempo of matches makes him a valuable asset. With experience in both domestic and international football, he understands the demands of high-level competition. His salary reflects his importance as a balanced midfielder capable of transitioning between attack and defense. His leadership and composure ensure stability in the middle of the park. With his technical skills and work ethic, he continues to be a key player for Kaizer Chiefs.",
    age: 28,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-11",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Makabi Lilepo",
    slug: "makabi-lilepo",
    occupation: "Football Player",
    salary: 130000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Makabi%20Lilepo.jpg",
    description: "Lilepo, an electrifying forward from DR Congo, earns R130,000 per month. At 27, he has developed into a dangerous attacking threat, using his speed and dribbling skills to trouble defenders. His ability to score and assist makes him one of the team’s most exciting players. His salary reflects his importance, as he has the capability to change games with his attacking prowess. His experience in African competitions has enhanced his confidence, making him a crucial figure in Kaizer Chiefs’ attacking setup. If he maintains his consistency, he could establish himself as one of the league’s top forwards.",
    age: 27,
    country: "DR Congo",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-12",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Tashreeq Morris",
    slug: "tashreeq-morris",
    occupation: "Football Player",
    salary: 90000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Tashreeq%20Morris.jpg",
    description: "Morris, a versatile forward, earns R90,000 monthly. At 30, the South African attacker has built a reputation as a hardworking and intelligent player. His ability to play as a striker or an attacking midfielder adds depth to the squad. His finishing ability, combined with his strength in aerial duels, makes him a valuable attacking option. His salary reflects his experience and steady contributions. His movement and link-up play help create chances for teammates. As he continues to perform, he remains an important figure in the squad, bringing both creativity and goal-scoring ability.",
    age: 30,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-13",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Edmilson Dove",
    slug: "edmilson-dove",
    occupation: "Football Player",
    salary: 105000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Edmilson%20Dove.jpg",
    description: "Dove, a Mozambican international defender, earns R105,000 per month. At 30, his defensive experience and technical ability make him a key part of the squad. Comfortable playing at center-back or left-back, he brings versatility and composure. His ball-playing skills allow him to contribute to the team’s build-up play. His salary reflects his reliability in defense, as he consistently delivers solid performances. His ability to read the game and time tackles effectively makes him a dependable option. With his leadership and adaptability, he remains an integral part of Kaizer Chiefs’ defensive setup.",
    age: 30,
    country: "Mozambique",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-14",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Reeve Frosler",
    slug: "reeve-frosler",
    occupation: "Football Player",
    salary: 150000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Reeve%20Frosler.jpg",
    description: "Frosler, a technically gifted right-back, earns R150,000 per month. At 27, the South African full-back is known for his precise crossing, defensive awareness, and attacking contribution. His salary reflects his crucial role in the team. His ability to transition seamlessly between defense and attack makes him one of the most complete full-backs in the league. His consistency and work rate ensure he remains a vital player for Kaizer Chiefs.",
    age: 27,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-15",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Mduduzi Shabalala",
    slug: "mduduzi-shabalala",
    occupation: "Football Player",
    salary: 33000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Mduduzi%20Shabalala.jpg",
    description: "Shabalala, at just 21, is a promising midfielder with immense potential. Earning R33,000 per month, he has already shown his flair and creativity on the ball. His technical ability, vision, and playmaking skills make him one of the most exciting young talents in South African football. His salary reflects his role in the squad as a developing player, and he is expected to continue growing and contributing to Kaizer Chiefs in the future. With the right development, Shabalala could become a key player in the South African national team as well.",
    age: 21,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-16",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Yusuf Maart",
    slug: "yusuf-maart",
    occupation: "Football Player",
    salary: 300000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Yusuf%20Maart.jpg",
    description: "Maart, a central midfielder, is a standout performer at Kaizer Chiefs, earning R300,000 per month. At 29, the South African has become a crucial part of the squad with his exceptional passing range, vision, and ability to dictate the tempo. His leadership qualities on the field ensure that the team maintains control in midfield. His salary reflects his pivotal role in the team’s setup, as he is not only a defensive midfielder but also a creative force capable of breaking down opposition defenses. Maart’s experience and consistency make him one of the club's most valuable assets.",
    age: 29,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-17",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Samkelo Zwane",
    slug: "samkelo-zwane",
    occupation: "Football Player",
    salary: 55000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Samkelo%20Zwane.jpg",
    description: "Zwane, a talented attacking midfielder, earns R55,000 per month. At 23, the South African is still in the early stages of his career, but he has already impressed with his technical skills and creativity. Known for his ability to link up play and make incisive passes, Zwane’s versatility makes him an important squad player. His salary reflects his developing status within the team, but his potential to influence games is clear. As he gains more experience, Zwane could emerge as one of the team’s key playmakers and a regular starter for Kaizer Chiefs.",
    age: 23,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-18",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Wandile Duba",
    slug: "wandile-duba",
    occupation: "Football Player",
    salary: 20000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Wandile%20Duba.jpg",
    description: "Duba, a young talent at just 20 years old, earns R20,000 per month. As a developing player, he has shown flashes of brilliance with his speed and agility. His low salary reflects his status as an emerging talent, but his potential is undeniable. Duba’s ability to beat defenders and create opportunities has caught the eye of coaches. While he is still learning the ropes, his determination and work ethic suggest that he has the ability to make an impact in the future. With time and experience, Duba could play a more prominent role in Kaizer Chiefs’ attacking setup.",
    age: 20,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-19",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Ranga Chivaviro",
    slug: "ranga-chivaviro",
    occupation: "Football Player",
    salary: 150000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Ranga%20Chivaviro.jpg",
    description: "Chivaviro, at 32, is an experienced forward earning R150,000 monthly. The South African striker is known for his physicality, aerial ability, and clinical finishing. His wealth of experience in top-tier football allows him to make intelligent runs and create goal-scoring opportunities. His salary reflects his experience and importance to the team as a reliable striker. Chivaviro’s ability to hold up play and bring teammates into the game makes him an asset. Despite being in the later stages of his career, he continues to be an important figure for Kaizer Chiefs in the attacking third.",
    age: 32,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-20",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Edson Castillo",
    slug: "edson-castillo",
    occupation: "Football Player",
    salary: 150000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Edson%20Castillo.jpg",
    description: "Castillo, a 30-year-old Venezuelan midfielder, earns R150,000 per month. His experience in international football adds significant value to Kaizer Chiefs, where he plays a crucial role in both defense and midfield. Castillo is known for his vision, passing range, and ability to disrupt opposition play. His defensive contributions, combined with his ability to dictate the tempo of the game, make him a well-rounded player. His salary is a reflection of his experience and importance within the team. Castillo continues to be a key figure in Kaizer Chiefs’ midfield, providing stability and leadership.",
    age: 30,
    country: "Venezuela",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-21",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Mfundo Vilakazi",
    slug: "mfundo-vilakazi",
    occupation: "Football Player",
    salary: 100000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Mfundo%20Vilakazi.jpg",
    description: "Vilakazi, at just 19, is one of the brightest young talents in South African football, earning R100,000 monthly. The forward is known for his explosive pace, dribbling skills, and ability to find the back of the net. His youthful energy and enthusiasm make him a real threat in one-on-one situations. His salary reflects his potential and growing importance to Kaizer Chiefs. As he gains more experience, Vilakazi’s role in the squad is expected to expand. With continued development, he could establish himself as one of the top young strikers in the league.",
    age: 19,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-22",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Ashley Du Preez",
    slug: "ashley-du-preez",
    occupation: "Football Player",
    salary: 300000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Ashley%20Du%20Preez.jpg",
    description: "Du Preez, a dynamic forward, earns R300,000 per month. At 27, the South African striker has established himself as one of the top talents in the league. Known for his speed, technical ability, and finishing, Du Preez offers a constant threat in the final third. His salary reflects his key role in Kaizer Chiefs’ attack, as he can both create and finish chances. His versatility allows him to play across the forward line, making him a valuable asset. As he continues to perform at a high level, Du Preez will remain a crucial player for the club.",
    age: 27,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-23",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Gaston Sirino",
    slug: "gaston-sirino",
    occupation: "Football Player",
    salary: 300000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Gaston%20Sirino.jpg",
    description: "Sirino, a 34-year-old Uruguayan midfielder, earns R300,000 per month. With his exceptional dribbling, creativity, and vision, Sirino has been a standout player for Kaizer Chiefs. His technical ability allows him to unlock opposition defenses and provide key assists. His salary reflects his experience and importance to the team. Although in the later stages of his career, Sirino remains a key player who can influence matches with his skill and leadership. His understanding of the game and ability to control the pace make him an invaluable asset in the squad.",
    age: 34,
    country: "Uruguay",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-24",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Njabulo Blom",
    slug: "njabulo-blom",
    occupation: "Football Player",
    salary: 543000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Njabulo%20Blom.jpg",
    description: "Blom, a dynamic defensive midfielder, earns a hefty R543,000 per month. At 25, the South African has already made a name for himself with his versatility and strong work ethic. His ability to break up opposition attacks, combined with his passing range, makes him an essential player for Kaizer Chiefs. His salary reflects his importance to the team, as he provides both defensive solidity and attacking support. Blom’s leadership and physical presence in midfield ensure that the team remains competitive. As he continues to grow, Blom has the potential to become one of the best in his position.",
    age: 25,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-25",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Sphiwe Msimango",
    slug: "sphiwe-msimango",
    occupation: "Football Player",
    salary: 100000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Sphiwe%20Msimango.jpg",
    description: "Msimango, a 27-year-old center-back, earns R100,000 per month. Known for his aerial ability, tackling, and leadership qualities, Msimango is a key figure in the defensive line. His salary reflects his solid performances and growing importance in the team. As a physical and commanding presence, he is integral in stopping opposition attacks and organizing the backline. Msimango’s consistency and work ethic make him a reliable player, and his performances continue to demonstrate his ability to compete at the highest level in South African football. He will remain an important part of Kaizer Chiefs’ defense for years to come.",
    age: 27,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-26",
    categories: ["football-players"]
  },
  {
    id: uuidv4(),
    name: "Pule Mmodi",
    slug: "pule-mmodi",
    occupation: "Football Player",
    salary: 150000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Pule%20Mmodi.jpg",
    description: "Mmodi, a 32-year-old forward, earns R150,000 per month. Known for his dribbling skills, pace, and ability to score goals, Mmodi has been an important player for Kaizer Chiefs. His salary reflects his role as a senior member of the squad who can influence matches in the attacking third. Despite being in the later stages of his career, Mmodi’s experience and technical ability ensure he remains a threat. His ability to create space and score goals makes him a valuable asset to the team, and he will continue to provide leadership and expertise in Kaizer Chiefs' offensive play.",
    age: 32,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-27",
    categories: ["football-players"]
  }

];

// Format salary for display
export const formatSalary = (salary: number, currency: string) => {
  return salary.toLocaleString('en-US', {
    style: 'currency',
    currency: currency,
    maximumFractionDigits: 1,
    minimumFractionDigits: 0,
    notation: 'compact',
    compactDisplay: 'short',
  });
};

// Find a celebrity by slug
export const findCelebrityBySlug = (slug: string): Celebrity | undefined => {
  return celebrities.find(celebrity => celebrity.slug === slug);
};

// Get similar celebrities (same industry or similar salary)
export const getSimilarCelebrities = (celebrity: Celebrity, limit: number = 5): Celebrity[] => {
  return celebrities
    .filter(c => 
      c.id !== celebrity.id && 
      (c.industry === celebrity.industry || 
       Math.abs(c.salary - celebrity.salary) / celebrity.salary < 0.3)
    )
    .sort((a, b) => {
      // Sort by industry match first, then by salary similarity
      if (a.industry === celebrity.industry && b.industry !== celebrity.industry) {
        return -1;
      }
      if (a.industry !== celebrity.industry && b.industry === celebrity.industry) {
        return 1;
      }
      return Math.abs(a.salary - celebrity.salary) - Math.abs(b.salary - celebrity.salary);
    })
    .slice(0, limit);
};
