
import { v4 as uuidv4 } from 'uuid';

// Define Celebrity interface
export interface Celebrity {
  id: string;
  name: string;
  slug: string;
  occupation: string;
  salary: number;
  currency: string;
  imageUrl?: string;
  description: string;
  age: number;
  country: string;
  company?: string;
  industry: string;
  source: string;
  lastUpdated: string;
  categories: string[];
}

// Sample celebrity data
export const celebrities: Celebrity[] = [
  {
    id: uuidv4(),
    name: "Lucas Ribeiro",
    slug: "lucas-ribeiro",
    occupation: "Football Player",
    salary: 850000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2023/10/a_%C2%ACKit-Shoot-1447.jpg",
    description: "Lucas Ribeiro is a highly-rated Brazilian professional footballer who excels as an attacking midfielder for Mamelodi Sundowns FC. Known for his ability to revamp the midfield and generate interest from top-flight clubs like Burnley, Ribeiro is considered one of the best players in the league. Born on October 9, 1998, making him 27 years old in 2025, his estimated monthly salary ranges from R700,000 to R1,000,000. He brings international experience and skill to the Mamelodi Sundowns squad.",
    age: 27,
    country: "Brazil",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Ronwen Williams",
    slug: "ronwen-williams",
    occupation: "Football Player",
    salary: 500000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Williams.jpg",
    description: "Ronwen Williams is a prominent South African professional footballer who plays as a goalkeeper for Mamelodi Sundowns FC and captains the South African national team. With over 12 years of professional experience, Williams joined Sundowns in 2022 after a long stint at SuperSport United. Born on January 21, 1992, making him 32 years old in 2025, his estimated monthly salary is R500,000. He is a key player for both club and country.",
    age: 32,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Denis Onyango",
    slug: "denis-onyango",
    occupation: "Football Player",
    salary: 450000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Onyango-4.jpg",
    description: "Denis Onyango is a highly experienced Ugandan professional footballer who serves as a goalkeeper for Mamelodi Sundowns FC. Having joined the club in 2014, Onyango has had a distinguished career, also representing Uganda in the Africa Cup of Nations and captaining the national team until his retirement in 2021. Born on May 15, 1985, making him 39 years old in 2025, his alleged monthly salary is R450,000. His leadership and goalkeeping skills are invaluable to Mamelodi Sundowns.",
    age: 39,
    country: "Uganda",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Marcelo Allende",
    slug: "marcelo-allende",
    occupation: "Football Player",
    salary: 430000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Allende.jpg",
    description: "Marcelo Allende is a talented Chilean professional footballer who plays as an attacking midfielder for Mamelodi Sundowns FC and the Chile national team. Regarded as a top youth prospect in Chile and having captained their team during the 2015 FIFA U-17 World Cup, Allende brings youthful energy and skill to the squad. Born on April 7, 2002, making him 22 years old in 2025, Marcelo Allende earns a monthly salary of R430,000. He is considered a key player for the future of Mamelodi Sundowns.",
    age: 22,
    country: "Chile",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Thapelo Morena",
    slug: "thapelo-morena",
    occupation: "Football Player",
    salary: 400000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Morena-2.jpg",
    description: "Thapelo Morena is a versatile South African professional footballer who plays as both a defender and midfielder for Mamelodi Sundowns FC. Joining the club in 2016 from Bloemfontein Celtic, where he began his professional career in 2013, Morena is a valuable asset to the team. Born on August 6, 1993, making him 31 years old in 2025, his estimated monthly salary is R400,000, making him one of the highest-paid players at Sundowns in 2024. He also represents the South African national team.",
    age: 31,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Peter Shalulile",
    slug: "peter-shalulile",
    occupation: "Football Player",
    salary: 400000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Shalulile-1.jpg",
    description: "Peter Shalulile is a Namibian professional footballer who plays as a striker for Mamelodi Sundowns FC. He also represents the Namibian national team, showcasing his talent on both club and international levels. Shalulile began his career in 2011 at Tura Magic and later moved to Highlands Park in 2015 before joining Sundowns. Born on October 23, 1993, making him 31 years old in 2025, his estimated monthly salary is R400,000. His striking prowess makes him a key player for Mamelodi Sundowns.",
    age: 31,
    country: "Namibia",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Keanu Cupido",
    slug: "keanu-cupido",
    occupation: "Football Player",
    salary: 450000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2025/02/Cupido-WHite-BAckground-Square.jpg",
    description: "Keanu Cupido is a South African defender who plays for Mamelodi Sundowns FC and the Bafana Bafana (South African national team). He recently joined Sundowns from Cape Town City FC before the close of the January 2025 transfer window. Born on January 15, 1998, making him 27 years old in 2025, his estimated monthly salary ranges from R350,000 to R570,000. Cupido is a promising defender strengthening the Sundowns' squad.",
    age: 27,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Teboho Mokoena",
    slug: "teboho-mokoena",
    occupation: "Football Player",
    salary: 400000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Mokoena.jpg",
    description: "Teboho Mokoena is a proficient South African professional footballer recognized for his skills as a midfielder. He has proudly represented South Africa in various international competitions, showcasing his talent on the global stage. Mokoena officially joined Mamelodi Sundowns on January 27, 2022. Born on January 24, 1997, making him 28 years old in 2025, his alleged monthly salary ranges between R300,000 and R500,000. He is a valuable midfielder for Mamelodi Sundowns.",
    age: 28,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Mosa Lebusa",
    slug: "mosa-lebusa",
    occupation: "Football Player",
    salary: 300000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Lebusa-2.jpg",
    description: "Mosa Lebusa is a South African professional footballer who plays as a centre-back and left-back for Mamelodi Sundowns FC. He had his youth career at Dinonyana FC and Ajax Cape Town, making his senior debut in 2012. Lebusa joined Mamelodi Sundowns in 2018 and has become a regular in the starting XI. Born on October 10, 1992, making him 32 years old in 2025, his estimated monthly salary is R300,000. He is a reliable defender for the team.",
    age: 32,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Aubrey Modiba",
    slug: "aubrey-modiba",
    occupation: "Football Player",
    salary: 290000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Modiba-2.jpg",
    description: "Aubrey Modiba is a South African professional footballer who plays as a left winger for Mamelodi Sundowns FC. He has achieved career highs, including representing the South African national team at the Rio De Janeiro 2016 Summer Olympics. Born on July 23, 1995, making him 30 years old in 2025, Modiba's rumored monthly salary at Sundowns is around R290,000. He is a dynamic winger known for his speed and skill.",
    age: 30,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Themba Zwane",
    slug: "themba-zwane",
    occupation: "Football Player",
    salary: 350000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Zwane-3.jpg",
    description: "Themba Zwane is a highly regarded South African professional football player who operates as an attacking midfielder for Mamelodi Sundowns FC and the national team. Known for his goal-scoring ability and playmaking skills, Zwane is a key figure in the Sundowns' midfield. Born on August 3, 1989, making him 36 years old in 2025, his alleged monthly salary at Sundowns ranges from R250,000 to R500,000. His experience and talent make him a vital player.",
    age: 36,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Mothobi Mvala",
    slug: "mothobi-mvala",
    occupation: "Football Player",
    salary: 250000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Mvala1.jpg",
    description: "Mothobi Mvala is a South African professional football central defender who plays for Mamelodi Sundowns FC and the South African national team. Mvala got his big break at Highlands Park and was part of the 2016 Rio Olympics squad. Born on June 14, 1994, making him 30 years old in 2025, his estimated monthly salary at Sundowns is R250,000. He is a solid defender with national team experience.",
    age: 30,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Iqraam Rayners",
    slug: "iqraam-rayners",
    occupation: "Football Player",
    salary: 350000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2024/08/Rayners-.jpg",
    description: "Iqraam Rayners is a highly regarded South African professional footballer who plays as a forward for Mamelodi Sundowns FC and the Bafana Bafana. Considered one of South Africa's best attackers, Rayners joined the Brazilians in 2024 from Stellenbosch. Born on December 19, 1995, making him 30 years old in 2025, his estimated monthly salary ranges from R200,000 to R500,000. He is a dynamic forward adding firepower to the Sundowns' attack.",
    age: 30,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Khuliso Mudau",
    slug: "khuliso-mudau",
    occupation: "Football Player",
    salary: 300000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Mudau-2.jpg",
    description: "Khuliso Mudau is a South African professional footballer who plays as a right-back for Mamelodi Sundowns FC and the South African national team. Currently regarded as one of the best right-backs in the league, Mudau signed for Mamelodi Sundowns in October 2020 on a five-year contract. Born on April 26, 1995, making him 30 years old in 2025, his estimated monthly salary is between R200,000 and R400,000. He is a key defender for both club and country.",
    age: 30,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Lucas Suarez",
    slug: "lucas-suarez",
    occupation: "Football Player",
    salary: 300000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2025/02/Suarez-WHite-BAckground-Square.jpg",
    description: "Lucas Suarez is an Argentine professional footballer who plays as a defender and left-back for Mamelodi Sundowns FC. He came on loan from Estudiantes de Río Cuarto and was previously on loan at Talleres, where he reportedly earned around R380,000 monthly. Born on March 17, 1995, making him 30 years old in 2025, his estimated monthly salary at Mamelodi Sundowns ranges from R200,000 to R400,000. He brings international defensive experience to the team.",
    age: 30,
    country: "Argentina",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Grant Kekana",
    slug: "grant-kekana",
    occupation: "Football Player",
    salary: 250000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Kekana-2.jpg",
    description: "Grant Kekana is a South African professional footballer who plays as a defender and centre-back for Mamelodi Sundowns FC. Kekana joined Mamelodi Sundowns in July 2021 from their rivals, SuperSport United. Born on October 31, 1992, making him 33 years old in 2025, his estimated monthly salary is between R200,000 and R300,000. He is an experienced defender in the Mamelodi Sundowns squad.",
    age: 33,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Arthur Sales",
    slug: "arthur-sales",
    occupation: "Football Player",
    salary: 250000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Sales.jpg",
    description: "Arthur Sales is a Brazilian professional footballer who plays as a centre-forward for Mamelodi Sundowns FC. He joined the Sundowns in July 2024 for a record transfer fee from Belgian side, Lomel. Born on July 3, 2002, making him 23 years old in 2025, his estimated monthly salary is between R200,000 and R300,000. Despite a shaky start, Sales has become a part of the Mamelodi Sundowns squad, bringing his attacking abilities to the team.",
    age: 23,
    country: "Brazil",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Rivaldo Coetzee",
    slug: "rivaldo-coetzee",
    occupation: "Football Player",
    salary: 200000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2020/12/Coetzee-3.jpg",
    description: "Rivaldo Coetzee is a South African professional footballer who plays as a defender and central midfielder for Mamelodi Sundowns FC. He also plays for the South African national team and made his professional debut at Ajax Cape Town. Coetzee was part of the Bafana Bafana squad in the 2016 Rio Olympics. Born on October 16, 1996, making him 29 years old in 2025, his estimated monthly salary is R200,000. He is a versatile player with both club and national team experience.",
    age: 29,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
  {
    id: uuidv4(),
    name: "Jayden Adams",
    slug: "jayden-adams",
    occupation: "Football Player",
    salary: 200000,
    currency: "ZAR",
    imageUrl: "https://sundownsfc.co.za/wp-content/uploads/2025/02/Adams-WHite-BAckground-Square.jpg",
    description: "Jayden Adams is a young and promising South African professional footballer who plays as an attacking midfielder for Mamelodi Sundowns FC. He recently arrived at the club from Stellies, signing a deal until at least June 2028. Adams also plays for the South African national team. Born on May 5, 2001, making him 24 years old in 2025, his estimated monthly salary is in the region of R100,000 to R200,000. He is considered a talented midfielder with a bright future at Sundowns.",
    age: 24,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Research",
    lastUpdated: "2025-04-02"
  },
    {
    id: uuidv4(),
    name: "Nkosingiphile Ngcobo",
    slug: "nkosingiphile-ngcobo",
    occupation: "Football Player",
    salary: 30000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Nkosingiphile%20Ngcobo.jpg",
    description: "Ngcobo, a highly skilled midfielder, earns R30,000 monthly. At 25, he has developed into a creative playmaker with impressive dribbling and passing ability. As a South African talent nurtured at Kaizer Chiefs, he possesses great vision and composure on the ball. Though his salary is relatively modest, his potential remains significant. His performances reflect a player eager to make a lasting impact, and with more game time, he could become a crucial figure. His ability to control the tempo of matches and deliver key assists makes him an essential part of the team’s attacking strategy.",
    age: 25,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-03"
  },
  {
    id: uuidv4(),
    name: "Happy Mashiane",
    slug: "happy-mashiane",
    occupation: "Football Player",
    salary: 50000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Happy%20Mashiane.jpg",
    description: "Mashiane is a versatile left-back earning R50,000 per month. At 27, he has gained valuable experience, solidifying his defensive capabilities while also contributing in attack. The South African full-back is known for his quick runs down the flank and accurate crosses. His salary reflects his squad role, but his adaptability allows him to play multiple positions when needed. His commitment to both defense and attack makes him a reliable option for Kaizer Chiefs. With his technical skills and tactical awareness, he has the potential to further establish himself as a key player in the coming seasons.",
    age: 27,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-04"

  },
  {
    id: uuidv4(),
    name: "Brandon Petersen",
    slug: "brandon-petersen",
    occupation: "Football Player",
    salary: 70000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Brandon%20Petersen.jpg",
    description: "Petersen, a seasoned South African goalkeeper, earns R70,000 monthly. At 30, he brings experience and composure to the squad. His quick reflexes and ability to organize the defense make him a reliable shot-stopper. Having played for multiple clubs in the South African league, he understands the tactical demands of top-flight football. His leadership in the box ensures stability, and his distribution skills allow smooth transitions from defense to attack. Although he faces competition for the starting role, his performances prove he is a dependable choice when called upon, making him a valuable part of the team.",
    age: 30,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-05"
  },
  {
    id: uuidv4(),
    name: "Dillan Solomons",
    slug: "dillan-solomons",
    occupation: "Football Player",
    salary: 120000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Dillan%20Solomons.jpg",
    description: "Solomons is a dynamic right-back earning R120,000 per month. At 28, the South African defender brings pace and versatility to Kaizer Chiefs. His ability to overlap and deliver dangerous crosses adds an attacking edge, while his defensive awareness ensures solidity at the back. His salary reflects his growing importance in the squad, as his energetic playing style allows him to excel in different tactical systems. His work ethic and determination to contribute in both offensive and defensive phases make him a valuable asset. With his consistency, he has the potential to become one of the league’s top full-backs.",
    age: 28,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Sibongiseni Mthethwa",
    slug: "sibongiseni-mthethwa",
    occupation: "Football Player",
    salary: 70000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Sibongiseni%20Mthethwa.jpg",
    description: "Mthethwa, a strong and disciplined defensive midfielder, earns R70,000 monthly. At 30, the South African enforcer provides balance and control in midfield. His role in breaking up opposition attacks and shielding the defense is crucial for Kaizer Chiefs. His ability to win duels, intercept passes, and distribute the ball effectively makes him a key component of the team. While his salary is moderate, his value to the squad cannot be overlooked. His leadership and work rate allow attacking players more freedom to create chances. His experience and tactical intelligence make him a vital presence in the midfield.",
    age: 30,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Tebogo Potsane",
    slug: "tebogo-potsane",
    occupation: "Football Player",
    salary: 70000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Tebogo%20Potsane.jpg",
    description: "Potsane, an experienced attacking midfielder, earns R70,000 per month. At 31, the South African playmaker continues to showcase his dribbling and passing skills. His creativity in the final third allows him to unlock defenses and create scoring opportunities. Despite not always being a starter, his ability to impact games as a substitute makes him a useful squad player. His salary reflects his contributions, as he offers valuable experience and depth to the attacking lineup. His vision, technical ability, and composure under pressure ensure he remains a reliable asset for the team as they compete at the highest level.",
    age: 31,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "Bruce Bvuma",
    slug: "bruce-bvuma",
    occupation: "Football Player",
    salary: 75000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Bruce%20Bvuma.jpg",
    description: "Bvuma, a talented goalkeeper, earns R75,000 monthly. At 29, the South African shot-stopper has built a reputation for his sharp reflexes and ability to perform in high-pressure situations. He has been with Kaizer Chiefs for several seasons, proving to be a dependable backup option. His quick reactions and confidence in one-on-one situations make him a strong presence in goal. His salary reflects his growing experience and ability to step up when needed. As he continues to improve, he has the potential to solidify his role as a consistent first-choice goalkeeper for the team.",
    age: 29,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Zitha Kwinika",
    slug: "zitha-kwinika",
    occupation: "Football Player",
    salary: 370000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Zitha%20Kwinika.jpg",
    description: "Kwinika, one of the highest-paid players at Kaizer Chiefs, earns R370,000 per month. At 31, the South African center-back brings leadership and defensive stability. His aerial dominance, tactical awareness, and strong tackling ability make him a key figure in the squad. His salary highlights his importance, as he is entrusted with organizing the backline. His composure on the ball allows him to initiate attacks from defense, a crucial trait in modern football. His wealth of experience at the top level ensures he remains an essential leader for Kaizer Chiefs, helping to guide younger players in the squad.",
    age: 31,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-10"
  },
  {
    id: uuidv4(),
    name: "Thabo Cele",
    slug: "thabo-cele",
    occupation: "Football Player",
    salary: 480000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Thabo%20Cele.jpg",
    description: "Cele, a hardworking central midfielder, earns R120,000 monthly. At 28, the South African playmaker brings energy, passing accuracy, and defensive contribution. His ability to dictate the tempo of matches makes him a valuable asset. With experience in both domestic and international football, he understands the demands of high-level competition. His salary reflects his importance as a balanced midfielder capable of transitioning between attack and defense. His leadership and composure ensure stability in the middle of the park. With his technical skills and work ethic, he continues to be a key player for Kaizer Chiefs.",
    age: 28,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-11"
  },
  {
    id: uuidv4(),
    name: "Makabi Lilepo",
    slug: "makabi-lilepo",
    occupation: "Football Player",
    salary: 130000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Makabi%20Lilepo.jpg",
    description: "Lilepo, an electrifying forward from DR Congo, earns R130,000 per month. At 27, he has developed into a dangerous attacking threat, using his speed and dribbling skills to trouble defenders. His ability to score and assist makes him one of the team’s most exciting players. His salary reflects his importance, as he has the capability to change games with his attacking prowess. His experience in African competitions has enhanced his confidence, making him a crucial figure in Kaizer Chiefs’ attacking setup. If he maintains his consistency, he could establish himself as one of the league’s top forwards.",
    age: 27,
    country: "DR Congo",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-12"
  },
  {
    id: uuidv4(),
    name: "Tashreeq Morris",
    slug: "tashreeq-morris",
    occupation: "Football Player",
    salary: 90000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Tashreeq%20Morris.jpg",
    description: "Morris, a versatile forward, earns R90,000 monthly. At 30, the South African attacker has built a reputation as a hardworking and intelligent player. His ability to play as a striker or an attacking midfielder adds depth to the squad. His finishing ability, combined with his strength in aerial duels, makes him a valuable attacking option. His salary reflects his experience and steady contributions. His movement and link-up play help create chances for teammates. As he continues to perform, he remains an important figure in the squad, bringing both creativity and goal-scoring ability.",
    age: 30,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-13"
  },
  {
    id: uuidv4(),
    name: "Edmilson Dove",
    slug: "edmilson-dove",
    occupation: "Football Player",
    salary: 105000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Edmilson%20Dove.jpg",
    description: "Dove, a Mozambican international defender, earns R105,000 per month. At 30, his defensive experience and technical ability make him a key part of the squad. Comfortable playing at center-back or left-back, he brings versatility and composure. His ball-playing skills allow him to contribute to the team’s build-up play. His salary reflects his reliability in defense, as he consistently delivers solid performances. His ability to read the game and time tackles effectively makes him a dependable option. With his leadership and adaptability, he remains an integral part of Kaizer Chiefs’ defensive setup.",
    age: 30,
    country: "Mozambique",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-14"
  },
  {
    id: uuidv4(),
    name: "Reeve Frosler",
    slug: "reeve-frosler",
    occupation: "Football Player",
    salary: 150000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Reeve%20Frosler.jpg",
    description: "Frosler, a technically gifted right-back, earns R150,000 per month. At 27, the South African full-back is known for his precise crossing, defensive awareness, and attacking contribution. His salary reflects his crucial role in the team. His ability to transition seamlessly between defense and attack makes him one of the most complete full-backs in the league. His consistency and work rate ensure he remains a vital player for Kaizer Chiefs.",
    age: 27,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-15"
  },
  {
    id: uuidv4(),
    name: "Mduduzi Shabalala",
    slug: "mduduzi-shabalala",
    occupation: "Football Player",
    salary: 33000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Mduduzi%20Shabalala.jpg",
    description: "Shabalala, at just 21, is a promising midfielder with immense potential. Earning R33,000 per month, he has already shown his flair and creativity on the ball. His technical ability, vision, and playmaking skills make him one of the most exciting young talents in South African football. His salary reflects his role in the squad as a developing player, and he is expected to continue growing and contributing to Kaizer Chiefs in the future. With the right development, Shabalala could become a key player in the South African national team as well.",
    age: 21,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-16"
  },
  {
    id: uuidv4(),
    name: "Yusuf Maart",
    slug: "yusuf-maart",
    occupation: "Football Player",
    salary: 300000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Yusuf%20Maart.jpg",
    description: "Maart, a central midfielder, is a standout performer at Kaizer Chiefs, earning R300,000 per month. At 29, the South African has become a crucial part of the squad with his exceptional passing range, vision, and ability to dictate the tempo. His leadership qualities on the field ensure that the team maintains control in midfield. His salary reflects his pivotal role in the team’s setup, as he is not only a defensive midfielder but also a creative force capable of breaking down opposition defenses. Maart’s experience and consistency make him one of the club's most valuable assets.",
    age: 29,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-17"
  },
  {
    id: uuidv4(),
    name: "Samkelo Zwane",
    slug: "samkelo-zwane",
    occupation: "Football Player",
    salary: 55000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Samkelo%20Zwane.jpg",
    description: "Zwane, a talented attacking midfielder, earns R55,000 per month. At 23, the South African is still in the early stages of his career, but he has already impressed with his technical skills and creativity. Known for his ability to link up play and make incisive passes, Zwane’s versatility makes him an important squad player. His salary reflects his developing status within the team, but his potential to influence games is clear. As he gains more experience, Zwane could emerge as one of the team’s key playmakers and a regular starter for Kaizer Chiefs.",
    age: 23,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-18"
  },
  {
    id: uuidv4(),
    name: "Wandile Duba",
    slug: "wandile-duba",
    occupation: "Football Player",
    salary: 20000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Wandile%20Duba.jpg",
    description: "Duba, a young talent at just 20 years old, earns R20,000 per month. As a developing player, he has shown flashes of brilliance with his speed and agility. His low salary reflects his status as an emerging talent, but his potential is undeniable. Duba’s ability to beat defenders and create opportunities has caught the eye of coaches. While he is still learning the ropes, his determination and work ethic suggest that he has the ability to make an impact in the future. With time and experience, Duba could play a more prominent role in Kaizer Chiefs’ attacking setup.",
    age: 20,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-19"
  },
  {
    id: uuidv4(),
    name: "Ranga Chivaviro",
    slug: "ranga-chivaviro",
    occupation: "Football Player",
    salary: 150000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Ranga%20Chivaviro.jpg",
    description: "Chivaviro, at 32, is an experienced forward earning R150,000 monthly. The South African striker is known for his physicality, aerial ability, and clinical finishing. His wealth of experience in top-tier football allows him to make intelligent runs and create goal-scoring opportunities. His salary reflects his experience and importance to the team as a reliable striker. Chivaviro’s ability to hold up play and bring teammates into the game makes him an asset. Despite being in the later stages of his career, he continues to be an important figure for Kaizer Chiefs in the attacking third.",
    age: 32,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-20"
  },
  {
    id: uuidv4(),
    name: "Edson Castillo",
    slug: "edson-castillo",
    occupation: "Football Player",
    salary: 150000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Edson%20Castillo.jpg",
    description: "Castillo, a 30-year-old Venezuelan midfielder, earns R150,000 per month. His experience in international football adds significant value to Kaizer Chiefs, where he plays a crucial role in both defense and midfield. Castillo is known for his vision, passing range, and ability to disrupt opposition play. His defensive contributions, combined with his ability to dictate the tempo of the game, make him a well-rounded player. His salary is a reflection of his experience and importance within the team. Castillo continues to be a key figure in Kaizer Chiefs’ midfield, providing stability and leadership.",
    age: 30,
    country: "Venezuela",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-21"
  },
  {
    id: uuidv4(),
    name: "Mfundo Vilakazi",
    slug: "mfundo-vilakazi",
    occupation: "Football Player",
    salary: 100000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Mfundo%20Vilakazi.jpg",
    description: "Vilakazi, at just 19, is one of the brightest young talents in South African football, earning R100,000 monthly. The forward is known for his explosive pace, dribbling skills, and ability to find the back of the net. His youthful energy and enthusiasm make him a real threat in one-on-one situations. His salary reflects his potential and growing importance to Kaizer Chiefs. As he gains more experience, Vilakazi’s role in the squad is expected to expand. With continued development, he could establish himself as one of the top young strikers in the league.",
    age: 19,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-22"
  },
  {
    id: uuidv4(),
    name: "Ashley Du Preez",
    slug: "ashley-du-preez",
    occupation: "Football Player",
    salary: 300000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Ashley%20Du%20Preez.jpg",
    description: "Du Preez, a dynamic forward, earns R300,000 per month. At 27, the South African striker has established himself as one of the top talents in the league. Known for his speed, technical ability, and finishing, Du Preez offers a constant threat in the final third. His salary reflects his key role in Kaizer Chiefs’ attack, as he can both create and finish chances. His versatility allows him to play across the forward line, making him a valuable asset. As he continues to perform at a high level, Du Preez will remain a crucial player for the club.",
    age: 27,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-23"
  },
  {
    id: uuidv4(),
    name: "Gaston Sirino",
    slug: "gaston-sirino",
    occupation: "Football Player",
    salary: 300000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Gaston%20Sirino.jpg",
    description: "Sirino, a 34-year-old Uruguayan midfielder, earns R300,000 per month. With his exceptional dribbling, creativity, and vision, Sirino has been a standout player for Kaizer Chiefs. His technical ability allows him to unlock opposition defenses and provide key assists. His salary reflects his experience and importance to the team. Although in the later stages of his career, Sirino remains a key player who can influence matches with his skill and leadership. His understanding of the game and ability to control the pace make him an invaluable asset in the squad.",
    age: 34,
    country: "Uruguay",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-24"
  },
  {
    id: uuidv4(),
    name: "Njabulo Blom",
    slug: "njabulo-blom",
    occupation: "Football Player",
    salary: 543000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Njabulo%20Blom.jpg",
    description: "Blom, a dynamic defensive midfielder, earns a hefty R543,000 per month. At 25, the South African has already made a name for himself with his versatility and strong work ethic. His ability to break up opposition attacks, combined with his passing range, makes him an essential player for Kaizer Chiefs. His salary reflects his importance to the team, as he provides both defensive solidity and attacking support. Blom’s leadership and physical presence in midfield ensure that the team remains competitive. As he continues to grow, Blom has the potential to become one of the best in his position.",
    age: 25,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-25"
  },
  {
    id: uuidv4(),
    name: "Sphiwe Msimango",
    slug: "sphiwe-msimango",
    occupation: "Football Player",
    salary: 100000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Sphiwe%20Msimango.jpg",
    description: "Msimango, a 27-year-old center-back, earns R100,000 per month. Known for his aerial ability, tackling, and leadership qualities, Msimango is a key figure in the defensive line. His salary reflects his solid performances and growing importance in the team. As a physical and commanding presence, he is integral in stopping opposition attacks and organizing the backline. Msimango’s consistency and work ethic make him a reliable player, and his performances continue to demonstrate his ability to compete at the highest level in South African football. He will remain an important part of Kaizer Chiefs’ defense for years to come.",
    age: 27,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-26"
  },
  {
    id: uuidv4(),
    name: "Pule Mmodi",
    slug: "pule-mmodi",
    occupation: "Football Player",
    salary: 150000,
    currency: "ZAR",
    imageUrl: "https://kcpub.azureedge.net/storage/images/players/Pule%20Mmodi.jpg",
    description: "Mmodi, a 32-year-old forward, earns R150,000 per month. Known for his dribbling skills, pace, and ability to score goals, Mmodi has been an important player for Kaizer Chiefs. His salary reflects his role as a senior member of the squad who can influence matches in the attacking third. Despite being in the later stages of his career, Mmodi’s experience and technical ability ensure he remains a threat. His ability to create space and score goals makes him a valuable asset to the team, and he will continue to provide leadership and expertise in Kaizer Chiefs' offensive play.",
    age: 32,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-27"
  },
  {
    id: uuidv4(),
    name: "Nkosinathi Sibisi",
    slug: "nkosinathi-sibisi",
    occupation: "Football Player",
    salary: 180000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/nkosinathi-sibisi-defender-home-headshot-2024-25-kit-brandon-barnard-photography-L1040420.png",
    description: "Defender Nkosinathi Sibisi's reported R180,000 salary reflects his status as a key signing and a player fulfilling a lifelong dream. Arriving before the 2022/23 season, the former Golden Arrows stalwart brought over 100 games of top-flight experience. His robust defending style and fighting spirit are qualities Pirates clearly valued, warranting a significant wage. As a boyhood supporter aiming to emulate heroes like Mbulelo Mabizela, Sibisi's earnings align with the expectation that he will be a cornerstone of the defence and contribute significantly to the club's trophy ambitions for years to come.",
    age: 29,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Tapelo Xoki",
    slug: "tapelo-xoki",
    occupation: "Football Player",
    salary: 100000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/tapelo-xoki-defender-home-headshot-2024-25-kit-brandon-barnard-photography-L1040415.png",
    description: "Tapelo Xoki's reported R100,000 salary aligns with the acquisition of a player known for his natural leadership qualities. Arriving after an eight-year stint at AmaZulu, where he often wore the captain's armband, Xoki brought proven PSL experience and defensive stability. His compensation reflects the value Pirates placed on securing not just a capable defender, but also a strong character and leader within the dressing room. Inspired by Thiago Silva, Xoki aims to leave a lasting mark, and his salary represents a solid investment in experience and leadership for the squad.",
    age: 29,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Bandile Shandu",
    slug: "bandile-shandu",
    occupation: "Football Player",
    salary: 200000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/bandile-shandu-defender-home-headshot-2024-25-kit-brandon-barnard-photography-L1040641.png",
    description: "Utility player Bandile Shandu commands a respectable salary at R200,000, placing him in the upper tier of earners within the squad. This compensation acknowledges the extensive experience he brought upon arrival, having already played over 150 games for Maritzburg United. His versatility, allowing him to fill multiple roles effectively, makes him a valuable asset. The R200,000 figure signifies the club's investment in a proven, reliable performer capable of contributing significantly to maintaining the team's high standards and competitive edge across different competitions, justifying his substantial wage packet.",
    age: 30,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Deon Hotto",
    slug: "deon-hotto",
    occupation: "Football Player",
    salary: 500000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/deon-hotto-forward-home-headshot-2024-25-kit-brandon-barnard-photography-L1040498.png",
    description: "Standing out significantly on the wage bill is Namibian international Deon Hotto, reportedly earning R500,000. This figure places him firmly among the club's top earners, a reflection of his established quality and importance. Joining in 2020, the dynamic winger brought international experience and a proven track record in the PSL. His high salary underscores the investment Pirates made to secure a player known for his persistence and ability to influence games, expecting him to play a key role in competing for silverware, much like his idol Ryan Giggs did for Manchester United.",
    age: 34,
    country: "Namibia",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Innocent Maela",
    slug: "innocent-maela",
    occupation: "Football Player",
    salary: 150000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/innocent-maela-defender-home-headshot-2024-25-kit-brandon-barnard-photography-L1040596.png",
    description: "As a product of the Orlando Pirates Youth Development system, Innocent Maela's R150,000 salary represents a solid investment in homegrown talent combined with proven leadership. Having successfully captained Thanda Royal Zulu during a loan spell, he returned with valuable experience. His compensation reflects his role as a reliable defender and a figure who understands the club's culture deeply. Maela aims to win trophies for the fans, and his earnings signify his importance within the squad structure as an established player hoping his performances also secure national team recognition.",
    age: 32,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Thabiso Monyane",
    slug: "thabiso-monyane",
    occupation: "Football Player",
    salary: 50000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/thabiso-monyane-defender-home-headshot-2024-25-kit-brandon-barnard-photography-L1040601-op.webp",
    description: "As a young product of the Orlando Pirates Development program, Thabiso Monyane's reported R50,000 salary is indicative of his status as an emerging talent. Breaking into the first team at 19, his earnings reflect his developmental stage rather than peak market value. This wage structure is common for young players proving their worth. His focus on improving with each game aligns with this, suggesting his salary represents the club nurturing homegrown talent, providing opportunities based on potential, with the expectation of growth in both performance and future earning power.",
    age: 24,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Olisa Ndah",
    slug: "olisa-ndah",
    occupation: "Football Player",
    salary: 107000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/olisa-ndah-defender-home-headshot-2024-25-kit-brandon-barnard-photography-L1040392.png",
    description: "Nigerian international Olisa Ndah joined Pirates with a league title under his belt from Akwa United, commanding a salary reported at R107,000. This figure signifies the club's investment in securing a promising, internationally recognised defender. Having represented Nigeria at U23 and senior levels, Ndah brought potential and proven ability. His earnings reflect the value placed on strengthening the defence with relatively young talent possessing international experience. The club secured a player aiming to make his mark in South Africa, justifying a competitive salary within the Pirates' wage structure.",
    age: 27,
    country: "Nigerian",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Ndabayithethwa Ndlondlo",
    slug: "phillip-ndlondlo",
    occupation: "Football Player",
    salary: 80000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/ndabayithetwa-ndlondlo-midfielder-home-headshot-2024-25-kit-brandon-barnard-photography-L1040624.png",
    description: "Secured after a standout season with Marumo Gallants, Ndabayithethwa Ndlondlo's R80,000 salary might be seen as a shrewd investment by Pirates. Despite being highly sought-after, his reported wage isn't among the highest, suggesting the club possibly acquired his versatile midfield talents and high work rate at good value. Known for his stocky build and never-say-die attitude, Ndlondlo provides energy and adaptability. His earnings reflect the club securing a player with significant potential impact without necessarily breaking the bank, adding depth and dynamism to the midfield options available.",
    age: 29,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Miguel Timm",
    slug: "miguel-timm",
    occupation: "Football Player",
    salary: 120000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/miguel-timm-midfielder-home-headshot-2024-25-kit-brandon-barnard-photography-L1040839.png",
    description: "Miguel Timm’s return to Orlando Pirates, where his football journey began, came with a reported salary of R120,000. This figure represents the value placed on his extensive midfield experience, gathered across South Africa and even internationally in the United States. His journey coming full circle adds a narrative element, but his compensation is primarily based on his proven abilities and tactical understanding. Timm sees representing the badge as 'bigger than the athlete,' and his salary reflects the club securing a mature, dedicated professional committed to driving the team towards collecting more silverware.",
    age: 33,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Mkhehleni Makhaula",
    slug: "mkhehleni-makhaula",
    occupation: "Football Player",
    salary: 30000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/makhehlene-makhaula-midfielder-home-headshot-2024-25-kit-brandon-barnard-photography-L1040579.png",
    description: "Veteran midfielder Mkhehleni Makhaula, earning a reported R30,000, represents a different kind of value proposition within the squad's wage structure. While his salary sits at the lower end, he brings significant experience from stints at Free State Stars, Highlands Park, and AmaZulu. Signed mid-season in 2022/23, his compensation might reflect his age (35) or the nature of the deal, but Pirates secured valuable leadership and a combative style economically. His earnings demonstrate that squad building involves balancing high-cost stars with experienced heads secured at more modest figures.",
    age: 35,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Patrick Maswanganyi",
    slug: "patrick-maswanganyi",
    occupation: "Football Player",
    salary: 250000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/patrick-maswanganyi-forward-home-headshot-2024-25-kit-brandon-barnard-photography-L1040610.png",
    description: "Patrick 'Tito' Maswanganyi quickly established himself as a fan favourite, and his reported R250,000 salary places him among Orlando Pirates' top earners. This substantial figure reflects the impact he made after joining from SuperSport United, following formative years in Portugal. His creativity and technical skill, reminiscent of his idol Teko Modise, clearly impressed the club. Maswanganyi's significant earnings underscore the investment made to secure a player seen as pivotal to the team's attacking ambitions, justifying the outlay through consistent, eye-catching performances in the middle of the park.",
    age: 27,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Kabelo Dlamini",
    slug: "kabelo-dlamini",
    occupation: "Football Player",
    salary: 80000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/kabelo-dlamini-forward-home-headshot-2024-25-kit-brandon-barnard-photography-L1040620.png",
    description: "Affectionately known as 'Shuffle,' Kabelo Dlamini earns a reported R80,000, reflecting his role as a creative spark within the Orlando Pirates squad. Having caught the eye while at Bloemfontein Celtic, his salary represents the club securing a player hoped to contribute significantly to the team's attacking flair and trophy ambitions. While not among the highest earners, his compensation is solid for a player valued for his technical ability and capacity to unlock defences. Dlamini provides valuable depth and creativity in the final third for the Buccaneers' setup.",
    age: 28,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Karim Kimvuidi",
    slug: "karim-kimvuidi",
    occupation: "Football Player",
    salary: 150000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/karim-kimvuidi-midfielder-home-headshot-2024-25-kit-brandon-barnard-photography-L1040653-op.webp",
    description: "Hailing from the DRC, Karim Kimvuidi's arrival came with considerable buzz, reflected in his reported R150,000 salary. This places him in a solid earning bracket, indicative of Pirates securing 'hot property' after his strong showings for Maritzburg United. The club acted swiftly to bring the midfielder to Soweto, and his compensation signifies the value placed on his potential and demonstrated skill. It's an investment in a young, dynamic international talent expected to stamp his mark further and play a key role in the Buccaneers' quest for honours.",
    age: 23,
    country: "DR Congo",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Thalente Mbatha",
    slug: "thalente-mbatha",
    occupation: "Football Player",
    salary: 120000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/thalente-mbatha-midfielder-home-headshot-2024-25-kit-brandon-barnard-photography-L1040808.png",
    description: "The stylish midfielder Thalente Mbatha described his 2024 move to Orlando Pirates as a 'dream come true,' accompanied by a reported salary of R120,000. This places him comfortably in the mid-tier earning range, reflecting the club's investment in his polished skills honed at Highlands Park and SuperSport United. Hailing from KwaMashu, Mbatha's compensation signifies Pirates securing a player with potential and top-flight experience to bolster their midfield stocks. His earnings match the expectation that he will continue developing and contribute significantly to the team's engine room creativity and control.",
    age: 25,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Selaelo Rasebotja",
    slug: "selaelo-rasebotja",
    occupation: "Football Player",
    salary: 60000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/08/selaelo-rasebotja-midfielder-home-headshot-2024-25-kit-brandon-barnard-photography-L1040823.png",
    description: "Joining Orlando Pirates in 2024 from SuperSport United, midfielder Selaelo Rasebotja commands a reported salary of R60,000. This figure places him in the developmental bracket of the squad's wage structure. As a young player making a switch between major clubs, his earnings reflect an investment in his potential future contributions rather than established stardom. The Mokopane-born player aims to contribute to league and CAF Champions League success, and his current salary represents the starting point for a player looking to grow and establish himself at the Soweto Giants.",
    age: 23,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Relebohile Mofokeng",
    slug: "relebohile-mofokeng",
    occupation: "Football Player",
    salary: 90000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/relebohile-mofokeng-forward-home-headshot-2024-25-kit-brandon-barnard-photography-L1040612.png",
    description: "Teen sensation Relebohile Mofokeng's rapid ascent is mirrored in his reported R90,000 salary – a significant sum for a player so young. Making his first-team debut shortly after impressing in the Diski Challenge highlights his phenomenal talent. This wage, while not topping the charts, is substantial for a developing player and underlines how highly Pirates rates the Sharpeville-born forward. It represents a major investment in his potential, acknowledging his immediate impact and marking him as a key future asset expected to shine on domestic and continental stages for years.",
    age: 20,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Tshegofatso Mabasa",
    slug: "tshegofatso-mabasa",
    occupation: "Football Player",
    salary: 120000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/tshegofatso-mabasa-forward-home-headshot-2024-25-kit-brandon-barnard-photography-L1040831.png",
    description: "Striker Tshegofatso Mabasa's journey with Pirates includes loan spells, but his return saw him command a respectable R120,000 salary. This figure acknowledges his natural goal-scoring instincts, evident since his Bloemfontein Celtic days. For Pirates, bringing him back and assigning this wage reflects renewed faith in his ability to find the net consistently. Supporting the club as a youngster, Mabasa's earnings represent the value placed on a proven finisher within the squad, tasked with delivering goals and spearheading the attack, justifying his place among the well-compensated players.",
    age: 28,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Mohau Nkota",
    slug: "mohau-nkota",
    occupation: "Football Player",
    salary: 70000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/09/mohau-nkota-forward-home-headshot-2024-25-kit-brandon-barnard-photography-L1040357.png",
    description: "Mohau Nkota, earning a reported R70,000, is another example of Orlando Pirates investing in youth potential emerging from their structures. His journey from Kimberly culminated in eye-catching Diski Challenge performances that earned him a first-team spot. His current salary reflects his status as a promising young player transitioning to senior football. Living by 'If you believe, you will achieve,' Nkota's earnings represent the club providing a platform and initial reward for his talent, with the expectation of growth as he gains experience and contributes towards collecting silverware.",
    age: 20,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Boitumelo Radiopane",
    slug: "boitumelo-radiopane",
    occupation: "Football Player",
    salary: 50000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/09/boitumelo-radiopane-forward-home-headshot-2024-25-kit-brandon-barnard-photography-L1040821.png",
    description: "Striker Boitumelo Radiopane's reported R50,000 salary aligns with his status as a highly-regarded youth product stepping into the senior setup. Despite his accolades at the DStv Diski Challenge level – including a Golden Boot and Player of the Season award – his first-team earnings reflect the need to translate that potential into consistent senior performance. His wage is typical for a young player promoted based on promise, offering him the opportunity to prove his worth and earn higher honours (and likely salary increases) through future contributions to the first team's success.",
    age: 23,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Monnapule Saleng",
    slug: "monnapule-saleng",
    occupation: "Football Player",
    salary: 265000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/08/monnapule-saleng-headshot-opfc.png",
    description: "Monnapule Saleng sits comfortably near the apex of the Pirates' pay scale with a reported R265,000 salary. This significant earning reflects his explosive impact and journey. After impressing in the lower tier and joining Pirates, a successful loan spell at Swallows proved his top-flight readiness. His subsequent performances, marked by skill reminiscent of his idol Arjen Robben, have made him a key attacking threat. His high wage is a clear indicator of his status as one of the team's most valuable players, rewarded for his game-changing abilities and crucial contributions.",
    age: 27,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Zakhele Lepasa",
    slug: "zakhele-lepasa",
    occupation: "Football Player",
    salary: 150000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/zakhele-lepasa-forward-home-headshot-2024-25-kit-brandon-barnard-photography-L1040633.png",
    description: "Zakhele Lepasa, a product of the Buccaneers' own development system, earns a solid R150,000. This respectable salary acknowledges his journey through the ranks, including proving his goal-scoring prowess during loan spells – notably finishing as Nedbank Cup top scorer with TS Galaxy. Having established himself as a regular Bafana Bafana international, Lepasa's compensation reflects his recognized ability to find the net and his value as a homegrown talent who successfully made the leap to the first team, contributing significantly to the club's attacking options over the years.",
    age: 28,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Evidence Makgopa",
    slug: "evidence-makgopa",
    occupation: "Football Player",
    salary: 200000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/evidence-makgopa-defender-home-headshot-2024-25-kit-brandon-barnard-photography-L1040402.png",
    description: "Striker Evidence Makgopa commands a significant salary, reported at R200,000, placing him among the higher earners at Orlando Pirates. This substantial wage reflects the club's investment in securing a player who had already earned Bafana Bafana caps and shown immense promise after converting from a defender. His goal-scoring exploits for Baroka and the national team justified the move. Makgopa's earnings underscore his status as a key attacking asset, with Pirates banking on his talent, potential, and international experience to deliver goals and lead the line effectively for the Soweto giants.",
    age: 24,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Paseka Mako",
    slug: "paseka-mako",
    occupation: "Football Player",
    salary: 80000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/paseka-mako-defender-home-headshot-2024-25-kit-brandon-barnard-photography-L1040650.png",
    description: "Versatile defender Paseka Mako earns a reported R80,000, a mid-range salary reflecting his role as a reliable squad member since joining in 2018. His journey saw him pass through Mamelodi Sundowns' academy and gain experience at Cape Town All Stars and Chippa United before arriving at Pirates. Mako's earnings represent the value placed on his consistency, adaptability (often playing left-back or wing-back), and experience in the PSL. He provides dependable depth and tactical flexibility for the team without commanding the wages of the absolute top earners on the squad list.",
    age: 30,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Sipho Chaine",
    slug: "sipho-chaine",
    occupation: "Football Player",
    salary: 75000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/sipho-chaine-goalkeeper-home-headshot-2024-25-kit-brandon-barnard-photography-L1040806-1.png",
    description: "Goalkeeper Sipho Chaine was brought into the squad earning a reported R75,000. This salary reflects his role in bolstering the goalkeeping department with valuable Premiership experience gained at clubs like Bloemfontein Celtic, Royal AM, and Chippa United. While not positioned at the top end of the pay scale, his earnings signify the club securing necessary depth and competition between the sticks. Chaine provides experienced cover and challenges for the starting spot, representing a practical investment to ensure the team is well-covered in a crucial position on the field.",
    age: 29,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Melusi Buthelezi",
    slug: "melusi-buthelezi",
    occupation: "Football Player",
    salary: 50000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/07/melusi-buthelezi-goalkeeper-home-headshot-2024-25-kit-brandon-barnard-photography-L1040805.png",
    description: "Melusi Buthelezi joined Orlando Pirates with a burgeoning reputation, reflected in a reported salary of R50,000. Despite this placing him lower on the overall wage scale, it signifies Pirates potentially securing excellent value. Buthelezi's sharp career rise included becoming first-choice at TS Galaxy and earning a Bafana Bafana call-up. His signing bolsters the goalkeeping ranks significantly, adding stiff competition. His modest salary might reflect a strategic acquisition, securing a talented, capped goalkeeper entering his prime without a massive initial financial outlay by the club’s management team.",
    age: 27,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Siyabonga Dladla",
    slug: "siyabonga-dladla",
    occupation: "Football Player",
    salary: 30000,
    currency: "ZAR",
    imageUrl: "https://www.orlandopiratesfc.com/storage/2024/08/siyabonga-dladla-goalkeeper-home-headshot-2024-25-kit-brandon-barnard-photography-L1040817.png",
    description: "As a young goalkeeper recently promoted from the youth structures ahead of the 2024/25 season, Siyabonga Dladla sits at the entry level of the first-team pay scale with a reported R30,000. This salary is typical for a player making the transition from development football to the senior professional environment. It represents the opportunity given by the Soweto Giants to showcase his talent and grow. His earnings reflect his current status based purely on potential, providing a starting point from which he can aim to build his career and increase his value.",
    age: 24,
    country: "South Africa",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-06"
  },
  {
    id: uuidv4(),
    name: "Mike Henry",
    slug: "mike-henry",
    occupation: "CEO",
    salary: 21567610,
    currency: "ZAR",
    imageUrl: "https://www.bhp.com/-/media/project/bhp1ip/bhp1ip-en/image-5.png?h=352&iar=0&w=352&hash=2B3BCBA0A548B1D86ECE6B294DAD289F",
    description: "At 58 years old, Canadian executive Mike Henry serves as the Chief Executive Officer of the global resources giant, BHP Billiton. Leading one of the world's foremost mining and metals companies comes with significant financial reward, reflected in his substantial monthly salary of R 21,567,610. This figure underscores his position at the helm of a major international corporation with extensive operations and places him at the very top of the earnings list for CEOs associated with South Africa's corporate sphere, highlighting the scale of his responsibilities.",
    age: 58,
    country: "Canada",
    company: "BHP Billiton",
    industry: "Mining",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Fani Titi",
    slug: "fani-titi",
    occupation: "CEO",
    salary: 13890741,
    currency: "ZAR",
    imageUrl: "https://www.investec.com/content/dam/dotcom/structuredContent/contacts/Fani_Titi.jpeg",
    description: "Fani Titi, a 58-year-old South African business leader, holds the crucial role of Chief Executive Officer at the international specialist bank and asset manager, Investec. Guiding the strategic direction of this prominent financial institution, Mr. Titi commands a significant monthly compensation package amounting to R 13,890,741. This substantial remuneration reflects his extensive experience and the demanding nature of leading a complex, dual-listed company operating across diverse global markets, positioning him as one of South Africa's highest-paid executives in the financial sector.",
    age: 58,
    country: "South Africa",
    company: "Investec",
    industry: "Financial Services",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Alberto Calderon",
    slug: "alberto-calderon",
    occupation: "CEO",
    salary: 11061102,
    currency: "ZAR",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs8o9ZhNVZ9n7773-C7X-CllREFYQwODAUQg&s",
    description: "Alberto Calderon, aged 63 and originally from Colombia, leads the prominent global gold mining company, AngloGold Ashanti, as its Chief Executive Officer. Steering this major player in the international mining industry involves navigating complex operational and market challenges. His leadership role is compensated with a considerable monthly salary of R 11,061,102. This level of earnings highlights the significant responsibilities associated with managing a large-scale, multinational mining enterprise and his senior standing within the global resources sector based in South Africa.",
    age: 63,
    country: "Colombia",
    company: "AngloGold Ashanti",
    industry: "Mining",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Roy Bagattini",
    slug: "roy-bagattini",
    occupation: "CEO",
    salary: 10205667,
    currency: "ZAR",
    imageUrl: "https://cdn.asp.events/CLIENT_AIS_4ECF9403_5056_B731_4C2E7E25E0DDB2FB/sites/WRC-2023/media/libraries/speakers/roy.png/fit-in/500x500/filters:no_upscale()",
    description: "South African executive Roy Bagattini, at 61 years old, is the Chief Executive Officer of the well-known retailer, Woolworths Holdings Limited. Tasked with leading one of the country's most iconic retail brands, which also has significant operations in Australia, his role demands strategic vision and operational expertise. Mr. Bagattini receives a substantial monthly salary of R 10,205,667. This figure reflects the complexity of managing a large retail group with diverse offerings and a wide geographical footprint, placing him among the top earners in the South African retail industry.",
    age: 61,
    country: "South Africa",
    company: "Woolworths",
    industry: "Retail",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Gary Nagle",
    slug: "gary-nagle",
    occupation: "CEO",
    salary: 9001543,
    currency: "ZAR",
    imageUrl: "https://lh3.googleusercontent.com/xy0Yh22QBQJJ8kBZAyjJK7TVlKf7j8r1Qlq3sNL8Qi-aJSciafBxQgSNHjBo6YUWzFcCCSbJ8kjW3eW9y7oHVcZmhNi2RWf6=s1500-pp",
    description: "Gary Nagle, a 50-year-old South African, serves as the Chief Executive Officer of the multinational commodity trading and mining giant, Glencore Xstrata. Leading such a globally significant player in the resources sector involves immense responsibility and strategic decision-making across diverse commodities and regions. His executive position comes with a notable monthly salary of R 9,001,543. This compensation underlines the scale and complexity of Glencore's operations and Mr. Nagle's critical role in steering one of the world's largest natural resource companies.",
    age: 50,
    country: "South Africa",
    company: "Glencore Xstrata",
    industry: "Mining & Commodities",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Bob van Dijk",
    slug: "bob-van-dijk",
    occupation: "CEO",
    salary: 8984849,
    currency: "ZAR",
    imageUrl: "https://lh3.googleusercontent.com/CKbElWs41tk5SvwfGJukbeSVNL6s_B1KBTEWSQU7bmgj8ObyCIv8s1rCi_tEDX6Agc4Zzy4pnFBwKtO836AYXIBYnbB6-fQUr32f7R_9RBLD=s1500-pp",
    description: "Dutch executive Bob van Dijk, aged 52, leads the global consumer internet group and one of the world's largest technology investors, Naspers, as its Chief Executive Officer. His role involves overseeing a vast portfolio of international internet and technology investments, requiring a keen understanding of global digital trends. For his leadership, Mr. van Dijk earns a significant monthly salary of R 8,984,849. This remuneration reflects the global scale of Naspers' operations and the high stakes involved in navigating the rapidly evolving international technology.",
    age: 52,
    country: "Dutch",
    company: "Naspers",
    industry: "Technology & Media",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Duncan Wanblad",
    slug: "duncan-wanblad",
    occupation: "CEO",
    salary: 7148810,
    currency: "ZAR",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3Xrl7j-dA3SJO4aauXMhGomsosd3dsbsFNw&s",
    description: "At 57, South African Duncan Wanblad holds the position of Chief Executive Officer at the globally diversified mining company, Anglo American plc. Leading this major international mining house requires overseeing operations across multiple continents and commodities, from diamonds to platinum group metals and copper. His extensive responsibilities are reflected in his monthly salary of R 7,148,810. This significant compensation package underscores his critical leadership role within one of the world's largest and most influential mining corporations with deep roots in South Africa.",
    age: 57,
    country: "South Africa",
    company: "Anglo American plc",
    industry: "Mining",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Sim Tshabalala",
    slug: "sim-tshabalala",
    occupation: "CEO",
    salary: 6942000,
    currency: "ZAR",
    imageUrl: "https://www.standardbank.com/static_file/SBG/Assets/Img/Standard%20Bank%20Group/Leadership/2024/GLC/Q3/Sim%20Tshabalala/Sim_not-compressed_Portrait_sq_300x300.jpg",
    description: "Sim Tshabalala, a 57-year-old South African banking executive, serves as the Group Chief Executive Officer of Absa Group Limited. He leads one of Africa's largest diversified financial services groups, overseeing banking operations across numerous countries on the continent. This demanding leadership role comes with a monthly salary reported at R 6,942,000. This substantial figure reflects his responsibility for the strategic direction and performance of a major pan-African banking institution, positioning him as a top earner in the continent's financial services industry.",
    age: 57,
    country: "South Africa",
    company: "Absa Group",
    industry: "Banking",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Lungisa Fihla",
    slug: "lungisa-fihla",
    occupation: "CEO",
    salary: 5825250,
    currency: "ZAR",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWKh1xPfi8lvbN6Haafyyf0Y_n5yEBlZ-kjA&s",
    description: "Leading Africa's largest food retailer, Shoprite Holdings, is 53-year-old South African CEO Pieter Engelbrecht. His role involves managing a vast network of supermarkets and retail outlets across the continent, navigating complex logistics and diverse consumer markets. For steering this retail giant, Mr. Engelbrecht receives a significant monthly salary of R 6,939,333. This compensation highlights the immense scale of Shoprite's operations and the critical leadership required to maintain its market dominance in the highly competitive African retail sector.",
    age: 58,
    country: "South Africa",
    company: "Standard Bank Group",
    industry: "Banking",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Andrew King",
    slug: "andrew-king",
    occupation: "CEO",
    salary: 5486866,
    currency: "ZAR",
    imageUrl: "https://www.mondigroup.com/cdn-cgi/image/f=auto,w=640,sharpen=1/AdaptiveImages/celum/379591/Andrew_King.png?stamp=96fdbab5a66a152eecfdc24af7ce9a17b196c5a1",
    description: "Lungisa Fihla, a 58-year-old South African executive, serves as a Chief Executive Officer within the Standard Bank Group, Africa's largest bank by assets. While the specific division isn't listed, his CEO title within this major financial institution indicates significant leadership responsibilities. Mr. Fihla earns a substantial monthly salary of R 5,825,250. This figure reflects the seniority of his position and the importance of his contribution to the strategic operations and success of one of the continent's most prominent and influential banking organisations.",
    age: 56,
    country: "South Africa",
    company: "Mondi Group",
    industry: "Packaging & Paper",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Pieter Engelbrecht",
    slug: "pieter-engelbrecht",
    occupation: "CEO",
    salary: 6939333,
    currency: "ZAR",
    imageUrl: "https://media.licdn.com/dms/image/v2/C4D03AQEt5xSgAW0wjA/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1516971473807?e=2147483647&v=beta&t=qdpeXKCiWjJwG5kOmoYT1sr8-we2iKZCqmn4WVvQox8",
    description: "Andrew King, a 56-year-old South African executive, leads the international packaging and paper company, Mondi Group, as its Chief Executive Officer. His role involves overseeing a global business focused on sustainable packaging and paper solutions, operating across numerous countries. For this leadership position, Mr. King receives a monthly salary of R 5,486,866. This compensation reflects the global nature of Mondi's operations and the strategic importance of navigating the evolving landscape of sustainable materials and international manufacturing within the industry.",
    age: 53,
    country: "South Africa",
    company: "Shoprite",
    industry: "Retail",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Iain Williamson",
    slug: "iain-williamson",
    occupation: "CEO",
    salary: 2693333,
    currency: "ZAR",
    imageUrl: "https://www.africaglobalfunds.com/static/media/uploads/2020/07/07/ian-williamson.jpg",
    description: "At 52 years old, South African Iain Williamson holds the position of Chief Executive Officer at the prominent pan-African financial services group, Old Mutual Limited. He is responsible for guiding the strategy and operations of this well-established company, which offers a wide range of insurance, investment, and banking services across Africa. Mr. Williamson earns a monthly salary of R 2,693,333. This remuneration reflects his leadership role within a major player in the African financial services sector, overseeing diverse business units and navigating complex market dynamics.",
    age: 52,
    country: "South Africa",
    company: "Old Mutual",
    industry: "Insurance & Finance",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Chris du Toit",
    slug: "chris-du-toit",
    occupation: "CEO",
    salary: 2690000,
    currency: "ZAR",
    imageUrl: "https://media.licdn.com/dms/image/v2/C4E03AQFsCFQtgy8KZQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1579155432265?e=2147483647&v=beta&t=vNJsQEmn2WsgMMT56sh7hTcw7KFyBwVBLEumi_OfRAk",
    description: "Chris du Toit, a 55-year-old South African, serves as the Chief Executive Officer of the leading South African hospitality, gaming, and entertainment group, Tsogo Sun. His role involves managing a diverse portfolio of hotels and entertainment complexes, requiring expertise in the leisure and hospitality industry. Mr. du Toit's leadership position is compensated with a monthly salary of R 2,690,000. This figure reflects the responsibilities associated with steering a major player in South Africa's tourism and entertainment sector through various market conditions and operational challenges.",
    age: 55,
    country: "South Africa",
    company: "Tsogo Sun",
    industry: "Hospitality & Gaming",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Adrian Gore",
    slug: "adrian-gore",
    occupation: "CEO",
    salary: 2359167,
    currency: "ZAR",
    imageUrl: "https://www.internationalinsurance.org/sites/default/files/gbb-uploads/Adrian%20450x450-ads48i.jpg",
    description: "Adrian Gore, the 60-year-old South African founder and Chief Executive Officer of Discovery Limited, leads the globally recognized financial services organization known for its innovative shared-value insurance model. His entrepreneurial vision built the company, which now operates in insurance, wellness, and banking sectors internationally. Mr. Gore receives a monthly salary of R 2,359,167. While substantial, this figure reflects his ongoing leadership in driving innovation and managing the continued expansion and complexity of the Discovery group across different markets and product lines.",
    age: 60,
    country: "South Africa",
    company: "Discovery",
    industry: "Insurance & Healthcare",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Laurence Rapp",
    slug: "laurence-rapp",
    occupation: "CEO",
    salary: 1933333,
    currency: "ZAR",
    imageUrl: "https://lh3.googleusercontent.com/pN6uUrkphrvXfZ3qQATMFiscW5HdxUynDSmQbyAsZU759-yNFCsU19-kLZykUljs16H2pn8599MUqYQpnDtc9H9O6TOVCMfowXsEAkQpIRVlKQ=s1500-pp",
    description: "Laurence Rapp, a 54-year-old South African executive, leads Vukile Property Fund as its Chief Executive Officer. His role involves managing a specialist retail real estate investment trust (REIT) with significant property assets in South Africa and Spain. Steering this property investment company requires expertise in real estate markets and asset management. Mr. Rapp earns a monthly salary of R 1,933,333. This compensation reflects his leadership responsibilities in managing a substantial property portfolio and driving strategy within the competitive real estate investment sector.",
    age: 54,
    country: "South Africa",
    company: "Vukile Property",
    industry: "Real Estate Investment",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Roy Douglas",
    slug: "roy-douglas",
    occupation: "CEO",
    salary: 1863333,
    currency: "ZAR",
    imageUrl: "https://lh3.googleusercontent.com/Bm2UfRii30ATP6xfNmUt_quE98crEaeIKSFpZPyHq-8eWYm3S4aES1pnkQDfKfKt11JhmufbMwkNTmiek7OIfi96Uniscp4=s1500-pp",
    description: "At 61, South African Roy Douglas serves as the Chief Executive Officer of ADvTECH Group, a leading private education and recruitment company in South Africa. His responsibilities include overseeing a diverse portfolio of schools, tertiary institutions, and recruitment agencies, navigating the dynamics of both the education and employment sectors. Mr. Douglas receives a monthly salary of R 1,863,333. This figure reflects his leadership role in managing one of the largest private education and staffing providers on the continent, requiring strategic oversight across multiple brands and services.",
    age: 61,
    country: "South Africa",
    company: "ADvTECH",
    industry: "Education",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Nasreddine Nabi",
    slug: "nasreddine-nabi",
    occupation: "Football Coach",
    salary: 783000,
    currency: "ZAR",
    imageUrl: "https://farpost.co.za/wp-content/uploads/2025/04/Nasreddine-during-the-Nedbank-Cup-media-event-780x470.jpg",
    description: "Nasreddine Nabi has quickly become one of the most prominent figures in South African football. Managing Kaizer Chiefs, he earns an impressive R783,000 a month. His strategic approach and leadership have made him the highest-paid coach in the league. Nabi’s vast experience, which includes stints with top clubs in Tunisia, has elevated Kaizer Chiefs to new heights, capturing the attention of millions of fans. His salary reflects his status as a key figure in the PSL.",
    age: 48,
    country: "Tunisia",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "Manqoba Mngqithi",
    slug: "manqoba-mngqithi",
    occupation: "Football Coach",
    salary: 700000,
    currency: "ZAR",
    imageUrl: "https://cdn.24.co.za/files/Cms/General/d/12772/0ea088646f2c4469815a05d4c80d4555.jpg",
    description: "As the senior coach of Mamelodi Sundowns, Manqoba Mngqithi’s work speaks volumes. He commands over R700,000 a month, a salary that reflects his invaluable contribution to the team’s success. Mngqithi’s calm demeanor and tactical brilliance have made Sundowns a powerhouse in African football. Under his leadership, the team has consistently dominated both locally and internationally. Mngqithi’s ability to build a strong, cohesive team continues to earn him well-deserved recognition and respect in the footballing world.",
    age: 53,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "Rhulani Mokwena",
    slug: "rhulani-mokwena",
    occupation: "Football Coach",
    salary: 700000,
    currency: "ZAR",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/38/Go_Ahead_Eagles_-_Mamelodi_Sundowns_FC_-_53066347575_%28Rhulani_Mokwena%29.jpg",
    description: "Rhulani Mokwena’s managerial career reached new heights with his move to Wydad AC, but it was his previous work at Mamelodi Sundowns that solidified his reputation. Earning over R700,000 a month, Mokwena’s journey has been one of growth and innovation. His time at Sundowns saw him revolutionize the team’s attacking play, making them one of the most feared sides in Africa. His tactical acumen and leadership qualities have made him one of the most sought-after coaches in the region.",
    age: 37,
    country: "South Africa",
    company: "Wydad AC",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "Steve Komphela",
    slug: "steve-komphela",
    occupation: "Football Coach",
    salary: 700000,
    currency: "ZAR",
    imageUrl: "https://img.a.transfermarkt.technology/portrait/big/11044-1688283736.jpg?lm=1",
    description: "Steve Komphela has had a remarkable career in South African football, and his role at Mamelodi Sundowns now sees him earning over R700,000 per month. Known for his disciplined approach, Komphela has brought stability to Sundowns’ technical team. His knowledge of the game and his ability to nurture players has helped the club maintain its dominance. Komphela’s experience both as a former player and coach makes him a vital asset to the team, earning him one of the highest salaries in the league.",
    age: 56,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "José Riveiro",
    slug: "josé-riveiro",
    occupation: "Football Coach",
    salary: 700000,
    currency: "ZAR",
    imageUrl: "https://img.a.transfermarkt.technology/portrait/big/44214-1730832896.png?lm=1",
    description: "José Riveiro’s tenure at Orlando Pirates has proven successful, and his salary of around R700,000 a month is a testament to his hard work and expertise. The Spanish manager brought with him a fresh approach to South African football, focusing on tactical discipline and high-intensity play. His leadership has seen the Pirates make significant strides in both local and continental competitions. Riveiro’s calm and composed nature on the touchline, paired with his winning mentality, has solidified his position as one of the league’s highest earners.",
    age: 46,
    country: "Spanish",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "Eric Tinkler",
    slug: "eric-tinkler",
    occupation: "Football Coach",
    salary: 700000,
    currency: "ZAR",
    imageUrl: "https://img.a.transfermarkt.technology/portrait/big/20913-1635831200.jpg?lm=1",
    description: "Eric Tinkler, known for his fiery passion and tactical insight, leads Cape Town City with great success. Earning around R700,000 per month, Tinkler’s career has seen him rise through the ranks, proving his mettle at clubs across South Africa. His time at Cape Town City has been marked by innovative play and impressive results. Tinkler’s ability to extract the best from his players and create a competitive team in a tough league has earned him both respect and a lucrative salary.",
    age: 54,
    country: "South Africa",
    company: "Cape Town City",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "John Maduka",
    slug: "john-maduka",
    occupation: "Football Coach",
    salary: 600000,
    currency: "ZAR",
    imageUrl: "https://times.mw/wp-content/uploads/2023/09/john-maduka.jpg",
    description: "John Maduka has made waves in South African football, particularly with Royal AM. With a salary exceeding R600,000 per month, Maduka’s influence on the club has been undeniable. Known for his strong leadership and tactical discipline, Maduka has transformed Royal AM into a team to be reckoned with in the league. His experience as a former player has allowed him to connect with his squad on a deeper level, motivating them to perform at their peak. Maduka’s reputation continues to grow, alongside his salary.",
    age: 47,
    country: "Malawi",
    company: "Royal AM",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "Brandon Truter",
    slug: "brandon-truter",
    occupation: "Football Coach",
    salary: 600000,
    currency: "ZAR",
    imageUrl: "https://sundayworld.co.za/wp-content/uploads/2022/09/P22-Brandon-Truter--e1684604492868.jpg",
    description: "Brandon Truter’s leadership of Sekhukhune United has been marked by steady progress, and his monthly salary of over R600,000 reflects his growing stature in South African football. Truter’s ability to adapt to the demands of the PSL has helped Sekhukhune establish themselves as a competitive side. His tactical approach, combined with a focus on team cohesion, has enabled him to overcome challenges and secure important victories. Truter’s rise in the coaching ranks is a testament to his hard work and dedication.",
    age: 51,
    country: "South Africa",
    company: "Sekhukhune United",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "Steve Barker",
    slug: "steve-barker",
    occupation: "Football Coach",
    salary: 400000,
    currency: "ZAR",
    imageUrl: "https://lh3.googleusercontent.com/IcxB3ac5rhoQvZaEV8L2qWcXC2H-8i5Uj452Buo2J49qNOlzn17BlH1GqgB0XGL9V0ZHfBiFUJNDu5iQ0lp6kPCLrgh8x5htO-kpDSzx2tus=s750",
    description: "Steve Barker may not be one of the highest-paid coaches in the league, but his salary of R400,000 per month is still a reflection of his significant contributions to Stellenbosch FC. Barker’s emphasis on building a solid defensive team and his tactical discipline has made Stellenbosch a competitive force. Under his leadership, the club has continued to perform well, consistently securing important points. Barker’s calm, methodical approach to coaching has helped shape the club into a respected side in the PSL.",
    age: 47,
    country: "South Africa",
    company: "Stellenbosch FC",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  }
];

// Format salary for display
export const formatSalary = (salary: number, currency: string) => {
  return salary.toLocaleString('en-US', {
    style: 'currency',
    currency: currency,
    maximumFractionDigits: 1,
    minimumFractionDigits: 0,
    notation: 'compact',
    compactDisplay: 'short',
  });
};

// Find a celebrity by slug
export const findCelebrityBySlug = (slug: string): Celebrity | undefined => {
  return celebrities.find(celebrity => celebrity.slug === slug);
};

// Get similar celebrities (same industry or similar salary)
export const getSimilarCelebrities = (celebrity: Celebrity, limit: number = 5): Celebrity[] => {
  return celebrities
    .filter(c => 
      c.id !== celebrity.id && 
      (c.industry === celebrity.industry || 
       Math.abs(c.salary - celebrity.salary) / celebrity.salary < 0.3)
    )
    .sort((a, b) => {
      // Sort by industry match first, then by salary similarity
      if (a.industry === celebrity.industry && b.industry !== celebrity.industry) {
        return -1;
      }
      if (a.industry !== celebrity.industry && b.industry === celebrity.industry) {
        return 1;
      }
      return Math.abs(a.salary - celebrity.salary) - Math.abs(b.salary - celebrity.salary);
    })
    .slice(0, limit);
};
