import { faker } from '@faker-js/faker';

export interface Celebrity {
  id: string;
  name: string;
  slug: string;
  occupation: string;
  salary: number;
  currency: string;
  imageUrl: string;
  description: string;
  age: number;
  country: string;
  company: string;
  industry: string;
  source: string;
  lastUpdated: string;
}

// Function to generate a slug from a name
const generateSlug = (name: string): string => {
  return name.toLowerCase().replace(/ /g, '-').replace(/[^\w-]+/g, '');
};

// Utility function to format salary
export const formatSalary = (salary: number, currency: string): string => {
  return new Intl.NumberFormat('en-ZA', {
    style: 'currency',
    currency: currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(salary);
};

// Generate mock celebrity data
export const celebrities: Celebrity[] = [
  {
    id: "1",
    name: "Patrice Motsepe",
    slug: generateSlug("Patrice Motsepe"),
    occupation: "Businessman",
    salary: 27800000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Patrice_Motsepe_WEF_2013.jpg/440px-Patrice_Motsepe_WEF_2013.jpg",
    description: "Patrice Motsepe is a South African mining magnate. In 2016, he founded African Rainbow Capital, a private equity firm focused on investing in Africa.",
    age: 62,
    country: "South Africa",
    company: "African Rainbow Minerals",
    industry: "Mining",
    source: "Forbes",
    lastUpdated: "2024-01-26"
  },
  {
    id: "2",
    name: "Koos Bekker",
    slug: generateSlug("Koos Bekker"),
    occupation: "Businessman",
    salary: 26000000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Jacobus_Bekker.jpg/440px-Jacobus_Bekker.jpg",
    description: "Jacobus Petrus 'Koos' Bekker is a South African billionaire businessman. He is chairman of Naspers and Prosus.",
    age: 71,
    country: "South Africa",
    company: "Naspers",
    industry: "Media",
    source: "Forbes",
    lastUpdated: "2024-01-26"
  },
  {
    id: "3",
    name: "Elon Musk",
    slug: generateSlug("Elon Musk"),
    occupation: "Entrepreneur",
    salary: 25000000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Elon_Musk_Royal_Society_%28crop2%29.jpg/440px-Elon_Musk_Royal_Society_%28crop2%29.jpg",
    description: "Elon Reeve Musk is a business magnate and investor. He is the founder, chairman, CEO, and CTO of SpaceX; angel investor, CEO, product architect and former chairman of Tesla, Inc.",
    age: 52,
    country: "South Africa",
    company: "Tesla",
    industry: "Technology",
    source: "Forbes",
    lastUpdated: "2024-01-26"
  },
  {
    id: "4",
    name: "Johann Rupert",
    slug: generateSlug("Johann Rupert"),
    occupation: "Businessman",
    salary: 7780000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Johann_Rupert_2015.jpg/440px-Johann_Rupert_2015.jpg",
    description: "Johann Peter Rupert is a South African-born businessman, who is the eldest son of business tycoon Anton Rupert and his wife Huberte. He is the chairman of Swiss luxury goods firm Richemont and South Africa-based company Remgro.",
    age: 73,
    country: "South Africa",
    company: "Richemont",
    industry: "Luxury Goods",
    source: "Forbes",
    lastUpdated: "2024-01-26"
  },
  {
    id: "5",
    name: "Siya Kolisi",
    slug: generateSlug("Siya Kolisi"),
    occupation: "Rugby Player",
    salary: 858000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Siya_Kolisi_2023.jpg/440px-Siya_Kolisi_2023.jpg",
    description: "Siyamthanda Kolisi is a South African professional rugby union player who currently plays for Racing 92 in the French Top 14, and captains the South Africa national rugby union team.",
    age: 32,
    country: "South Africa",
    company: "Racing 92",
    industry: "Rugby",
    source: "SARugbyMag",
    lastUpdated: "2024-01-26"
  },
  {
    id: "6",
    name: "Trevor Noah",
    slug: generateSlug("Trevor Noah"),
    occupation: "Comedian",
    salary: 400000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Trevor_Noah_by_Christopher_Michel.jpg/440px-Trevor_Noah_by_Christopher_Michel.jpg",
    description: "Trevor Noah is a South African comedian, television host, and political commentator. He was the host of The Daily Show from 2015 to 2022.",
    age: 39,
    country: "South Africa",
    company: "The Daily Show",
    industry: "Comedy",
    source: "Forbes",
    lastUpdated: "2024-01-26"
  },
  {
    id: "7",
    name: "Bonang Matheba",
    slug: generateSlug("Bonang Matheba"),
    occupation: "Television Presenter",
    salary: 720000,
    currency: "ZAR",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Bonang_Matheba_at_the_2016_MTV_Africa_Music_Awards.jpg/440px-Bonang_Matheba_at_the_2016_MTV_Africa_Music_Awards.jpg",
    description: "Bonang Dorothy Matheba, is a South African television presenter, radio personality, businesswoman, producer, model and philanthropist.",
    age: 36,
    country: "South Africa",
    company: "Bonang Matheba Entertainment",
    industry: "Entertainment",
    source: "ZAlebs",
    lastUpdated: "2024-01-26"
  },
  {
    id: "8",
    name: "Black Coffee",
    slug: generateSlug("Black Coffee"),
    occupation: "DJ",
    salary: 300000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Black_Coffee_at_Ultra_Music_Festival_2018.jpg/440px-Black_Coffee_at_Ultra_Music_Festival_2018.jpg",
    description: "Nkosinathi Innocent Maphumulo, most popularly known as Black Coffee, is a South African DJ, record producer and songwriter.",
    age: 47,
    country: "South Africa",
    company: "Soulistic Music",
    industry: "Music",
    source: "Forbes",
    lastUpdated: "2024-01-26"
  },
  {
    id: "9",
    name: "AKA",
    slug: generateSlug("AKA"),
    occupation: "Rapper",
    salary: 250000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/AKA_performing_in_2018.jpg/440px-AKA_performing_in_2018.jpg",
    description: "Kiernan Jarryd Forbes , known professionally as AKA, was a South African rapper, songwriter, record producer and entrepreneur.",
    age: 35,
    country: "South Africa",
    company: "Beam Group",
    industry: "Music",
    source: "SAHipHopMag",
    lastUpdated: "2024-01-26"
  },
  {
    id: "10",
    name: "Cassper Nyovest",
    slug: generateSlug("Cassper Nyovest"),
    occupation: "Rapper",
    salary: 200000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Cassper_Nyovest_at_the_2018_MTV_Europe_Music_Awards.jpg/440px-Cassper_Nyovest_at_the_2018_MTV_Europe_Music_Awards.jpg",
    description: "Refiloe Maele Phoolo , professionally known as Cassper Nyovest, is a South African rapper, songwriter, entrepreneur and record producer.",
    age: 33,
    country: "South Africa",
    company: "Family Tree Records",
    industry: "Music",
    source: "Forbes",
    lastUpdated: "2024-01-26"
  },
  {
    id: "11",
    name: "Pitso Mosimane",
    slug: generateSlug("Pitso Mosimane"),
    occupation: "Football Coach",
    salary: 240000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Pitso_Mosimane_Al_Ahli_Saudi_FC.jpg/440px-Pitso_Mosimane_Al_Ahli_Saudi_FC.jpg",
    description: "Pitso Mosimane is a South African football manager and former player who is currently managing Saudi Arabian club Al-Ahli.",
    age: 59,
    country: "South Africa",
    company: "Al-Ahli",
    industry: "Football",
    source: "KickOff",
    lastUpdated: "2024-01-26"
  },
  {
    id: "12",
    name: "Hugo Broos",
    slug: generateSlug("Hugo Broos"),
    occupation: "Football Coach",
    salary: 60000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Hugo_Broos_2017.jpg/440px-Hugo_Broos_2017.jpg",
    description: "Hugo Broos is a Belgian football manager and former player who is currently the manager of the South Africa national football team.",
    age: 71,
    country: "South Africa",
    company: "South Africa National Football Team",
    industry: "Football",
    source: "IOL",
    lastUpdated: "2024-01-26"
  },
  {
    id: "13",
    name: "Molefi Ntseki",
    slug: generateSlug("Molefi Ntseki"),
    occupation: "Football Coach",
    salary: 30000,
    currency: "USD",
    imageUrl: "https://cdn.24.co.za/files/Cms/General/d/8814/4999c093449d44a9999ca34a4b0b94a1.jpg",
    description: "Molefi Ntseki is a South African football manager.",
    age: 54,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "The Citizen",
    lastUpdated: "2024-01-26"
  },
  {
    id: "14",
    name: "Rassie Erasmus",
    slug: generateSlug("Rassie Erasmus"),
    occupation: "Rugby Coach",
    salary: 410000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Rassie_Erasmus_2019.jpg/440px-Rassie_Erasmus_2019.jpg",
    description: "Johan 'Rassie' Erasmus is a South African rugby union coach and former player who is currently the head coach of the South Africa national rugby team.",
    age: 51,
    country: "South Africa",
    company: "South Africa National Rugby Team",
    industry: "Rugby",
    source: "SuperSport",
    lastUpdated: "2024-01-26"
  },
  {
    id: "15",
    name: "Jacques Nienaber",
    slug: generateSlug("Jacques Nienaber"),
    occupation: "Rugby Coach",
    salary: 300000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Jacques_Nienaber_2019.jpg/440px-Jacques_Nienaber_2019.jpg",
    description: "Jacques Nienaber is a South African rugby union coach who is currently the head coach of Leinster Rugby.",
    age: 51,
    country: "South Africa",
    company: "Leinster Rugby",
    industry: "Rugby",
    source: "SA Rugby",
    lastUpdated: "2024-01-26"
  },
  {
    id: "16",
    name: "Mark Boucher",
    slug: generateSlug("Mark Boucher"),
    occupation: "Cricket Coach",
    salary: 250000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Mark_Boucher.jpg/440px-Mark_Boucher.jpg",
    description: "Mark Boucher is a South African cricket coach and former cricketer who is currently the head coach of the Mumbai Indians.",
    age: 47,
    country: "South Africa",
    company: "Mumbai Indians",
    industry: "Cricket",
    source: "ESPNcricinfo",
    lastUpdated: "2024-01-26"
  },
  {
    id: "17",
    name: "Temba Bavuma",
    slug: generateSlug("Temba Bavuma"),
    occupation: "Cricket Player",
    salary: 49000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Temba_Bavuma_during_the_Test_match_between_Australia_and_South_Africa_at_the_Gabba_in_Brisbane_on_17_December_2022_%2801%29.jpg/440px-Temba_Bavuma_during_the_Test_match_between_Australia_and_South_Africa_at_the_Gabba_in_Brisbane_on_17_December_2022_%2801%29.jpg",
    description: "Temba Bavuma is a South African international cricketer who currently captains the South Africa national cricket team in Test and One Day International (ODI)cricket.",
    age: 33,
    country: "South Africa",
    company: "South Africa National Cricket Team",
    industry: "Cricket",
    source: "Cricket South Africa",
    lastUpdated: "2024-01-26"
  },
  {
    id: "18",
    name: "Dean Elgar",
    slug: generateSlug("Dean Elgar"),
    occupation: "Cricket Player",
    salary: 45000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Dean_Elgar_2017.jpg/440px-Dean_Elgar_2017.jpg",
    description: "Dean Elgar is a South African international cricketer and former captain of the South Africa national cricket team in Test cricket.",
    age: 36,
    country: "South Africa",
    company: "South Africa National Cricket Team",
    industry: "Cricket",
    source: "ESPNcricinfo",
    lastUpdated: "2024-01-26"
  },
  {
    id: "19",
    name: "Faf du Plessis",
    slug: generateSlug("Faf du Plessis"),
    occupation: "Cricket Player",
    salary: 40000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Faf_du_Plessis_2018.jpg/440px-Faf_du_Plessis_2018.jpg",
    description: "François 'Faf' du Plessis is a South African international cricketer and former captain of the South Africa national cricket team in all three forms of the game.",
    age: 39,
    country: "South Africa",
    company: "Chennai Super Kings",
    industry: "Cricket",
    source: "ESPNcricinfo",
    lastUpdated: "2024-01-26"
  },
  {
    id: "20",
    name: "Quinton de Kock",
    slug: generateSlug("Quinton de Kock"),
    occupation: "Cricket Player",
    salary: 35000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Quinton_de_Kock_2017.jpg/440px-Quinton_de_Kock_2017.jpg",
    description: "Quinton de Kock is a South African international cricketer and former captain of the South Africa national cricket team in all three forms of the game.",
    age: 31,
    country: "South Africa",
    company: "Lucknow Super Giants",
    industry: "Cricket",
    source: "ESPNcricinfo",
    lastUpdated: "2024-01-26"
  },
  {
    id: "21",
    name: "Percy Tau",
    slug: generateSlug("Percy Tau"),
    occupation: "Football Player",
    salary: 200000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Percy_Tau_2018.jpg/440px-Percy_Tau_2018.jpg",
    description: "Percy Muzi Tau is a South African professional footballer who plays as a forward for Egyptian Premier League club Al Ahly and the South Africa national team.",
    age: 29,
    country: "South Africa",
    company: "Al Ahly",
    industry: "Football",
    source: "KickOff",
    lastUpdated: "2024-01-26"
  },
  {
    id: "22",
    name: "Themba Zwane",
    slug: generateSlug("Themba Zwane"),
    occupation: "Football Player",
    salary: 35000,
    currency: "USD",
    imageUrl: "https://cdn.24.co.za/files/Cms/General/d/12445/4e983599550a4ef3858ca0c6c8dd9c6a.jpg",
    description: "Themba Zwane is a South African professional footballer who plays as a midfielder for Mamelodi Sundowns and the South Africa national team.",
    age: 34,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Soccer Laduma",
    lastUpdated: "2024-01-26"
  },
  {
    id: "23",
    name: "Keagan Dolly",
    slug: generateSlug("Keagan Dolly"),
    occupation: "Football Player",
    salary: 30000,
    currency: "USD",
    imageUrl: "https://i0.wp.com/www.snl24.com/files/Cms/General/d/8041/a989939549a44480b94d484a30446494.jpg",
    description: "Keagan Dolly is a South African professional footballer who plays as a midfielder for Kaizer Chiefs and the South Africa national team.",
    age: 31,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "KickOff",
    lastUpdated: "2024-01-26"
  },
  {
    id: "24",
    name: "Itumeleng Khune",
    slug: generateSlug("Itumeleng Khune"),
    occupation: "Football Player",
    salary: 25000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Itumeleng_Khune_2015.jpg/440px-Itumeleng_Khune_2015.jpg",
    description: "Itumeleng Isaac Khune is a South African professional footballer who plays as a goalkeeper for Kaizer Chiefs and the South Africa national team.",
    age: 36,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "Soccer Laduma",
    lastUpdated: "2024-01-26"
  },
    {
    id: "25",
    name: "Ronwen Williams",
    slug: generateSlug("Ronwen Williams"),
    occupation: "Football Player",
    salary: 40000,
    currency: "USD",
    imageUrl: "https://cdn.24.co.za/files/Cms/General/d/4844/9899c89e469a44a9a84a3a633347ca94.jpeg",
    description: "Ronwen Williams is a South African professional footballer who plays as a goalkeeper for Mamelodi Sundowns and the South Africa national team.",
    age: 32,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Soccer Laduma",
    lastUpdated: "2024-01-26"
  },
  {
    id: "26",
    name: "Andile Jali",
    slug: generateSlug("Andile Jali"),
    occupation: "Football Player",
    salary: 20000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Andile_Jali_2015.jpg/440px-Andile_Jali_2015.jpg",
    description: "Andile Ernest Jali is a South African professional footballer who plays as a midfielder for Moroka Swallows.",
    age: 33,
    country: "South Africa",
    company: "Moroka Swallows",
    industry: "Football",
    source: "KickOff",
    lastUpdated: "2024-01-26"
  },
    {
    id: "27",
    name: "Aubrey Modiba",
    slug: generateSlug("Aubrey Modiba"),
    occupation: "Football Player",
    salary: 28000,
    currency: "USD",
    imageUrl: "https://africanfootball.com/wp-content/uploads/2023/09/Aubrey-Modiba-Mamelodi-Sundowns.jpg",
    description: "Aubrey Modiba is a South African professional footballer who plays as a left back for Mamelodi Sundowns.",
    age: 28,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Soccer Laduma",
    lastUpdated: "2024-01-26"
  },
    {
    id: "28",
    name: "Khuliso Mudau",
    slug: generateSlug("Khuliso Mudau"),
    occupation: "Football Player",
    salary: 22000,
    currency: "USD",
    imageUrl: "https://i.ytimg.com/vi/3ooK0qG_0Fo/maxresdefault.jpg",
    description: "Khuliso Mudau is a South African professional footballer who plays as a right back for Mamelodi Sundowns.",
    age: 28,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "KickOff",
    lastUpdated: "2024-01-26"
  },
    {
    id: "29",
    name: "Teboho Mokoena",
    slug: generateSlug("Teboho Mokoena"),
    occupation: "Football Player",
    salary: 25000,
    currency: "USD",
    imageUrl: "https://cdn.24.co.za/files/Cms/General/d/8365/4a9f9394698644a991143459132b799a.jpg",
    description: "Teboho Mokoena is a South African professional footballer who plays as a midfielder for Mamelodi Sundowns.",
    age: 27,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Soccer Laduma",
    lastUpdated: "2024-01-26"
  },
      {
    id: "30",
    name: "Peter Shalulile",
    slug: generateSlug("Peter Shalulile"),
    occupation: "Football Player",
    salary: 38000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Peter_Shalulile.jpg/440px-Peter_Shalulile.jpg",
    description: "Peter Shalulile is a Namibian professional footballer who plays as a forward for Mamelodi Sundowns.",
    age: 30,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "KickOff",
    lastUpdated: "2024-01-26"
  },
        {
    id: "31",
    name: "Gaston Sirino",
    slug: generateSlug("Gaston Sirino"),
    occupation: "Football Player",
    salary: 32000,
    currency: "USD",
    imageUrl: "https://www.thesouthafrican.com/wp-content/uploads/2023/01/Gaston-Sirino-Mamelodi-Sundowns-PSL.jpg",
    description: "Gaston Sirino is a Uruguayan professional footballer who plays as an attacking midfielder for Mamelodi Sundowns.",
    age: 32,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Soccer Laduma",
    lastUpdated: "2024-01-26"
  },
          {
    id: "32",
    name: "Kennedy Mweene",
    slug: generateSlug("Kennedy Mweene"),
    occupation: "Football Player",
    salary: 17000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Kennedy_Mweene_2013.jpg/440px-Kennedy_Mweene_2013.jpg",
    description: "Kennedy Mweene is a Zambian professional footballer who plays as a goalkeeper for Mamelodi Sundowns.",
    age: 38,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "KickOff",
    lastUpdated: "2024-01-26"
  },
            {
    id: "33",
    name: "Denis Onyango",
    slug: generateSlug("Denis Onyango"),
    occupation: "Football Player",
    salary: 33000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Denis_Onyango_2017.jpg/440px-Denis_Onyango_2017.jpg",
    description: "Denis Onyango is a Ugandan professional footballer who plays as a goalkeeper for Mamelodi Sundowns.",
    age: 38,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Soccer Laduma",
    lastUpdated: "2024-01-26"
  },
              {
    id: "34",
    name: "Grant Kekana",
    slug: generateSlug("Grant Kekana"),
    occupation: "Football Player",
    salary: 19000,
    currency: "USD",
    imageUrl: "https://www.snl24.com/files/Cms/General/d/4844/9c9989a96c9a41a9a84a3a633347ca94.jpeg",
    description: "Grant Kekana is a South African professional footballer who plays as a defender for Mamelodi Sundowns.",
    age: 31,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "KickOff",
    lastUpdated: "2024-01-26"
  },
                {
    id: "35",
    name: "Rushine De Reuck",
    slug: generateSlug("Rushine De Reuck"),
    occupation: "Football Player",
    salary: 21000,
    currency: "USD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Rushine_De_Reuck_2021.jpg/440px-Rushine_De_Reuck_2021.jpg",
    description: "Rushine De Reuck is a South African professional footballer who plays as a defender for Mamelodi Sundowns.",
    age: 27,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "Soccer Laduma",
    lastUpdated: "2024-01-26"
  },
  {
    id: "36",
    name: "Brandon Petersen",
    slug: generateSlug("Brandon Petersen"),
    occupation: "Football Player",
    salary: 18000,
    currency: "USD",
    imageUrl: "https://www.thesouthafrican.com/wp-content/uploads/2023/07/Kaizer-Chiefs-Brandon-Petersen.jpg",
    description: "Brandon Petersen is a South African professional footballer who plays as a goalkeeper for Kaizer Chiefs.",
    age: 29,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "KickOff",
    lastUpdated: "2024-01-26"
  },
  {
    id: "37",
    name: "Yusuf Maart",
    slug: generateSlug("Yusuf Maart"),
    occupation: "Football Player",
    salary: 23000,
    currency: "USD",
    imageUrl: "https://www.thesouthafrican.com/wp-content/uploads/2022/07/Yusuf-Maart-Kaizer-Chiefs-PSL.jpg",
    description: "Yusuf Maart is a South African professional footballer who plays as a midfielder for Kaizer Chiefs.",
    age: 28,
    country: "South Africa",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "Soccer Laduma",
    lastUpdated: "2024-01-26"
  },
  {
    id: "38",
    name: "Sifiso Hlanti",
    slug: generateSlug("Sifiso Hlanti"),
    occupation: "Football Player",
    salary: 16000,
    currency: "USD",
    imageUrl: "https://www.kickoff.com/news/wp-content/uploads/2021/07/Sifiso-Hlanti-Kaizer-Chiefs.jpg",
    description: "Sifiso Hlanti is a South African professional footballer who plays as a defender for Kaizer Chiefs.",
