// EPL Players data

export interface EPLPlayer {
  id: number;
  name: string;
  slug: string;
  team: string;
  position: string;
  nationality: string;
  age: number;
  weeklySalary: number; // in British Pounds
  annualSalary: number; // calculated from weekly
  imageUrl?: string;
  description: string;
  contractUntil: string;
  transferValue?: number; // in millions of pounds
  jerseyNumber?: number;
  height?: string;
  accolades?: string[];
  previousClubs?: string[];
  internationalCaps?: number;
  marketValue?: number; // in millions of pounds
  source: string;
  lastUpdated: string;
}

// Helper function to calculate annual salary
const calculateAnnualSalary = (weeklySalary: number): number => {
  return weeklySalary * 52;
};

// EPL Players data
export const eplPlayers: EPLPlayer[] = [
{
id: 3,
name: "Mohamed Salah",
slug: "mohamed-salah",
team: "Liverpool",
position: "Right Wing",
nationality: "Egypt",
age: 32,
weeklySalary: 350000,
annualSalary: calculateAnnualSalary(350000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p118748.png",
description: "The Egyptian King continues to reign supreme at Anfield. His blistering pace, intricate dribbling, and lethal finishing make him a constant threat to any defense. Even after years at the top, his hunger for goals and silverware remains insatiable. You can always count on Salah to produce moments of magic, whether it's a stunning solo goal or a perfectly weighted assist. His dedication and professionalism set a high standard for the entire squad, and his influence extends far beyond the goals he scores. He's a true icon of the modern game.",
contractUntil: "June 2025",
transferValue: 77.5,
jerseyNumber: 11,
height: "1.75m",
accolades: ["PL Golden Boot", "PFA POTY"],
previousClubs: ["Basel", "Chelsea", "Roma"],
internationalCaps: 98,
marketValue: 65,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 20,
name: "Virgil van Dijk",
slug: "virgil-van-dijk",
team: "Liverpool",
position: "Centre Back",
nationality: "Netherlands",
age: 33,
weeklySalary: 220000,
annualSalary: calculateAnnualSalary(220000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p97032.png",
description: "A colossus at the heart of Liverpool's defense, Virgil van Dijk exudes composure and authority. His aerial prowess is unmatched, and his ability to read the game allows him to make crucial interceptions and tackles. Beyond his defensive capabilities, Van Dijk's calmness on the ball and accurate passing often initiate attacks from the back. His presence alone brings a sense of security to the team, and his leadership qualities make him an invaluable asset both on and off the pitch. He's the bedrock upon which Liverpool's success is built.",
contractUntil: "June 2025",
transferValue: 47.5,
jerseyNumber: 4,
height: "1.95m",
accolades: ["UEFA Defender of the Year", "PL Winner"],
previousClubs: ["Groningen", "Celtic", "Southampton"],
internationalCaps: 65,
marketValue: 40,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 33,
name: "Trent Alexander-Arnold",
slug: "trent-alexander-arnold",
team: "Liverpool",
position: "Right Back",
nationality: "England",
age: 26,
weeklySalary: 180000,
annualSalary: calculateAnnualSalary(180000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p169187.png",
description: "Trent Alexander-Arnold's creativity from the right flank is simply breathtaking. His pinpoint crosses and defence-splitting passes have become a hallmark of Liverpool's attacking play. While his offensive contributions are undeniable, his defensive game has also matured significantly over the years. His passion for the club is evident in every tackle and every surging run down the wing. He's a local lad living the dream, and his connection with the Anfield faithful is palpable.",
contractUntil: "June 2025",
transferValue: 90,
jerseyNumber: 66,
height: "1.75m",
accolades: ["PL Winner", "UCL Winner"],
previousClubs: ["Liverpool Youth"],
internationalCaps: 23,
marketValue: 75,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 39,
name: "Andy Robertson",
slug: "andrew-robertson",
team: "Liverpool",
position: "Left Back",
nationality: "Scotland",
age: 30,
weeklySalary: 160000,
annualSalary: calculateAnnualSalary(160000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p122798.png",
description: "The tireless engine of Liverpool's left flank, Andy Robertson embodies grit and determination. His relentless running, coupled with his accurate crosses and tenacious tackling, make him a nightmare for opposing wingers. He’s a leader on the pitch, always pushing his teammates and setting the tempo with his boundless energy. Robertson's journey to the top is a testament to his hard work and perseverance, and his unwavering commitment to the Liverpool cause makes him a firm fan favorite. He's the heart and soul of the team.",
contractUntil: "June 2026",
transferValue: 42.5,
jerseyNumber: 26,
height: "1.78m",
accolades: ["PL Winner", "UCL Winner"],
previousClubs: ["Dundee United", "Hull City"],
internationalCaps: 67,
marketValue: 35,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 48,
name: "Alexis Mac Allister",
slug: "alexis-mac-allister",
team: "Liverpool",
position: "Central Midfielder",
nationality: "Argentina",
age: 26,
weeklySalary: 150000,
annualSalary: calculateAnnualSalary(150000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p243016.png",
description: "Bringing a touch of elegance and steel to Liverpool's midfield, Alexis Mac Allister has quickly become an integral part of the team. His intelligent positioning, incisive passing, and ability to win back possession make him a vital cog in the machine. He possesses a calmness on the ball that belies his combative nature, and his eye for a killer pass can unlock even the most stubborn defenses. Mac Allister's versatility allows him to operate in various midfield roles, providing Jurgen Klopp with valuable tactical flexibility. He's a player who makes those around him better.",
contractUntil: "June 2028",
transferValue: 67.5,
jerseyNumber: 10,
height: "1.76m",
accolades: ["World Cup Winner 2022"],
previousClubs: ["Argentinos Juniors", "Brighton"],
internationalCaps: 25,
marketValue: 55,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 51,
name: "Alisson",
slug: "alisson",
team: "Liverpool",
position: "Goalkeeper",
nationality: "Brazil",
age: 32,
weeklySalary: 150000,
annualSalary: calculateAnnualSalary(150000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p116535.png",
description: "Arguably the best goalkeeper in the world, Alisson Becker brings a sense of security and brilliance to Liverpool's goal. His exceptional shot-stopping ability is matched by his composure with the ball at his feet and his incredible distribution. He has a knack for making crucial saves at pivotal moments, often turning draws into wins. Beyond his technical skills, Alisson's commanding presence and communication with his defenders are invaluable. He's a game-changer in his own right, capable of single-handedly keeping Liverpool in matches.",
contractUntil: "June 2027",
transferValue: 62.5,
jerseyNumber: 1,
height: "1.93m",
accolades: ["Copa América", "PL Winner"],
previousClubs: ["Internacional", "Roma"],
internationalCaps: 63,
marketValue: 55,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 53,
name: "Federico Chiesa",
slug: "federico-chiesa",
team: "Liverpool",
position: "Right Wing",
nationality: "Italy",
age: 27,
weeklySalary: 150000,
annualSalary: calculateAnnualSalary(150000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p223541.png",
description: "The arrival of Federico Chiesa at Anfield has injected a thrilling dose of dynamism into Liverpool's attack. His explosive pace, coupled with his intricate dribbling and clinical finishing, makes him a constant menace to opposition defenses. Whether cutting in from the wing or leading the line, Chiesa's direct running and eye for goal have quickly made him a firm favourite among the Anfield faithful. His ability to create something out of nothing and his relentless work rate both on and off the ball make him an invaluable asset to Jurgen Klopp's side as they continue to chase silverware. He’s a player who can truly ignite an attack.",
contractUntil: "June 2028",
transferValue: 67.5,
jerseyNumber: 14,
height: "1.75m",
accolades: ["Euro 2020 Winner"],
previousClubs: ["Fiorentina", "Juventus"],
internationalCaps: 40,
marketValue: 55,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 58,
name: "Ryan Gravenberch",
slug: "ryan-gravenberch",
team: "Liverpool",
position: "Defensive Midfielder",
nationality: "Netherlands",
age: 22,
weeklySalary: 150000,
annualSalary: calculateAnnualSalary(150000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p441266.png",
description: "A dynamic and technically gifted midfielder, Ryan Gravenberch possesses the potential to become a key player for Liverpool. His imposing physique, coupled with his excellent dribbling skills and passing range, allows him to dictate play from the center of the park. Still developing and adapting to the Premier League's intensity, Gravenberch has shown glimpses of his immense talent. As he continues to integrate into the team, his ability to break lines and create opportunities will be crucial for Liverpool's midfield.",
contractUntil: "June 2028",
transferValue: 47.5,
jerseyNumber: 38,
height: "1.90m",
accolades: ["Eredivisie Winner"],
previousClubs: ["Ajax", "Bayern Munich"],
internationalCaps: 11,
marketValue: 35,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 62,
name: "Darwin Núñez",
slug: "darwin-núñez",
team: "Liverpool",
position: "Centre FoRight Wingard",
nationality: "Uruguay",
age: 25,
weeklySalary: 140000,
annualSalary: calculateAnnualSalary(140000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p447203.png",
description: "An unpredictable force of nature, Darwin Núñez brings raw energy and a relentless work rate to Liverpool's attack. His pace and physicality make him a handful for any defender, and his willingness to run in behind creates numerous opportunities. While his finishing can sometimes be erratic, his desire to score and his commitment to the team are undeniable. Núñez's enthusiasm is infectious, and his ability to stretch defenses provides a different dimension to Liverpool's forward line. He's a player who keeps opposition defenders on their toes.",
contractUntil: "June 2028",
transferValue: 72.5,
jerseyNumber: 9,
height: "1.87m",
accolades: ["Primeira Liga Player of the Year"],
previousClubs: ["Almería", "Benfica"],
internationalCaps: 23,
marketValue: 60,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 66,
name: "Diogo Jota",
slug: "diogo-jota",
team: "Liverpool",
position: "Centre FoRight Wingard",
nationality: "Portugal",
age: 28,
weeklySalary: 140000,
annualSalary: calculateAnnualSalary(140000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p194634.png",
description: "A versatile and clinical forward, Diogo Jota has proven to be a valuable asset for Liverpool. His ability to play across the front line and his knack for scoring crucial goals make him a manager's dream. Jota's intelligent movement and sharp finishing inside the box are particularly impressive. Despite facing injury setbacks, his impact on the team is undeniable whenever he's on the pitch. He possesses a predatory instinct in front of goal and a knack for being in the right place at the right time.",
contractUntil: "June 2027",
transferValue: 52.5,
jerseyNumber: 20,
height: "1.78m",
accolades: ["Nations League Winner"],
previousClubs: ["Paços Ferreira", "Wolves"],
internationalCaps: 40,
marketValue: 45,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 88,
name: "Dominik Szoboszlai",
slug: "dominik-szoboszlai",
team: "Liverpool",
position: "Central Midfielder",
nationality: "Hungary",
age: 24,
weeklySalary: 120000,
annualSalary: calculateAnnualSalary(120000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p424876.png",
description: "Bursting onto the scene with an infectious energy, Dominik Szoboszlai has injected dynamism into Liverpool's midfield. His powerful running, coupled with his eye for a spectacular goal and a perfectly weighted through ball, makes him a constant threat. You can see his passion for the game in every stride, and his willingness to work hard both in attack and defense is a real asset. He's a player who can lift the team with a moment of brilliance or a tireless display of effort, quickly becoming a fan favourite at Anfield.",
contractUntil: "June 2028",
transferValue: 67.5,
jerseyNumber: 8,
height: "1.87m",
accolades: ["Austrian Bundesliga POTY"],
previousClubs: ["Liefering", "Salzburg", "Leipzig"],
internationalCaps: 40,
marketValue: 55,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 92,
name: "Cody Gakpo",
slug: "cody-gakpo",
team: "Liverpool",
position: "Left Wing",
nationality: "Netherlands",
age: 25,
weeklySalary: 120000,
annualSalary: calculateAnnualSalary(120000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p243298.png",
description: "Bringing versatility and a cool head to Liverpool's forward line, Cody Gakpo has proven to be a smart addition to the squad. Whether deployed centrally or out wide, his intelligent movement and composed finishing make him a reliable option in attack. He possesses excellent link-up play and an ability to find space in tight areas, often creating opportunities for himself and his teammates. Gakpo's tactical flexibility offers Jurgen Klopp valuable options, and his calm demeanor in front of goal is a welcome trait in high-pressure situations.",
contractUntil: "June 2028",
transferValue: 52.5,
jerseyNumber: 18,
height: "1.93m",
accolades: ["Eredivisie Top Scorer"],
previousClubs: ["PSV Eindhoven"],
internationalCaps: 25,
marketValue: 45,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 151,
name: "Joe Gomez",
slug: "joe-gomez",
team: "Liverpool",
position: "Centre Back",
nationality: "England",
age: 27,
weeklySalary: 85000,
annualSalary: calculateAnnualSalary(85000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p171287.png",
description: "A dependable and versatile defender, Joe Gomez has consistently proven his worth to Liverpool. Capable of playing both centrally and at full-back, his athleticism and strong tackling make him a reliable option across the backline. While injuries have sometimes hampered his progress, his resilience and determination to fight for his place are admirable. Gomez's ability to read the game and his composure under pressure provide a sense of stability to the defense, and his experience is invaluable to the team's overall solidity.",
contractUntil: "June 2027",
transferValue: 37.5,
jerseyNumber: 2,
height: "1.88m",
accolades: ["PL & UCL Winner"],
previousClubs: ["Charlton Athletic"],
internationalCaps: 11,
marketValue: 30,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 184,
name: "Konstantinos Tsimikas",
slug: "konstantinos-tsimikas",
team: "Liverpool",
position: "Left Back",
nationality: "Greece",
age: 28,
weeklySalary: 75000,
annualSalary: calculateAnnualSalary(75000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p214285.png",
description: "The ever-enthusiastic understudy to Andy Robertson, Konstantinos Tsimikas brings a vibrant energy and attacking intent to Liverpool's left flank. Known for his infectious smile and wholehearted commitment, Kostas provides quality cover and competition for the first-choice left-back. His crossing ability is a real weapon, and his willingness to get forward and contribute to attacks makes him a popular figure among the Anfield faithful. Whenever called upon, Tsimikas consistently delivers a performance full of passion and determination.",
contractUntil: "June 2027",
transferValue: 21.5,
jerseyNumber: 21,
height: "1.79m",
accolades: ["Greek Cup Winner"],
previousClubs: ["Olympiacos", "Willem II"],
internationalCaps: 30,
marketValue: 17.5,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 198,
name: "Ibrahima Konaté",
slug: "ibrahima-konaté",
team: "Liverpool",
position: "Centre Back",
nationality: "France",
age: 25,
weeklySalary: 70000,
annualSalary: calculateAnnualSalary(70000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p204716.png",
description: "A commanding presence in the heart of Liverpool's defense, Ibrahima Konaté possesses the physical attributes and technical ability to dominate opposing attackers. His strength, pace, and aerial prowess make him a formidable opponent for any striker. While still developing and refining his game, Konaté's potential is undeniable, and his partnership with Virgil van Dijk has the makings of a long-term defensive cornerstone for Liverpool. His confidence on the ball also allows him to contribute to build-up play from the back.",
contractUntil: "June 2026",
transferValue: 57.5,
jerseyNumber: 5,
height: "1.94m",
accolades: ["UCL Finalist", "UEFA U21 Champion"],
previousClubs: ["Sochaux", "RB Leipzig"],
internationalCaps: 15,
marketValue: 50,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 229,
name: "Luis Díaz",
slug: "luis-díaz",
team: "Liverpool",
position: "Left Wing",
nationality: "Colombia",
age: 28,
weeklySalary: 55000,
annualSalary: calculateAnnualSalary(55000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p244731.png",
description: "With his electrifying pace and mesmerizing dribbling skills, Luis Díaz has become a thrilling addition to Liverpool's attack. His ability to beat defenders with ease and his willingness to take on opponents make him a constant threat down the left wing. Beyond his individual brilliance, Díaz also possesses a strong work ethic and a desire to press and win back possession. His infectious energy and direct running style have quickly made him a fan favourite at Anfield, bringing a spark and unpredictability to the team's forward play.",
contractUntil: "June 2027",
transferValue: 62.5,
jerseyNumber: 7,
height: "1.80m",
accolades: ["Copa América Top Scorer"],
previousClubs: ["Barranquilla", "Junior", "Porto"],
internationalCaps: 45,
marketValue: 55,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 260,
name: "Wataru Endo",
slug: "wataru-endo",
team: "Liverpool",
position: "Defensive Midfielder",
nationality: "Japan",
age: 31,
weeklySalary: 50000,
annualSalary: calculateAnnualSalary(50000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p158983.png",
description: "Arriving with a reputation for his tenacious tackling and positional discipline, Wataru Endo has provided valuable steel and experience to Liverpool's midfield. His ability to break up play and shield the defense has been crucial, particularly in moments when the team needs added protection. Endo's understated but effective performances have made him a reliable option in the holding midfield role, allowing other midfielders more freedom to express themselves further up the pitch. His commitment and tactical awareness have been a welcome addition to the squad.",
contractUntil: "June 2027",
transferValue: 15,
jerseyNumber: 3,
height: "1.78m",
accolades: ["J. League Best XI"],
previousClubs: ["Urawa", "Stuttgart"],
internationalCaps: 60,
marketValue: 12.5,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 317,
name: "Harvey Elliott",
slug: "harvey-elliott",
team: "Liverpool",
position: "Central Midfielder",
nationality: "England",
age: 21,
weeklySalary: 40000,
annualSalary: calculateAnnualSalary(40000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p444884.png",
description: "A bright spark in Liverpool's midfield, Harvey Elliott possesses a maturity and technical ability beyond his years. His creativity, vision, and willingness to take risks in the final third make him a player capable of unlocking defenses. Whether playing centrally or on the right wing, Elliott's intelligence on the ball and his eye for a killer pass are evident. Still developing and learning, he has already shown glimpses of his immense potential and looks set to play a significant role in Liverpool's future.",
contractUntil: "June 2027",
transferValue: 42.5,
jerseyNumber: 19,
height: "1.70m",
accolades: ["UEFA Super Cup", "League Cup"],
previousClubs: ["Fulham"],
internationalCaps: 1,
marketValue: 35,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 384,
name: "Jarell Quansah",
slug: "jarell-quansah",
team: "Liverpool",
position: "Centre Back",
nationality: "England",
age: 22,
weeklySalary: 30000,
annualSalary: calculateAnnualSalary(30000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p441428.png",
description: "Emerging from the academy with impressive composure and maturity, Jarell Quansah has shown he has the potential to become a long-term fixture in Liverpool's defense. His calmness on the ball, coupled with his aerial ability and willingness to learn, have impressed both the coaching staff and the fans. Stepping up when called upon, Quansah has demonstrated a maturity beyond his years, suggesting a bright future ahead for the young center-back at Anfield. His development will be one to watch closely.",
contractUntil: "June 2029",
transferValue: 21.5,
jerseyNumber: 78,
height: "1.90m",
accolades: ["U19 Euro Champion"],
previousClubs: ["Liverpool Youth"],
internationalCaps: 0,
marketValue: 17.5,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 440,
name: "Nathaniel Phillips",
slug: "nathaniel-phillips",
team: "Liverpool",
position: "Centre Back",
nationality: "England",
age: 27,
weeklySalary: 20000,
annualSalary: calculateAnnualSalary(20000),
imageUrl: "https://static.wikia.nocookie.net/liverpoolfc/images/2/27/NPhillips2024.png/revision/latest?cb=20240830094003",
description: "A reliable and honest defender, Nathaniel Phillips has consistently stepped up for Liverpool when needed. Known for his aerial prowess and no-nonsense approach to defending, Phillips provides valuable cover in the center-back position. While opportunities might have been limited at times, his professionalism and commitment to the club have never wavered. Whenever called upon, he gives his all and has proven to be a dependable option for Jurgen Klopp, embodying the team spirit within the Liverpool squad.",
contractUntil: "June 2025",
transferValue: 9,
jerseyNumber: 12,
height: "1.90m",
accolades: ["UCL & PL Squad Member"],
previousClubs: ["Bolton", "Stuttgart (loan)"],
internationalCaps: 0,
marketValue: 7.5,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 465,
name: "Curtis Jones",
slug: "curtis-jones",
team: "Liverpool",
position: "Central Midfielder",
nationality: "England",
age: 24,
weeklySalary: 15000,
annualSalary: calculateAnnualSalary(15000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p206915.png",
description: "A graduate of Liverpool's esteemed academy, Curtis Jones embodies the flair and tenacity that Jurgen Klopp admires. Growing in confidence with each appearance, his ability to glide past opponents and pick out a clever pass makes him a valuable asset in midfield. You can see his understanding of the game developing, and his willingness to contribute defensively adds another dimension to his play. Jones has shown glimpses of becoming a key player for Liverpool in the years to come, bringing both creativity and a local connection to the team.",
contractUntil: "June 2027",
transferValue: 37.5,
jerseyNumber: 17,
height: "1.85m",
accolades: ["U21 Euro Champion"],
previousClubs: ["Liverpool Youth"],
internationalCaps: 1,
marketValue: 30,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 493,
name: "Ben Doak",
slug: "ben-doak",
team: "Liverpool",
position: "Right Wing",
nationality: "Scotland",
age: 19,
weeklySalary: 10000,
annualSalary: calculateAnnualSalary(10000),
imageUrl: "https://static.wikia.nocookie.net/liverpoolfc/images/8/89/Doak.jpeg/revision/latest?cb=20230903014528",
description: "An electrifying winger with bags of potential, Ben Doak has already provided glimpses of his exciting talent. His blistering pace and fearless dribbling make him a nightmare for defenders, and his willingness to take on opponents is refreshing to see. Still raw but brimming with promise, Doak has the potential to become a real attacking threat for Liverpool. His youthful enthusiasm and direct running style offer a different dimension to the forward line, and his development will be closely monitored by fans and coaches alike.",
contractUntil: "June 2025",
transferValue: 17.5,
jerseyNumber: 50,
height: "1.73m",
accolades: ["Scotland U21"],
previousClubs: ["Celtic"],
internationalCaps: 0,
marketValue: 12.5,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 497,
name: "Caoimhín Kelleher",
slug: "caoimhín-kelleher",
team: "Liverpool",
position: "Goalkeeper",
nationality: "Ireland",
age: 26,
weeklySalary: 10000,
annualSalary: calculateAnnualSalary(10000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p200720.png",
description: "A calm and reliable presence between the posts, Caoimhín Kelleher has proven to be an excellent understudy to Alisson Becker. His shot-stopping ability and composure under pressure have been evident whenever he's been called upon. For a young goalkeeper, he exudes a remarkable level of confidence, and his distribution is also improving steadily. Kelleher represents a secure future for Liverpool in the goalkeeping department and has shown he can be trusted in crucial moments.",
contractUntil: "June 2026",
transferValue: 21.5,
jerseyNumber: 62,
height: "1.88m",
accolades: ["League Cup Winner"],
previousClubs: ["Ringmahon Rangers"],
internationalCaps: 10,
marketValue: 17.5,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 505,
name: "Conor Bradley",
slug: "conor-bradley",
team: "Liverpool",
position: "Right Back",
nationality: "Northern Ireland",
age: 21,
weeklySalary: 10000,
annualSalary: calculateAnnualSalary(10000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p492777.png",
description: "A tenacious and energetic full-back, Conor Bradley has impressed with his maturity and work rate whenever given an opportunity. His willingness to get forward and contribute to attacks, coupled with his solid defensive capabilities, makes him a promising prospect. Bradley's enthusiasm is infectious, and his desire to learn and improve is clear to see. He represents a bright future for Liverpool in the full-back positions and has shown he's ready to compete for a place in the squad.",
contractUntil: "June 2027",
transferValue: 15,
jerseyNumber: 84,
height: "1.81m",
accolades: ["EFL Cup Finalist"],
previousClubs: ["Bolton (loan)"],
internationalCaps: 15,
marketValue: 12.5,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 514,
name: "Tyler Morton",
slug: "tyler-morton",
team: "Liverpool",
position: "Defensive Midfielder",
nationality: "England",
age: 22,
weeklySalary: 8000,
annualSalary: calculateAnnualSalary(8000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p440148.png",
description: "A composed and intelligent midfielder, Tyler Morton has demonstrated a maturity beyond his years in his appearances for the first team. His ability to dictate play from deep and his willingness to put in a shift defensively make him a valuable asset. Still developing physically, Morton's understanding of the game and his passing range are already impressive. He has the potential to become a key figure in Liverpool's midfield in the future, offering both control and creativity.",
contractUntil: "June 2025",
transferValue: 9,
jerseyNumber: 80,
height: "1.78m",
accolades: ["Championship Runner-Up"],
previousClubs: ["Blackburn (loan)"],
internationalCaps: 0,
marketValue: 7.5,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 533,
name: "Rhys Williams",
slug: "rhys-williams",
team: "Liverpool",
position: "Centre Back",
nationality: "England",
age: 24,
weeklySalary: 7500,
annualSalary: calculateAnnualSalary(7500),
imageUrl: "https://lfc.pl/images/players/67.png?m=1631600886",
description: "A determined and committed defender, Rhys Williams has shown his willingness to step up and perform when called upon. His aerial ability and no-nonsense defending have been valuable assets for Liverpool, particularly during periods of injury crisis. While still learning and developing, Williams's dedication and desire to improve are evident. He represents the kind of player who will always give his all for the club, providing important depth to the defensive ranks.",
contractUntil: "June 2026",
transferValue: 6.5,
jerseyNumber: 46,
height: "1.95m",
accolades: ["PL & UCL Squad Member"],
previousClubs: ["Kidderminster", "Swansea"],
internationalCaps: 0,
marketValue: 5,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 538,
name: "Vitezslav Jaros",
slug: "vitezslav-jaros",
team: "Liverpool",
position: "Goalkeeper",
nationality: "Czech Republic",
age: 23,
weeklySalary: 7000,
annualSalary: calculateAnnualSalary(7000),
imageUrl: "https://resources.premierleague.com/premierleague/photos/players/110x140/p432987.png",
description: "Another promising goalkeeper within the Liverpool ranks, Vitezslav Jaros has been gaining valuable experience and developing his skills. Known for his agility and shot-stopping abilities, Jaros represents a potential future option between the posts for the club. While still progressing through the ranks, his dedication and hard work are evident, and his development within the academy system is a positive sign for Liverpool's goalkeeping future.",
contractUntil: "June 2025",
transferValue: 2.5,
jerseyNumber: 56,
height: "1.90m",
accolades: ["U21 Euro Champion (Czech Rep. squad)"],
previousClubs: ["St Patrick's", "Stockport"],
internationalCaps: 0,
marketValue: 2,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 556,
name: "Calvin Ramsay",
slug: "calvin-ramsay",
team: "Liverpool",
position: "Right Back",
nationality: "Scotland",
age: 21,
weeklySalary: 5000,
annualSalary: calculateAnnualSalary(5000),
imageUrl: "https://i.guim.co.uk/img/media/ad06500577e9ae9f49fc4084ad55100bd9aa7ab7/171_110_1580_948/master/1580.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=6d23894776db7eeab432e39fc864ad44",
description: "A talented young full-back with attacking instincts, Calvin Ramsay possesses the potential to become a dynamic presence on the flank for Liverpool. While injuries have unfortunately hampered his progress since joining the club, his natural ability and willingness to get forward are clear to see. As he continues his recovery and development, Ramsay has the potential to provide valuable competition and a different dimension to Liverpool's full-back options.",
contractUntil: "June 2027",
transferValue: 9,
jerseyNumber: 21,
height: "1.77m",
accolades: ["SFWA Young Player of the Year"],
previousClubs: ["Aberdeen"],
internationalCaps: 1,
marketValue: 7.5,
source: "Verified contracts",
lastUpdated: "April 2024"
},
{
id: 590,
name: "Harvey Davies",
slug: "harvey-davies",
team: "Liverpool",
position: "Goalkeeper",
nationality: "England",
age: 21,
weeklySalary: 3000,
annualSalary: calculateAnnualSalary(3000),
imageUrl: "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-09/harvey-davies-headshot-202425-v2.webp?itok=fDe1ZywV",
description: "A young goalkeeper making his way through the Liverpool academy, Harvey Davies is showing promising signs for the future. Developing his technique and gaining experience within the club's youth system, Davies represents another potential option for Liverpool in the goalkeeping department down the line. His continued progress and dedication will be key as he aims to make his mark within the club's ranks.",
contractUntil: "June 2025",
transferValue: 2.5,
jerseyNumber: 0,
height: "1.90m",
accolades: ["FA Youth Cup Finalist"],
previousClubs: ["Liverpool Youth"],
internationalCaps: 0,
marketValue: 2,
source: "Verified contracts",
lastUpdated: "April 2024"
}
];

// Helper functions

// Find a player by slug
export function findPlayerBySlug(slug: string): EPLPlayer | undefined {
  return eplPlayers.find(player => player.slug === slug);
}

// Find a player by ID
export function findPlayerById(id: number): EPLPlayer | undefined {
  return eplPlayers.find(player => player.id === id);
}

// Get all players
export function getAllPlayers(): EPLPlayer[] {
  return eplPlayers;
}

// Format weekly salary
export function formatWeeklySalary(salary: number, currency: string = "£"): string {
  return `${currency}${salary.toLocaleString()}`;
}

// Format annual salary
export function formatAnnualSalary(salary: number, currency: string = "£"): string {
  return `${currency}${salary.toLocaleString()}`;
}

// Get similar players based on position and team
export function getSimilarPlayers(player: EPLPlayer, limit: number = 5): EPLPlayer[] {
  // First look for players on the same team
  const sameTeamPlayers = eplPlayers.filter(p => 
    p.id !== player.id && p.team === player.team
  );
  
  // Then look for players in the same position
  const samePositionPlayers = eplPlayers.filter(p => 
    p.id !== player.id && p.position === player.position && p.team !== player.team
  );
  
  // Combine and limit the results
  const combinedPlayers = [...sameTeamPlayers, ...samePositionPlayers];
  
  // Remove duplicates if any
  const uniquePlayers = Array.from(new Set(combinedPlayers.map(p => p.id)))
    .map(id => combinedPlayers.find(p => p.id === id))
    .filter((p): p is EPLPlayer => p !== undefined);
  
  return uniquePlayers.slice(0, limit);
}
