export interface NetWorthPerson {
  id: string;
  name: string;
  slug: string;
  netWorth: number;
  currency: string;
  source: string;
  lastUpdated: string;
  country: string;
  industry: string;
  occupation: string;
  company?: string;
  imageUrl?: string;
  bio: string;
  categories: string;
}

export interface NetWorthCategory {
  id: string;
  title: string;
  slug: string;
  description: string;
  imageUrl?: string;
}

export const formatNetWorth = (netWorth: number, currency: string): string => {
  return netWorth.toLocaleString('en-US', {
    style: 'currency',
    currency: currency,
    maximumFractionDigits: 1,
    minimumFractionDigits: 0,
    notation: 'compact',
    compactDisplay: 'short',
  });
};

export const netWorthCategories: NetWorthCategory[] = [
  {
    id: "1",
    title: "Richest Global Executives",
    slug: "richest-global-executives",
    description: "Explore the financial standings of the world's most successful executives. This category offers insights into the net worth of CEOs, CFOs, and other top-level managers across various industries.",
    imageUrl: "/images/categories/global-executives.jpg",
  },
  {
    id: "2",
    title: "Top Tech Entrepreneurs",
    slug: "top-tech-entrepreneurs",
    description: "Discover the net worth of leading tech entrepreneurs who have revolutionized the industry. From software to hardware, see who's on top.",
    imageUrl: "/images/categories/tech-entrepreneurs.jpg",
  },
  {
    id: "3",
    title: "Leading Financial Moguls",
    slug: "leading-financial-moguls",
    description: "A look at the wealthiest figures in the financial world, including investors, hedge fund managers, and bankers.",
    imageUrl: "/images/categories/financial-moguls.jpg",
  },
  {
    id: "4",
    title: "Entertainment Industry Titans",
    slug: "entertainment-industry-titans",
    description: "From actors to producers, explore the net worth of the entertainment industry's biggest players.",
    imageUrl: "/images/categories/entertainment-titans.jpg",
  },
  {
    id: "5",
    title: "Sports Stars and Owners",
    slug: "sports-stars-and-owners",
    description: "Athletes, team owners, and sports executives—see who's scoring big in the world of sports.",
    imageUrl: "/images/categories/sports-stars.jpg",
  },
  {
    id: "6",
    title: "Real Estate Tycoons",
    slug: "real-estate-tycoons",
    description: "The wealthiest individuals in real estate, including developers, investors, and property magnates.",
    imageUrl: "/images/categories/real-estate-tycoons.jpg",
  },
  {
    id: "7",
    title: "Fashion and Retail Giants",
    slug: "fashion-and-retail-giants",
    description: "Explore the net worth of the biggest names in fashion and retail, from designers to CEOs.",
    imageUrl: "/images/categories/fashion-giants.jpg",
  },
  {
    id: "8",
    title: "Media and Communications Moguls",
    slug: "media-and-communications-moguls",
    description: "A look at the wealthiest figures in media and communications, including CEOs of major networks and media moguls.",
    imageUrl: "/images/categories/media-moguls.jpg",
  },
  {
    id: "9",
    title: "Energy and Resources Barons",
    slug: "energy-and-resources-barons",
    description: "The wealthiest individuals in the energy and resources sectors, including oil magnates and mining executives.",
    imageUrl: "/images/categories/energy-barons.jpg",
  },
  {
    id: "10",
    title: "Philanthropists and Foundation Heads",
    slug: "philanthropists-and-foundation-heads",
    description: "Explore the net worth of leading philanthropists and heads of major charitable foundations.",
    imageUrl: "/images/categories/philanthropists.jpg",
  },
];

export const findCategoryBySlug = (slug: string): NetWorthCategory | undefined => {
  return netWorthCategories.find(category => category.slug === slug);
};

export const getCategoryIdBySlug = (slug: string): string | undefined => {
  const category = netWorthCategories.find(category => category.slug === slug);
  return category ? category.id : undefined;
};

export const getPeopleByCategory = (categoryId: string): NetWorthPerson[] => {
  return netWorthPeople.filter(person => person.categories === categoryId);
};

export const netWorthPeople: NetWorthPerson[] = [
  {
    id: "1",
    name: "Elon Musk",
    slug: "elon-musk",
    netWorth: 210000000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Technology",
    occupation: "Entrepreneur",
    company: "Tesla, SpaceX",
    imageUrl: "/images/people/elon-musk.jpg",
    bio: "Elon Musk is a South African-born American entrepreneur and businessman who founded SpaceX and co-founded Tesla and PayPal.",
    categories: "2",
  },
  {
    id: "2",
    name: "Jeff Bezos",
    slug: "jeff-bezos",
    netWorth: 190000000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Technology",
    occupation: "Entrepreneur",
    company: "Amazon",
    imageUrl: "/images/people/jeff-bezos.jpg",
    bio: "Jeff Bezos is an American entrepreneur, media proprietor, investor, and computer engineer. He is the founder, executive chairman, and former president and CEO of Amazon.",
    categories: "2",
  },
  {
    id: "3",
    name: "Bernard Arnault",
    slug: "bernard-arnault",
    netWorth: 180000000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "France",
    industry: "Fashion",
    occupation: "Chairman and CEO",
    company: "LVMH",
    imageUrl: "/images/people/bernard-arnault.jpg",
    bio: "Bernard Arnault is a French businessman, investor, and art collector. He is the chairman and CEO of LVMH, the world's largest luxury goods company.",
    categories: "7",
  },
  {
    id: "4",
    name: "Bill Gates",
    slug: "bill-gates",
    netWorth: 130000000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Technology",
    occupation: "Entrepreneur",
    company: "Microsoft",
    imageUrl: "/images/people/bill-gates.jpg",
    bio: "Bill Gates is an American business magnate, software developer, investor, author, and philanthropist. He is a co-founder of Microsoft Corporation.",
    categories: "2",
  },
  {
    id: "5",
    name: "Larry Ellison",
    slug: "larry-ellison",
    netWorth: 120000000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Technology",
    occupation: "Entrepreneur",
    company: "Oracle",
    imageUrl: "/images/people/larry-ellison.jpg",
    bio: "Lawrence Joseph Ellison is an American business magnate, investor, and philanthropist who is a co-founder, executive chairman and chief technology officer of Oracle Corporation.",
    categories: "2",
  },
  {
    id: "6",
    name: "Warren Buffett",
    slug: "warren-buffett",
    netWorth: 110000000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Finance",
    occupation: "Investor",
    company: "Berkshire Hathaway",
    imageUrl: "/images/people/warren-buffett.jpg",
    bio: "Warren Buffett is an American business magnate, investor, and philanthropist. He is considered one of the most successful investors in the world.",
    categories: "3",
  },
  {
    id: "7",
    name: "Mark Zuckerberg",
    slug: "mark-zuckerberg",
    netWorth: 100000000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Technology",
    occupation: "Entrepreneur",
    company: "Meta Platforms",
    imageUrl: "/images/people/mark-zuckerberg.jpg",
    bio: "Mark Zuckerberg is an American business magnate, internet entrepreneur, and philanthropist. He is known for co-founding Meta Platforms, Inc.",
    categories: "2",
  },
  {
    id: "8",
    name: "Larry Page",
    slug: "larry-page",
    netWorth: 90000000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Technology",
    occupation: "Entrepreneur",
    company: "Alphabet Inc.",
    imageUrl: "/images/people/larry-page.jpg",
    bio: "Larry Page is an American computer scientist and internet entrepreneur. He is best known as one of the co-founders of Google.",
    categories: "2",
  },
  {
    id: "9",
    name: "Sergey Brin",
    slug: "sergey-brin",
    netWorth: 89000000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Technology",
    occupation: "Entrepreneur",
    company: "Alphabet Inc.",
    imageUrl: "/images/people/sergey-brin.jpg",
    bio: "Sergey Brin is an American computer scientist and internet entrepreneur who, with Larry Page, co-founded Google.",
    categories: "2",
  },
  {
    id: "10",
    name: "Michael Bloomberg",
    slug: "michael-bloomberg",
    netWorth: 70000000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Media",
    occupation: "Entrepreneur",
    company: "Bloomberg L.P.",
    imageUrl: "/images/people/michael-bloomberg.jpg",
    bio: "Michael Bloomberg is an American businessman, politician, philanthropist, and author. He is the majority owner and co-founder of Bloomberg L.P.",
    categories: "8",
  },
  {
    id: "11",
    name: "Mukesh Ambani",
    slug: "mukesh-ambani",
    netWorth: 90000000000,
    currency: "USD",
    source: "Forbes",
    lastUpdated: "2024-01-01",
    country: "India",
    industry: "Diversified",
    occupation: "Chairman",
    company: "Reliance Industries",
    imageUrl: "/images/people/mukesh-ambani.jpg",
    bio: "Mukesh Ambani is an Indian billionaire businessman. He is the chairman and managing director of Reliance Industries.",
    categories: "1",
  },
  {
    id: "12",
    name: "Gautam Adani",
    slug: "gautam-adani",
    netWorth: 80000000000,
    currency: "USD",
    source: "Forbes",
    lastUpdated: "2024-01-01",
    country: "India",
    industry: "Infrastructure",
    occupation: "Chairman",
    company: "Adani Group",
    imageUrl: "/images/people/gautam-adani.jpg",
    bio: "Gautam Adani is an Indian billionaire businessman. He is the chairman and founder of the Adani Group.",
    categories: "1",
  },
  {
    id: "13",
    name: "Francoise Bettencourt Meyers",
    slug: "francoise-bettencourt-meyers",
    netWorth: 75000000000,
    currency: "USD",
    source: "Forbes",
    lastUpdated: "2024-01-01",
    country: "France",
    industry: "Fashion",
    occupation: "Chairwoman",
    company: "L'Oréal",
    imageUrl: "/images/people/francoise-bettencourt-meyers.jpg",
    bio: "Francoise Bettencourt Meyers is a French businesswoman, heiress, and philanthropist. She is the chairwoman of L'Oréal.",
    categories: "7",
  },
  {
    id: "14",
    name: "Carlos Slim Helu",
    slug: "carlos-slim-helu",
    netWorth: 68000000000,
    currency: "USD",
    source: "Forbes",
    lastUpdated: "2024-01-01",
    country: "Mexico",
    industry: "Telecommunications",
    occupation: "Chairman",
    company: "América Móvil",
    imageUrl: "/images/people/carlos-slim-helu.jpg",
    bio: "Carlos Slim Helu is a Mexican businessman, investor, and philanthropist. He is the chairman and CEO of Grupo Carso.",
    categories: "1",
  },
  {
    id: "15",
    name: "Jim Walton",
    slug: "jim-walton",
    netWorth: 65000000000,
    currency: "USD",
    source: "Forbes",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Retail",
    occupation: "Heir",
    company: "Walmart",
    imageUrl: "/images/people/jim-walton.jpg",
    bio: "Jim Walton is an American businessman and heir to the fortune of Walmart. He is the youngest son of Sam Walton.",
    categories: "7",
  },
  {
    id: "16",
    name: "Rob Walton",
    slug: "rob-walton",
    netWorth: 64000000000,
    currency: "USD",
    source: "Forbes",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Retail",
    occupation: "Heir",
    company: "Walmart",
    imageUrl: "/images/people/rob-walton.jpg",
    bio: "Rob Walton is an American businessman and heir to the fortune of Walmart. He served as chairman of Walmart from 1992 to 2015.",
    categories: "7",
  },
  {
    id: "17",
    name: "Alice Walton",
    slug: "alice-walton",
    netWorth: 63000000000,
    currency: "USD",
    source: "Forbes",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Retail",
    occupation: "Heir",
    company: "Walmart",
    imageUrl: "/images/people/alice-walton.jpg",
    bio: "Alice Walton is an American heiress to the fortune of Walmart. She is the daughter of Sam Walton and Helen Walton.",
    categories: "7",
  },
  {
    id: "18",
    name: "David Thomson",
    slug: "david-thomson",
    netWorth: 62000000000,
    currency: "USD",
    source: "Forbes",
    lastUpdated: "2024-01-01",
    country: "Canada",
    industry: "Media",
    occupation: "Chairman",
    company: "Thomson Reuters",
    imageUrl: "/images/people/david-thomson.jpg",
    bio: "David Thomson, 3rd Baron Thomson of Fleet, is a Canadian media magnate. He is the chairman of Thomson Reuters.",
    categories: "8",
  },
  {
    id: "19",
    name: "Charles Koch",
    slug: "charles-koch",
    netWorth: 60000000000,
    currency: "USD",
    source: "Forbes",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Diversified",
    occupation: "Chairman and CEO",
    company: "Koch Industries",
    imageUrl: "/images/people/charles-koch.jpg",
    bio: "Charles Koch is an American businessman, political donor, and philanthropist. He is the chairman and CEO of Koch Industries.",
    categories: "1",
  },
  {
    id: "20",
    name: "Julia Koch",
    slug: "julia-koch",
    netWorth: 59000000000,
    currency: "USD",
    source: "Forbes",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Diversified",
    occupation: "Heir",
    company: "Koch Industries",
    imageUrl: "/images/people/julia-koch.jpg",
    bio: "Julia Koch is an American socialite, philanthropist, and one of the richest women in the world. She inherited her fortune from her husband, David Koch.",
    categories: "1",
  },
  {
    id: "21",
    name: "Amancio Ortega",
    slug: "amancio-ortega",
    netWorth: 77300000000,
    currency: "USD",
    source: "Forbes",
    lastUpdated: "2024-01-01",
    country: "Spain",
    industry: "Fashion",
    occupation: "Founder",
    company: "Inditex (Zara)",
    imageUrl: "/images/people/amancio-ortega.jpg",
    bio: "Amancio Ortega is a Spanish billionaire businessman. He is the founder of the Inditex fashion group, best known for its chain of Zara clothing and accessories shops.",
    categories: "7",
  },
  {
    id: "22",
    name: "Michael Dell",
    slug: "michael-dell",
    netWorth: 50100000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Technology",
    occupation: "Chairman and CEO",
    company: "Dell Technologies",
    imageUrl: "/images/people/michael-dell.jpg",
    bio: "Michael Dell is an American businessman, investor, philanthropist, and author. He is the founder, chairman, and CEO of Dell Technologies.",
    categories: "2",
  },
  {
    id: "23",
    name: "Masayoshi Son",
    slug: "masayoshi-son",
    netWorth: 24700000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "Japan",
    industry: "Technology",
    occupation: "Founder and CEO",
    company: "SoftBank Group",
    imageUrl: "/images/people/masayoshi-son.jpg",
    bio: "Masayoshi Son is a Japanese billionaire businessman, investor, and philanthropist. He is the founder and CEO of the SoftBank Group.",
    categories: "2",
  },
  {
    id: "24",
    name: "Jack Ma",
    slug: "jack-ma",
    netWorth: 34400000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "China",
    industry: "Technology",
    occupation: "Co-founder",
    company: "Alibaba Group",
    imageUrl: "/images/people/jack-ma.jpg",
    bio: "Jack Ma is a Chinese business magnate, investor, and philanthropist. He is the co-founder of Alibaba Group.",
    categories: "2",
  },
  {
    id: "25",
    name: "Ma Huateng",
    slug: "ma-huateng",
    netWorth: 37200000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "China",
    industry: "Technology",
    occupation: "Chairman and CEO",
    company: "Tencent",
    imageUrl: "/images/people/ma-huateng.jpg",
    bio: "Ma Huateng, also known as Pony Ma, is a Chinese internet entrepreneur. He is the founder, chairman and CEO of Tencent.",
    categories: "2",
  },
  {
    id: "26",
    name: "Shiv Nadar",
    slug: "shiv-nadar",
    netWorth: 28700000000,
    currency: "USD",
    source: "Forbes",
    lastUpdated: "2024-01-01",
    country: "India",
    industry: "Technology",
    occupation: "Founder and Chairman",
    company: "HCL Technologies",
    imageUrl: "/images/people/shiv-nadar.jpg",
    bio: "Shiv Nadar is an Indian billionaire industrialist and philanthropist. He is the founder and chairman of HCL Technologies.",
    categories: "2",
  },
  {
    id: "27",
    name: "Dietrich Mateschitz",
    slug: "dietrich-mateschitz",
    netWorth: 27000000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "Austria",
    industry: "Beverage",
    occupation: "Co-founder",
    company: "Red Bull",
    imageUrl: "/images/people/dietrich-mateschitz.jpg",
    bio: "Dietrich Mateschitz was an Austrian billionaire businessman. He was the co-founder of the Red Bull energy drink company.",
    categories: "1",
  },
  {
    id: "28",
    name: "Lee Shau Kee",
    slug: "lee-shau-kee",
    netWorth: 30400000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "Hong Kong",
    industry: "Real Estate",
    occupation: "Founder",
    company: "Henderson Land Development",
    imageUrl: "/images/people/lee-shau-kee.jpg",
    bio: "Lee Shau Kee is a Hong Kong businessman, investor, and philanthropist. He is the founder of Henderson Land Development.",
    categories: "6",
  },
  {
    id: "29",
    name: "Giovanni Ferrero",
    slug: "giovanni-ferrero",
    netWorth: 35100000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "Italy",
    industry: "Food",
    occupation: "Executive Chairman",
    company: "Ferrero SpA",
    imageUrl: "/images/people/giovanni-ferrero.jpg",
    bio: "Giovanni Ferrero is an Italian businessman. He is the executive chairman of Ferrero SpA.",
    categories: "1",
  },
  {
    id: "30",
    name: "Alain Wertheimer",
    slug: "alain-wertheimer",
    netWorth: 31200000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "France",
    industry: "Fashion",
    occupation: "Chairman",
    company: "Chanel",
    imageUrl: "/images/people/alain-wertheimer.jpg",
    bio: "Alain Wertheimer is a French businessman. He is the chairman of Chanel.",
    categories: "7",
  },
  {
    id: "31",
    name: "Gerard Wertheimer",
    slug: "gerard-wertheimer",
    netWorth: 31200000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "France",
    industry: "Fashion",
    occupation: "Chairman",
    company: "Chanel",
    imageUrl: "/images/people/gerard-wertheimer.jpg",
    bio: "Gerard Wertheimer is a French businessman. He is the chairman of Chanel.",
    categories: "7",
  },
  {
    id: "32",
    name: "Jacqueline Mars",
    slug: "jacqueline-mars",
    netWorth: 38300000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Food",
    occupation: "Heir",
    company: "Mars, Incorporated",
    imageUrl: "/images/people/jacqueline-mars.jpg",
    bio: "Jacqueline Mars is an American heiress and businesswoman. She is a member of the Mars family.",
    categories: "1",
  },
  {
    id: "33",
    name: "John Mars",
    slug: "john-mars",
    netWorth: 38300000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Food",
    occupation: "Heir",
    company: "Mars, Incorporated",
    imageUrl: "/images/people/john-mars.jpg",
    bio: "John Mars is an American businessman and heir. He is a member of the Mars family.",
    categories: "1",
  },
  {
    id: "34",
    name: "Li Ka-shing",
    slug: "li-ka-shing",
    netWorth: 34700000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "Hong Kong",
    industry: "Diversified",
    occupation: "Chairman",
    company: "CK Hutchison Holdings",
    imageUrl: "/images/people/li-ka-shing.jpg",
    bio: "Li Ka-shing is a Hong Kong business magnate, investor, and philanthropist. He is the chairman of CK Hutchison Holdings.",
    categories: "1",
  },
  {
    id: "35",
    name: "Stefan Persson",
    slug: "stefan-persson",
    netWorth: 20600000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "Sweden",
    industry: "Retail",
    occupation: "Chairman",
    company: "H&M",
    imageUrl: "/images/people/stefan-persson.jpg",
    bio: "Stefan Persson is a Swedish billionaire businessman. He is the chairman of H&M.",
    categories: "7",
  },
  {
    id: "36",
    name: "Phil Knight",
    slug: "phil-knight",
    netWorth: 49000000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Retail",
    occupation: "Co-founder",
    company: "Nike",
    imageUrl: "/images/people/phil-knight.jpg",
    bio: "Phil Knight is an American billionaire businessman. He is the co-founder of Nike.",
    categories: "7",
  },
  {
    id: "37",
    name: "Steve Ballmer",
    slug: "steve-ballmer",
    netWorth: 91400000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Technology",
    occupation: "Former CEO",
    company: "Microsoft",
    imageUrl: "/images/people/steve-ballmer.jpg",
    bio: "Steve Ballmer is an American businessman and investor. He is the former CEO of Microsoft.",
    categories: "1",
  },
  {
    id: "38",
    name: "Rupert Murdoch",
    slug: "rupert-murdoch",
    netWorth: 17700000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Media",
    occupation: "Chairman",
    company: "News Corp",
    imageUrl: "/images/people/rupert-murdoch.jpg",
    bio: "Rupert Murdoch is an Australian-born American media proprietor. He is the chairman of News Corp.",
    categories: "8",
  },
  {
    id: "39",
    name: "Donald Bren",
    slug: "donald-bren",
    netWorth: 17000000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Real Estate",
    occupation: "Chairman",
    company: "Irvine Company",
    imageUrl: "/images/people/donald-bren.jpg",
    bio: "Donald Bren is an American businessman. He is the chairman of the Irvine Company.",
    categories: "6",
  },
  {
    id: "40",
    name: "Ray Dalio",
    slug: "ray-dalio",
    netWorth: 19100000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "United States",
    industry: "Finance",
    occupation: "Founder",
    company: "Bridgewater Associates",
    imageUrl: "/images/people/ray-dalio.jpg",
    bio: "Ray Dalio is an American billionaire investor, hedge fund manager, and philanthropist. He is the founder of Bridgewater Associates.",
    categories: "3",
  },
  {
    id: "41",
    name: "William Ding",
    slug: "william-ding",
    netWorth: 25000000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "China",
    industry: "Technology",
    occupation: "CEO",
    company: "NetEase",
    imageUrl: "/images/people/william-ding.jpg",
    bio: "William Ding is a Chinese businessman. He is the CEO of NetEase.",
    categories: "2",
  },
  {
    id: "42",
    name: "He Xiangjian",
    slug: "he-xiangjian",
    netWorth: 28300000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "China",
    industry: "Consumer Electronics",
    occupation: "Founder",
    company: "Midea Group",
    imageUrl: "/images/people/he-xiangjian.jpg",
    bio: "He Xiangjian is a Chinese businessman. He is the founder of Midea Group.",
    categories: "1",
  },
  {
    id: "43",
    name: "Colin Zheng Huang",
    slug: "colin-zheng-huang",
    netWorth: 31700000000,
    currency: "USD",
    source: "Bloomberg",
    lastUpdated: "2024-01-01",
    country: "China",
    industry: "Technology",
    occupation: "Founder",
    company: "Pinduoduo",
    imageUrl: "/images/people/colin-zheng-huang.jpg",
    bio: "Colin Zheng Huang is a Chinese billionaire businessman. He is the founder of the e-commerce platform Pinduoduo.",
    categories: "2",
  },
];
