export interface NetWorthPerson {
  id: number;
  slug: string;
  name: string;
  netWorth: number;
  currency: string;
  age: number;
  country: string;
  industry: string;
  occupation: string;
  company?: string;
  source: string;
  lastUpdated: string;
  description: string;
  imageUrl?: string;
  categoryId: number;
}

export interface CategoryMetadata {
  id: number;
  slug: string;
  title: string;
  description: string;
  imageUrl?: string;
}

const netWorthData: NetWorthPerson[] = [
  {
    id: 1,
    slug: "elon-musk",
    name: "Elon Musk",
    netWorth: 219000000000,
    currency: "USD",
    age: 50,
    country: "United States",
    industry: "Technology",
    occupation: "Entrepreneur",
    company: "Tesla, SpaceX",
    source: "Tesla, SpaceX",
    lastUpdated: "2023-03-10",
    description: "Elon Musk is the CEO of Tesla and SpaceX.",
    imageUrl: "/elon-musk.jpeg",
    categoryId: 1,
  },
  {
    id: 2,
    slug: "jeff-bezos",
    name: "Jeff Bezos",
    netWorth: 171000000000,
    currency: "USD",
    age: 58,
    country: "United States",
    industry: "Technology",
    occupation: "Entrepreneur",
    company: "Amazon",
    source: "Amazon",
    lastUpdated: "2023-03-10",
    description: "Jeff Bezos is the founder of Amazon.",
    imageUrl: "/jeff-bezos.jpeg",
    categoryId: 1,
  },
  {
    id: 3,
    slug: "bernard-arnault",
    name: "Bernard Arnault",
    netWorth: 158000000000,
    currency: "USD",
    age: 73,
    country: "France",
    industry: "Fashion",
    occupation: "Entrepreneur",
    company: "LVMH",
    source: "LVMH",
    lastUpdated: "2023-03-10",
    description: "Bernard Arnault is the CEO of LVMH.",
    imageUrl: "/bernard-arnault.jpeg",
    categoryId: 2,
  },
  {
    id: 4,
    slug: "bill-gates",
    name: "Bill Gates",
    netWorth: 129000000000,
    currency: "USD",
    age: 66,
    country: "United States",
    industry: "Technology",
    occupation: "Philanthropist",
    company: "Microsoft",
    source: "Microsoft",
    lastUpdated: "2023-03-10",
    description: "Bill Gates is the co-founder of Microsoft.",
    imageUrl: "/bill-gates.jpeg",
    categoryId: 3,
  },
  {
    id: 5,
    slug: "warren-buffett",
    name: "Warren Buffett",
    netWorth: 118000000000,
    currency: "USD",
    age: 91,
    country: "United States",
    industry: "Finance",
    occupation: "Investor",
    company: "Berkshire Hathaway",
    source: "Berkshire Hathaway",
    lastUpdated: "2023-03-10",
    description: "Warren Buffett is the CEO of Berkshire Hathaway.",
    imageUrl: "/warren-buffett.jpeg",
    categoryId: 4,
  },
  {
    id: 6,
    slug: "larry-page",
    name: "Larry Page",
    netWorth: 111000000000,
    currency: "USD",
    age: 49,
    country: "United States",
    industry: "Technology",
    occupation: "Entrepreneur",
    company: "Alphabet Inc.",
    source: "Google",
    lastUpdated: "2023-03-10",
    description: "Larry Page is the co-founder of Google.",
    imageUrl: "/larry-page.jpeg",
    categoryId: 1,
  },
  {
    id: 7,
    slug: "sergey-brin",
    name: "Sergey Brin",
    netWorth: 107000000000,
    currency: "USD",
    age: 48,
    country: "United States",
    industry: "Technology",
    occupation: "Entrepreneur",
    company: "Alphabet Inc.",
    source: "Google",
    lastUpdated: "2023-03-10",
    description: "Sergey Brin is the co-founder of Google.",
    imageUrl: "/sergey-brin.jpeg",
    categoryId: 1,
  },
  {
    id: 8,
    slug: "mukesh-ambani",
    name: "Mukesh Ambani",
    netWorth: 90700000000,
    currency: "USD",
    age: 65,
    country: "India",
    industry: "Diversified",
    occupation: "Entrepreneur",
    company: "Reliance Industries",
    source: "Reliance Industries",
    lastUpdated: "2023-03-10",
    description: "Mukesh Ambani is the chairman of Reliance Industries.",
    imageUrl: "/mukesh-ambani.jpeg",
    categoryId: 5,
  },
  {
    id: 9,
    slug: "gautam-adani",
    name: "Gautam Adani",
    netWorth: 90000000000,
    currency: "USD",
    age: 60,
    country: "India",
    industry: "Infrastructure",
    occupation: "Entrepreneur",
    company: "Adani Group",
    source: "Adani Group",
    lastUpdated: "2023-03-10",
    description: "Gautam Adani is the chairman of Adani Group.",
    imageUrl: "/gautam-adani.jpeg",
    categoryId: 5,
  },
  {
    id: 10,
    slug: "michael-dell",
    name: "Michael Dell",
    netWorth: 50100000000,
    currency: "USD",
    age: 57,
    country: "United States",
    industry: "Technology",
    occupation: "Entrepreneur",
    company: "Dell Technologies",
    source: "Dell Technologies",
    lastUpdated: "2023-03-10",
    description: "Michael Dell is the CEO of Dell Technologies.",
    imageUrl: "/michael-dell.jpeg",
    categoryId: 1,
  },
  {
    id: 11,
    slug: "patrice-motsepe",
    name: "Patrice Motsepe",
    netWorth: 2900000000,
    currency: "USD",
    age: 60,
    country: "South Africa",
    industry: "Mining",
    occupation: "Businessman",
    company: "African Rainbow Minerals",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Patrice Motsepe is the founder and chairman of African Rainbow Minerals.",
    imageUrl: "/patrice-motsepe.jpeg",
    categoryId: 6,
  },
  {
    id: 12,
    slug: "nicky-oppenheimer",
    name: "Nicky Oppenheimer",
    netWorth: 8700000000,
    currency: "USD",
    age: 77,
    country: "South Africa",
    industry: "Diamonds",
    occupation: "Businessman",
    company: "De Beers",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Nicky Oppenheimer is the former chairman of De Beers diamond mining company.",
    imageUrl: "/nicky-oppenheimer.jpeg",
    categoryId: 6,
  },
  {
    id: 13,
    slug: "johann- Rupert",
    name: "Johann Rupert",
    netWorth: 11000000000,
    currency: "USD",
    age: 72,
    country: "South Africa",
    industry: "Luxury Goods",
    occupation: "Businessman",
    company: "Richemont",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Johann Rupert is the chairman of the Swiss luxury goods company Richemont.",
    imageUrl: "/johann-rupert.jpeg",
    categoryId: 6,
  },
  {
    id: 14,
    slug: "Koos-Bekker",
    name: "Koos Bekker",
    netWorth: 2700000000,
    currency: "USD",
    age: 69,
    country: "South Africa",
    industry: "Media",
    occupation: "Businessman",
    company: "Naspers",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Koos Bekker is the chairman of Naspers, a South African media company.",
    imageUrl: "/koos-bekker.jpeg",
    categoryId: 6,
  },
  {
    id: 15,
    slug: "allan-gray",
    name: "Allan Gray",
    netWorth: 2200000000,
    currency: "USD",
    age: 83,
    country: "South Africa",
    industry: "Finance",
    occupation: "Investor",
    company: "Allan Gray Investment Management",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Allan Gray is the founder of Allan Gray Investment Management.",
    imageUrl: "/allan-gray.jpeg",
    categoryId: 6,
  },
  {
    id: 16,
    slug: "michiel-le-roux",
    name: "Michiel Le Roux",
    netWorth: 1300000000,
    currency: "USD",
    age: 72,
    country: "South Africa",
    industry: "Banking",
    occupation: "Businessman",
    company: "Capitec Bank",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Michiel Le Roux is the founder of Capitec Bank.",
    imageUrl: "/michiel-le-roux.jpeg",
    categoryId: 6,
  },
  {
    id: 17,
    slug: "raymond-ackerman",
    name: "Raymond Ackerman",
    netWorth: 1000000000,
    currency: "USD",
    age: 91,
    country: "South Africa",
    industry: "Retail",
    occupation: "Businessman",
    company: "Pick n Pay",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Raymond Ackerman is the founder of Pick n Pay.",
    imageUrl: "/raymond-ackerman.jpeg",
    categoryId: 6,
  },
  {
    id: 18,
    slug: "stephen- Saad",
    name: "Stephen Saad",
    netWorth: 1200000000,
    currency: "USD",
    age: 57,
    country: "South Africa",
    industry: "Pharmaceuticals",
    occupation: "Businessman",
    company: "Aspen Pharmacare",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Stephen Saad is the CEO of Aspen Pharmacare.",
    imageUrl: "/stephen-saad.jpeg",
    categoryId: 6,
  },
  {
    id: 19,
    slug: "giovanni-ravazzotti",
    name: "Giovanni Ravazzotti",
    netWorth: 1100000000,
    currency: "USD",
    age: 72,
    country: "South Africa",
    industry: "Construction",
    occupation: "Businessman",
    company: "CMC di Ravenna",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Giovanni Ravazzotti is the chairman of CMC di Ravenna.",
    imageUrl: "/giovanni-ravazzotti.jpeg",
    categoryId: 6,
  },
  {
    id: 20,
    slug: "grant-tregurtha",
    name: "Grant Tregurtha",
    netWorth: 1000000000,
    currency: "USD",
    age: 57,
    country: "South Africa",
    industry: "Real Estate",
    occupation: "Businessman",
    company: "Growthpoint Properties",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Grant Tregurtha is the CEO of Growthpoint Properties.",
    imageUrl: "/grant-tregurtha.jpeg",
    categoryId: 6,
  },
  {
    id: 21,
    slug: "douw-Steyn",
    name: "Douw Steyn",
    netWorth: 900000000,
    currency: "USD",
    age: 69,
    country: "South Africa",
    industry: "Insurance",
    occupation: "Businessman",
    company: "Auto & General Insurance Services",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Douw Steyn is the founder of Auto & General Insurance Services.",
    imageUrl: "/douw-steyn.jpeg",
    categoryId: 7,
  },
  {
    id: 22,
    slug: "ian-Kirby",
    name: "Ian Kirby",
    netWorth: 800000000,
    currency: "USD",
    age: 72,
    country: "South Africa",
    industry: "Insurance",
    occupation: "Businessman",
    company: "Outsurance",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Ian Kirby is the founder of Outsurance.",
    imageUrl: "/ian-kirby.jpeg",
    categoryId: 7,
  },
  {
    id: 23,
    slug: "glyn-du Plessis",
    name: "Glyn du Plessis",
    netWorth: 700000000,
    currency: "USD",
    age: 69,
    country: "South Africa",
    industry: "Insurance",
    occupation: "Businessman",
    company: "Hollard Insurance",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Glyn du Plessis is the chairman of Hollard Insurance.",
    imageUrl: "/glyn-du-plessis.jpeg",
    categoryId: 7,
  },
  {
    id: 24,
    slug: "marius-du Toit",
    name: "Marius du Toit",
    netWorth: 600000000,
    currency: "USD",
    age: 66,
    country: "South Africa",
    industry: "Insurance",
    occupation: "Businessman",
    company: "African Rainbow Capital",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Marius du Toit is the chairman of African Rainbow Capital.",
    imageUrl: "/marius-du-toit.jpeg",
    categoryId: 7,
  },
  {
    id: 25,
    slug: "hermanus-Steyn",
    name: "Hermanus Steyn",
    netWorth: 500000000,
    currency: "USD",
    age: 63,
    country: "South Africa",
    industry: "Insurance",
    occupation: "Businessman",
    company: "PSG Group",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Hermanus Steyn is the chairman of PSG Group.",
    imageUrl: "/hermanus-steyn.jpeg",
    categoryId: 7,
  },
  {
    id: 26,
    slug: "jannie-mouton",
    name: "Jannie Mouton",
    netWorth: 400000000,
    currency: "USD",
    age: 75,
    country: "South Africa",
    industry: "Insurance",
    occupation: "Businessman",
    company: "PSG Group",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Jannie Mouton is the founder of PSG Group.",
    imageUrl: "/jannie-mouton.jpeg",
    categoryId: 7,
  },
  {
    id: 27,
    slug: "willem-Roode",
    name: "Willem Roode",
    netWorth: 300000000,
    currency: "USD",
    age: 60,
    country: "South Africa",
    industry: "Insurance",
    occupation: "Businessman",
    company: "OUTsurance",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Willem Roode is the CEO of OUTsurance.",
    imageUrl: "/willem-roode.jpeg",
    categoryId: 7,
  },
  {
    id: 28,
    slug: "jurie-erwee",
    name: "Jurie Erwee",
    netWorth: 200000000,
    currency: "USD",
    age: 63,
    country: "South Africa",
    industry: "Insurance",
    occupation: "Businessman",
    company: "Capitec Bank",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Jurie Erwee is the chairman of Capitec Bank.",
    imageUrl: "/jurie-erwee.jpeg",
    categoryId: 7,
  },
  {
    id: 29,
    slug: "michel-du Toit",
    name: "Michel du Toit",
    netWorth: 100000000,
    currency: "USD",
    age: 60,
    country: "South Africa",
    industry: "Insurance",
    occupation: "Businessman",
    company: "Sanlam",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Michel du Toit is the CEO of Sanlam.",
    imageUrl: "/michel-du-toit.jpeg",
    categoryId: 7,
  },
  {
    id: 30,
    slug: "hein-du Toit",
    name: "Hein du Toit",
    netWorth: 50000000,
    currency: "USD",
    age: 57,
    country: "South Africa",
    industry: "Insurance",
    occupation: "Businessman",
    company: "African Rainbow Capital",
    source: "Forbes",
    lastUpdated: "2023-03-10",
    description: "Hein du Toit is the CEO of African Rainbow Capital.",
    imageUrl: "/hein-du-toit.jpeg",
    categoryId: 7,
  },
];

const netWorthCategories: CategoryMetadata[] = [
  {
    id: 1,
    slug: "technology",
    title: "Technology",
    description: "Individuals in the technology industry",
    imageUrl: "/category-technology.jpeg",
  },
  {
    id: 2,
    slug: "fashion",
    title: "Fashion",
    description: "Individuals in the fashion industry",
    imageUrl: "/category-fashion.jpeg",
  },
  {
    id: 3,
    slug: "philanthropy",
    title: "Philanthropy",
    description: "Individuals known for their philanthropic efforts",
    imageUrl: "/category-philanthropy.jpeg",
  },
  {
    id: 4,
    slug: "finance",
    title: "Finance",
    description: "Individuals in the finance industry",
    imageUrl: "/category-finance.jpeg",
  },
  {
    id: 5,
    slug: "diversified",
    title: "Diversified",
    description: "Individuals with diversified business interests",
    imageUrl: "/category-diversified.jpeg",
  },
  {
    id: 6,
    slug: "south-africa",
    title: "South Africa",
    description: "Richest people in South Africa",
    imageUrl: "/category-south-africa.jpeg",
  },
  {
    id: 7,
    slug: "insurance-executives",
    title: "Insurance Executives",
    description: "Top Insurance Executives in South Africa",
    imageUrl: "/category-insurance-executives.jpeg",
  },
];

export const netWorthPeople = netWorthData;

// Function to find a person by slug
export const findPersonBySlug = (slug: string): NetWorthPerson | undefined => {
  return netWorthData.find((person) => person.slug === slug);
};

// Function to get similar people based on industry
export const getSimilarPeople = (person: NetWorthPerson, limit: number): NetWorthPerson[] => {
  return netWorthData
    .filter((p) => p.industry === person.industry && p.id !== person.id)
    .slice(0, limit);
};

// Function to find a category by slug
export const findCategoryBySlug = (slug: string): CategoryMetadata | undefined => {
  return netWorthCategories.find((category) => category.slug === slug);
};

// Function to get category ID by slug
export const getCategoryIdBySlug = (slug: string): number | undefined => {
  const category = netWorthCategories.find((cat) => cat.slug === slug);
  return category ? category.id : undefined;
};

// Function to get all categories
export const getAllCategories = (): CategoryMetadata[] => {
  return [...netWorthCategories];
};

// Function to get people by category
export const getPeopleByCategory = (categoryId: number): NetWorthPerson[] => {
  return netWorthData.filter(person => person.categoryId === categoryId);
};

// Function to format net worth
export const formatNetWorth = (amount: number, currency = 'ZAR'): string => {
  const options: Intl.NumberFormatOptions = {
    style: 'currency',
    currency: currency,
    maximumFractionDigits: 1,
    minimumFractionDigits: 1,
    notation: 'compact',
    compactDisplay: 'short',
  };

  return amount.toLocaleString('en-US', options);
};
