export interface NetWorthPerson {
  id: string;
  name: string;
  netWorth: number;
  currency: string;
  occupation: string;
  age: number;
  country: string;
  industry: string;
  company?: string;
  description: string;
  source: string;
  lastUpdated: string;
  imageUrl: string;
  slug: string;
  categories: string[];
}

export const netWorthPeople: NetWorthPerson[] = [
  {
    id: "1",
    name: "Patrice Motsepe",
    netWorth: 3200000000,
    currency: "USD",
    occupation: "Mining Magnate",
    age: 61,
    country: "South Africa",
    industry: "Mining",
    company: "African Rainbow Minerals",
    description: "A trailblazer in the South African mining sector, Patrice Motsepe has carved out a remarkable success story through his company, African Rainbow Minerals (ARM). Demonstrating exceptional entrepreneurial drive, Motsepe transformed a modest mining services business into a diversified mining giant with interests in platinum, gold, ferrous metals, and coal. His journey is particularly noteworthy as he was one of the first black South Africans to enter the mining industry at a senior level following the end of apartheid. Beyond his business achievements, Motsepe is also recognized for his philanthropic commitments through the Motsepe Foundation, which supports education, healthcare, and poverty alleviation initiatives. Furthermore, his passion for sports is evident in his ownership of the Mamelodi Sundowns Football Club, one of the most successful teams in South Africa.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://media.gettyimages.com/id/994504746/photo/johannesburg-south-africa-patrice-motsepe-of-the-motsepe-foundation-speaks-during-the-press.jpg?s=612x612&w=0&k=20&c=Y8KvOlDCUxXV-4LwCz3fNhHZtCs__8_C9Rf7ssBO6xY=",
    slug: "patrice-motsepe",
    categories: ["football-club-owners", "mining-magnates", "philanthropists"]
  },
  {
    id: "2",
    name: "Johann Rupert",
    netWorth: 10700000000,
    currency: "USD",
    occupation: "Businessman",
    age: 73,
    country: "South Africa",
    industry: "Luxury Goods",
    company: "Richemont",
    description: "A titan of South African industry, Johann Rupert has expertly steered the fortunes of luxury goods conglomerate Richemont, a company renowned for its prestigious brands in jewelry, watches, fashion, and writing instruments. Born into a family with a strong entrepreneurial legacy, Rupert inherited and expanded upon his father Anton Rupert's business empire. Beyond Richemont, his influence extends through Remgro, an investment holding company with diverse interests spanning banking, healthcare, and consumer products. Known for his astute business acumen and often outspoken views on economic and social issues in South Africa, Rupert maintains a relatively private profile despite his significant public standing. His leadership has been instrumental in positioning Richemont as a global leader in the high-end market, navigating the complexities of international commerce and evolving consumer preferences.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Rupert-Johann-2004.jpg",
    slug: "johann-rupert",
    categories: ["luxury-goods", "business-magnates"]
  },
  {
    id: "3",
    name: "Nicky Oppenheimer",
    netWorth: 8700000000,
    currency: "USD",
    occupation: "Diamond Heir",
    age: 78,
    country: "South Africa",
    industry: "Mining",
    company: "De Beers",
    description: "The name Oppenheimer resonates deeply within the history of South African mining, particularly in the realm of diamonds. Nicky Oppenheimer represents the third generation of this influential family to lead the De Beers diamond mining company. For decades, the Oppenheimer family held a dominant position in the global diamond trade, shaping the industry and contributing significantly to South Africa's economic landscape. While the family's direct control over De Beers has since transitioned, Nicky Oppenheimer remains a figure of considerable wealth and influence. His legacy is intertwined with the intricate history of diamond mining in the region, a story marked by both immense prosperity and complex social implications. Today, he focuses on conservation efforts and philanthropic endeavors, channeling his resources towards preserving Africa's natural heritage and supporting various social causes.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://media.gettyimages.com/id/81157695/photo/gaborone-botswana-nicky-oppenheimer-age-63-the-chairman-of-de-beers-sits-in-a-de-beers-office.jpg?s=612x612&w=0&k=20&c=7JVCg_OsD8SQNXvo7F3t5xZ7G5Yc82Y3wiK6kjRjxfw=",
    slug: "nicky-oppenheimer",
    categories: ["mining-magnates", "diamond-industry"]
  },
  {
    id: "4",
    name: "Koos Bekker",
    netWorth: 2300000000,
    currency: "USD",
    occupation: "Media Executive",
    age: 71,
    country: "South Africa",
    industry: "Media & Technology",
    company: "Naspers",
    description: "Having served as the chief executive officer of Naspers for nearly two decades, Koos Bekker is widely credited with transforming the South African publishing house into a global internet and media powerhouse. His visionary leadership saw Naspers make an early and incredibly lucrative investment in the Chinese technology company Tencent, a move that has generated enormous returns and significantly elevated Naspers' international standing. Bekker's strategic foresight and understanding of the burgeoning digital landscape were instrumental in this transformation. Though he stepped down as CEO in 2014, his impact on Naspers and the broader technology investment world remains profound. His tenure is remembered for bold decisions and a keen eye for identifying high-growth potential in emerging markets, particularly in the rapidly evolving internet sector.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://media.gettyimages.com/id/472544152/photo/koos-bekker-billionaire-and-chairman-of-naspers-ltd-reacts-during-an-interview-at-his-office.jpg?s=612x612&w=0&k=20&c=9cuD31U6fHI1XqU6GUHs6q2XLhJYcEdRD3g3cwBKX3I=",
    slug: "koos-bekker",
    categories: ["media-executives", "tech-investors"]
  },
  {
    id: "5",
    name: "Michiel Le Roux",
    netWorth: 1100000000,
    currency: "USD",
    occupation: "Banker",
    age: 73,
    country: "South Africa",
    industry: "Banking",
    company: "Capitec Bank",
    description: "The astute businessman behind Capitec Bank, Michiel Le Roux, has significantly disrupted the South African banking industry. Recognizing a gap in the market for a more accessible and affordable banking model, Le Roux played a pivotal role in establishing Capitec as a major player. The bank's innovative approach, focusing on simplicity, transparency, and lower fees, resonated with a large segment of the population, leading to rapid growth and challenging the dominance of more established institutions. Le Roux's entrepreneurial spirit and understanding of consumer needs were crucial to Capitec's success. While he may maintain a lower public profile compared to some other business leaders, his impact on the financial lives of millions of South Africans through Capitec Bank is undeniable and has earned him a place among the country's wealthiest individuals.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://imageio.forbes.com/specials-images/imageserve/5a80fc894bbe6f2652f543fb/0x0.jpg?format=jpg&crop=455,455,x87,y0,safe&height=416&width=416&fit=bounds",
    slug: "michiel-le-roux",
    categories: ["bankers", "financial-innovators"]
  },
  {
    id: "6",
    name: "Douw Steyn",
    netWorth: 1000000000,
    currency: "USD",
    occupation: "Insurance Entrepreneur",
    age: 70,
    country: "South Africa",
    industry: "Insurance",
    company: "BGL Group",
    description: "A prominent figure in the South African property development sector, Douw Steyn has left an indelible mark on the landscape with his ambitious and large-scale projects. He is best known for the creation of Steyn City, a sprawling and luxurious mixed-use development north of Johannesburg, which exemplifies his vision for creating self-contained, high-quality urban environments. Steyn's career has been characterized by a bold approach to development, often involving significant investment and innovative design concepts. His ventures have not only generated substantial wealth but have also contributed to shaping the urban sprawl and lifestyle offerings in the Gauteng province. Through his various property endeavors, Steyn has demonstrated a keen understanding of market trends and a commitment to creating distinctive and sought-after residential and commercial spaces.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://www.goodthingsguy.com/wp-content/uploads/2025/02/douw-steyn.jpg",
    slug: "douw-steyn",
    categories: ["insurance-executives", "property-developers"]
  },
  {
    id: "7",
    name: "Stephen Saad",
    netWorth: 900000000,
    currency: "USD",
    occupation: "Pharmaceutical Executive",
    age: 59,
    country: "South Africa",
    industry: "Pharmaceuticals",
    company: "Aspen Pharmacare",
    description: "As the co-founder and current Chief Executive Officer of Aspen Pharmacare, Stephen Saad has built a pharmaceutical giant with a global reach. Starting from relatively humble beginnings, Saad and his partners transformed Aspen into the largest pharmaceutical manufacturer in Africa, with a growing presence in international markets. His leadership has been instrumental in navigating the complexities of the pharmaceutical industry, including research and development, manufacturing, and distribution across diverse regulatory environments. Saad's entrepreneurial journey is a testament to his strategic vision and his ability to capitalize on opportunities within the healthcare sector. Aspen's success under his guidance has not only contributed to his personal wealth but has also played a significant role in providing access to essential medicines for millions of people in South Africa and beyond.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://lh3.googleusercontent.com/dPQ9LQuUnK6m65uLminDsUclszwNcLjorH7B7LqVFg_ztCHK6QPjW5tn-olOpgFPq32iBK8BERSG2wAFU-XiDxrd-PMyEfTB60ls4Nuzf-SuuA",
    slug: "stephen-saad",
    categories: ["pharmaceutical-executives", "healthcare-entrepreneurs"]
  },
  {
    id: "8",
    name: "Cyril Ramaphosa",
    netWorth: 450000000,
    currency: "USD",
    occupation: "Politician & Businessman",
    age: 71,
    country: "South Africa",
    industry: "Politics & Business",
    company: "Shanduka Group",
    description: "Currently serving as the President of the Republic of South Africa, Cyril Ramaphosa has had a long and distinguished career spanning business, politics, and trade unionism. Before entering the highest office, Ramaphosa was a prominent businessman with significant investments in various sectors, including mining, telecommunications, and beverages. His early career saw him as a key figure in the anti-apartheid movement and the formation of the powerful National Union of Mineworkers. Following the transition to democracy, he played a crucial role in the drafting of South Africa's constitution. Ramaphosa's journey reflects a unique blend of political activism, business acumen, and public service, making him a complex and influential figure in South African society. His current focus is on addressing the country's economic challenges and fostering social cohesion.",
    source: "Bloomberg",
    lastUpdated: "2025-03-28",
    imageUrl: "https://lh3.googleusercontent.com/CuxBt-N3r9YNz9dlrNK8AMZLq5_WdkyjH1-esXje3fwBWMLnA9wxfiuVYYqj5u0KV5PJkX_4CpipTkr2jlnaOgrGvp7GtMCnsGDc3SlRQj8X9Ic=s750",
    slug: "cyril-ramaphosa",
    categories: ["politicians", "business-leaders"]
  },
  {
    id: "9",
    name: "Jannie Mouton",
    netWorth: 800000000,
    currency: "USD",
    occupation: "Investor",
    age: 77,
    country: "South Africa",
    industry: "Finance",
    company: "PSG Group",
    description: "Often hailed as the 'Boere Buffett,' Jannie Mouton is a highly respected figure in the South African investment community. He founded the PSG Group, an investment holding company with interests in financial services, banking, education, and agriculture. Mouton's investment philosophy, characterized by a long-term perspective and a focus on value investing, has proven remarkably successful over the years. His astute stock-picking abilities and his knack for identifying promising businesses have earned him a legendary status among investors in South Africa. Mouton's down-to-earth approach and his willingness to share his insights have made him a popular and influential voice in the financial markets. His legacy is one of shrewd investment decisions and the creation of a diversified and enduring investment group that continues to generate value.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://imageio.forbes.com/specials-images/imageserve/8ab9cfd81c126830ba99bde49a2fdc07/0x0.jpg?format=jpg&crop=531,532,x105,y16,safe&height=416&width=416&fit=bounds",
    slug: "jannie-mouton",
    categories: ["investment-gurus", "financial-advisors"]
  },
  {
    id: "10",
    name: "Adrian Gore",
    netWorth: 700000000,
    currency: "USD",
    occupation: "Insurance Executive",
    age: 59,
    country: "South Africa",
    industry: "Insurance & Healthcare",
    company: "Discovery Limited",
    description: "The visionary founder and Chief Executive Officer of Discovery Limited, Adrian Gore has revolutionized the South African healthcare and financial services industries with his innovative business models. Discovery's integrated approach, centered around incentivizing healthy behavior through its Vitality program, has gained international recognition and has been adopted in various forms across the globe. Gore's entrepreneurial spirit and his commitment to using data and behavioral economics to improve people's health and financial well-being have been the driving forces behind Discovery's success. His leadership has not only built a highly profitable company but has also had a significant positive impact on the health and wellness of its millions of members. Gore's forward-thinking approach and his ability to disrupt traditional industries have established him as a prominent and influential business leader in South Africa.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/78/Adrian_Gore.jpg",
    slug: "adrian-gore",
    categories: ["insurance-executives", "healthcare-innovators"]
  },
    {
    id: "11",
    name: "DJ Black Coffee",
    netWorth: 60000000,
    currency: "USD",
    occupation: "DJ, Record Producer, & Songwriter",
    age: 49,
    country: "South Africa",
    industry: "Music & Entertainment",
    company: "Soulistic Music",
    description: "Globally recognized as a pioneer of Afro-house music, Nkosinathi Innocent Maphumulo, famously known as Black Coffee, has etched his name as a dominant force in the international DJ scene. His sophisticated blend of deep house infused with African rhythms has captivated audiences worldwide, earning him numerous accolades, including a Grammy Award. Beyond his electrifying performances at prestigious venues and festivals across the globe, Black Coffee has also proven himself as a shrewd businessman, investing in multiple properties both in South Africa and the United States. His journey from humble beginnings to international stardom serves as an inspiration to aspiring artists, demonstrating that talent, hard work, and a unique artistic vision can transcend geographical boundaries and cultural differences. His influence extends beyond music, positioning him as a cultural ambassador for South Africa on the global stage.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://i0.wp.com/mgosi.co.za/wp-content/uploads/2022/06/Black-coffee.jpeg?fit=1440%2C1440&ssl=1",
    slug: "black-coffee",
	categories: ["djs"]
  },
  {
    id: "12",
    name: "DJ Zinhle",
    netWorth: 3000000,
    currency: "USD",
    occupation: "DJ, Businesswoman, & Producer",
    age: 42,
    country: "South Africa",
    industry: "Music & Entertainment",
    company: "Kalawa Jazmee",
    description: "Ntombezinhle Jiyane, popularly known as DJ Zinhle, has solidified her position as one of the most successful and influential female DJs in Africa. Since launching her career in 2004, she has not only dominated the music scene with her infectious house beats but has also proven to be a formidable businesswoman. DJ Zinhle has successfully ventured into various entrepreneurial endeavors, including her fashion accessory brand 'Timeless,' a furniture manufacturing and design company called 'DJZinhle Dancing Pencils' (co-owned with her brother), and a beverage company, 'Boulevard Rose,' specializing in wines and champagnes. Her ability to seamlessly transition between the music industry and the business world showcases her versatility and astute business acumen. Residing in an impressive Johannesburg mansion, DJ Zinhle's success story serves as an inspiration for aspiring female entrepreneurs and DJs across the continent.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://lh3.googleusercontent.com/tGIdzVbOsBiZVcuLxpWFEiPv9yCYBMaOySIqjFOZSkgIO5zciYOziL6xhD-_PE5YRbAE_lSXTXUi3jVTfJa29uE1MijcM2HYrSUb0taLwXV3Ug=s750",
    slug: "dj-zinhle",
	categories: ["djs"]
  },
  {
    id: "13",
    name: "DJ Kabza De Small",
    netWorth: 2000000,
    currency: "USD",
    occupation: "DJ & Record Producer",
    age: 32,
    country: "South Africa",
    industry: "Music & Entertainment",
    company: "Piano Hub, Bestbyfar",
    description: "Kabelo Petrus Motha, widely celebrated as Kabza De Small, has emerged as a central figure in the amapiano music genre, earning him the moniker 'King of Amapiano.' His innovative and prolific production has significantly shaped the sound of this popular South African genre, collaborating with numerous artists and releasing a consistent stream of hit tracks. Often working in tandem with DJ Maphorisa under the moniker 'Scorpion Kings,' Kabza De Small's influence on the South African music landscape is undeniable. His intricate understanding of rhythm and melody, combined with his ability to create infectious grooves, has garnered him a massive following and critical acclaim. Despite his relatively young age, Kabza De Small's contribution to amapiano has cemented his status as a musical innovator and a key driver of the genre's widespread popularity.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://static.ra.co/images/profiles/square/kabzadesmall.jpg?dateUpdated=1611781076000",
    slug: "kabza-de-small",
	categories: ["djs"]
  },
  {
    id: "14",
    name: "DJ Maphorisa",
    netWorth: 6000000,
    currency: "USD",
    occupation: "DJ & Record Producer",
    age: 37,
    country: "South Africa",
    industry: "Music & Entertainment",
    company: "BlaqBoy Music",
    description: "Themba Sekowe, professionally known as DJ Maphorisa, is a highly versatile and influential figure in the South African music industry. As a DJ, record producer, singer, and songwriter, his musical palette spans across various genres, including house music, amapiano, and afropop. His extensive production credits include collaborations with a diverse range of notable artists, both locally and internationally, such as Wizkid, Drake, Black Coffee, and many others. Before establishing his own successful record label, BlaqBoy Music, DJ Maphorisa was signed to Kalawa Jazmee Records, a testament to his early talent and potential. His collaborative spirit and his ability to seamlessly blend different musical styles have made him a sought-after producer and DJ, consistently pushing the boundaries of South African popular music.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://event-images.tixel.com/cdn-cgi/image/w=700,q=70/media/images/d8d66164781ab27f5a7ca5f2bee5cb16_1695870971_3019_square_l.jpg",
    slug: "dj-maphorisa",
	categories: ["djs"]
  },
  {
    id: "15",
    name: "DJ Tira",
    netWorth: 3100000,
    currency: "USD",
    occupation: "DJ & Businessman",
    age: 49,
    country: "South Africa",
    industry: "Music & Entertainment",
    company: "Afrotainment",
    description: "Makhosini Nathi Maphumulo, affectionately known as DJ Tira, is a veteran of the South African music scene and a prominent figure in the Afro-pop and hip-hop genres. As the founder of the influential record label Afrotainment in 1998, DJ Tira has played a pivotal role in launching and nurturing the careers of numerous South African artists. His energetic performances and his knack for producing catchy and commercially successful tracks have made him a household name across the country. DJ Tira also hosts the annual Afrotainment Music Festival, a major event on the South African music calendar, further solidifying his status as a key influencer in the industry. His longevity and consistent contribution to the South African music landscape underscore his enduring appeal and his understanding of the local music market.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://iharare.com/wp-content/uploads/2021/10/dj-tira.jpg",
    slug: "dj-tira",
	categories: ["djs"]
  },
  {
    id: "16",
    name: "DJ Uncle Waffles",
    netWorth: 150000,
    currency: "USD",
    occupation: "DJ & Record Producer",
    age: 24,
    country: "Eswatini/RSA",
    industry: "Music & Entertainment",
    company: "Kreativekornerr, Uncle Waffles Music",
    description: "Lungelihle Zwane, popularly known as Uncle Waffles, has taken the amapiano scene by storm with her electrifying DJ sets and distinctive dance moves. Her meteoric rise to fame was fueled by viral videos showcasing her energetic performances, captivating audiences both in South Africa and internationally. Uncle Waffles' unique style and her ability to connect with the crowd have quickly made her a sought-after DJ for major events and festivals. Her international recognition, including performances in other African countries and beyond, highlights her growing global appeal and her potential to further elevate the amapiano genre on the world stage. Despite being a relatively new entrant to the mainstream, Uncle Waffles' impact has been significant, demonstrating the power of social media in propelling emerging artists to stardom.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://yt3.googleusercontent.com/UBN47LCrpZcPuY2RzHsOt2Da_5sK8lVUziKF1afCBcNs0l9zYWRDdxR_SkHsK9kE3CzDDvfI6SU=s900-c-k-c0x00ffffff-no-rj",
    slug: "uncle-waffles",
	categories: ["djs"]
  },
  {
    id: "17",
    name: "DJ Oskido",
    netWorth: 2500000,
    currency: "USD",
    occupation: "Artist, DJ & Record Producer",
    age: 57,
    country: "South Africa",
    industry: "Music & Entertainment",
    company: "Kalawa Jazmee Records",
    description: "Oscar Bonginkosi Mdlongwa, widely known as Oskido, is a true pioneer of South African house music and a highly respected veteran in the industry. With a career spanning several decades, Oskido has been instrumental in shaping the sound of South African dance music and has mentored countless aspiring DJs and producers. As a co-founder of the legendary Kalawa Jazmee Records, he played a crucial role in popularizing kwaito music in the 1990s, laying the foundation for many of the genres that followed. Oskido's enduring influence and his dedication to nurturing new talent have solidified his status as a living legend in the South African music scene. His deep understanding of music and his ability to adapt to evolving trends have allowed him to remain relevant and influential throughout his long and illustrious career.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://lh3.googleusercontent.com/ddKBS1jdFwJax5OTbNCsxXzi9tb1k_yg6ie-r_cwhw3piwzcFO4AX4xVLf1RIIfHvxsXd8YZk-4YcV64EWlyv4PMAqNWxaMAoA=s1500-pp",
    slug: "oskido",
	categories: ["djs"]
  },
  {
    id: "18",
    name: "DJ Shimza",
    netWorth: 5000000,
    currency: "USD",
    occupation: "DJ & Record Producer",
    age: 40,
    country: "South Africa",
    industry: "Music & Entertainment",
    company: "The Hang Awt 1632",
    description: "Ashley Raphala, professionally known as DJ Shimza, has carved out a significant niche in the South African house music scene with his sophisticated and soulful sound. Known for his meticulously crafted DJ sets and his ability to create a captivating atmosphere on the dance floor, DJ Shimza has become a regular feature at major music festivals and events both locally and internationally. He is also the founder of 'Shimza's One Man Show,' an annual event that has grown into a significant platform for showcasing South African musical talent. DJ Shimza's dedication to his craft and his commitment to delivering high-quality musical experiences have earned him a loyal following and critical acclaim, establishing him as a prominent figure in the contemporary South African dance music landscape.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://yt3.googleusercontent.com/IfhYU9Ydx6ekK7wzCFyjAC5Z_h_MYG6zB4_KVJZlsTuMbJAdeeQh2jZtBtj9fNuDA_ZbawmCFQ=s900-c-k-c0x00ffffff-no-rj",
    slug: "dj-shimza",
	categories: ["djs"]
  },
  {
    id: "19",
    name: "Lerato Kganyago",
    netWorth: 2000000,
    currency: "USD",
    occupation: "DJ & Record Producer",
    age: 42,
    country: "South Africa",
    industry: "Music & Entertainment",
    company: "Tammy Tailor Franchise Store",
    description: "While primarily known as a prominent media personality, television presenter, and model, Lerato Kganyago has also established herself as a capable and sought-after DJ. Her foray into the DJing world has added another dimension to her already successful career, showcasing her versatility and her passion for music. Lerato Kganyago's engaging stage presence and her ability to curate sets that resonate with diverse audiences have made her a popular choice for corporate events, fashion shows, and other high-profile gatherings. Her established brand and her wide-reaching influence across various entertainment platforms have undoubtedly contributed to her success as a DJ, further solidifying her status as a multifaceted and influential figure in the South African entertainment industry.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://yt3.googleusercontent.com/IWV5YOVHydvK9IgH8kvBlZ0DJr4HlY9rbtb0HdY1D4zsyU-I31fcANLc2ZcXnC7aThVwYv-m2nA=s900-c-k-c0x00ffffff-no-rj",
    slug: "lerato-kganyago",
	categories: ["djs"]
  },
  {
    id: "20",
    name: "DJ Fresh",
    netWorth: 2000000,
    currency: "USD",
    occupation: "DJ & Record Producer",
    age: 52,
    country: "South Africa",
    industry: "Media Personality",
    company: "Big Dawg Productions",
    description: "Daniel Stein, known professionally as DJ Fresh, is an award-winning British DJ and record producer who has also made a significant impact on the South African music scene. While originally from the UK, DJ Fresh has collaborated with numerous South African artists and has become a familiar face at local music festivals and events. His dynamic and energetic sets, often blending drum and bass with other electronic music genres, have earned him a strong following in South Africa. Notably, he formed a successful duo with DJ Euphonik under the name F.Eu, releasing several albums and headlining major events like Ultra Fest South Africa. DJ Fresh's ability to connect with the South African audience and his willingness to collaborate with local talent have cemented his place as a respected figure in the country's electronic music landscape.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://yt3.googleusercontent.com/ze433g2j5iMfFxe3rcjt8NwnrTXDucDP7gnrE0xtSBbhPhk_YMI6-RwNT5L9fLNkMmq9YT3l=s900-c-k-c0x00ffffff-no-rj",
    slug: "dj-fresh",
	categories: ["djs"]
  },
  {
    id: "21",
    name: "DJ Euphonik",
    netWorth: 1900000,
    currency: "USD",
    occupation: "DJ & Record Producer",
    age: 41,
    country: "South Africa",
    industry: "Music &  Property Investor",
    company: "ROCKA X Euphonik Headphones",
    description: "Themba Mbongeni Nkosi, widely recognized as DJ Euphonik, is a prominent figure in the South African house music scene and a well-known radio personality on stations like 5FM and 947. His consistent delivery of popular house music tracks and his energetic DJ sets have garnered him a large and dedicated fanbase. DJ Euphonik gained significant recognition early in his career with the hit track 'Cool and Deadly,' a collaboration that topped the 5FM charts. He also formed a successful partnership with DJ Fresh, creating the duo F.Eu, which produced several popular albums and headlined major events. Beyond his music career, DJ Euphonik has also ventured into business, demonstrating his entrepreneurial spirit and his desire to diversify his income streams.",
    source: "Forbes",
    lastUpdated: "2025-03-28",
    imageUrl: "https://i1.sndcdn.com/avatars-000188518071-egygye-t1080x1080.jpg",
    slug: "dj-euphonik",
	categories: ["djs"]
  },
  {
    id: "13",
    name: "DJ Tbo Touch",
    netWorth: 30000000,
    currency: "USD",
    occupation: "DJ, Radio Host",
    age: 43,
    country: "South Africa",
    industry: "Music & Entertainment",
    company: "Touch HD",
    description: "Tbo Touch, born Thabo Molefe, has built a legacy in South Africa's media industry. He first gained fame as a charismatic radio host, later transitioning into television and business. His influence expanded with Touch HD, a pioneering digital radio station. Beyond music, his investments span technology and branding, cementing his status as a top
