
import { v4 as uuidv4 } from 'uuid';

// Define Celebrity interface
export interface Celebrity {
  id: string;
  name: string;
  slug: string;
  occupation: string;
  salary: number;
  currency: string;
  imageUrl?: string;
  description: string;
  age: number;
  country: string;
  company?: string;
  industry: string;
  source: string;
  lastUpdated: string;
}

// Sample celebrity data
export const celebrities: Celebrity[] = [
  {
    id: uuidv4(),
    name: "Mike Henry",
    slug: "mike-henry",
    occupation: "CEO",
    salary: 21567610,
    currency: "ZAR",
    imageUrl: "https://www.bhp.com/-/media/project/bhp1ip/bhp1ip-en/image-5.png?h=352&iar=0&w=352&hash=2B3BCBA0A548B1D86ECE6B294DAD289F",
    description: "At 58 years old, Canadian executive Mike Henry serves as the Chief Executive Officer of the global resources giant, BHP Billiton. Leading one of the world's foremost mining and metals companies comes with significant financial reward, reflected in his substantial monthly salary of R 21,567,610. This figure underscores his position at the helm of a major international corporation with extensive operations and places him at the very top of the earnings list for CEOs associated with South Africa's corporate sphere, highlighting the scale of his responsibilities.",
    age: 58,
    country: "Canada",
    company: "BHP Billiton",
    industry: "Mining",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Fani Titi",
    slug: "fani-titi",
    occupation: "CEO",
    salary: 13890741,
    currency: "ZAR",
    imageUrl: "https://www.investec.com/content/dam/dotcom/structuredContent/contacts/Fani_Titi.jpeg",
    description: "Fani Titi, a 58-year-old South African business leader, holds the crucial role of Chief Executive Officer at the international specialist bank and asset manager, Investec. Guiding the strategic direction of this prominent financial institution, Mr. Titi commands a significant monthly compensation package amounting to R 13,890,741. This substantial remuneration reflects his extensive experience and the demanding nature of leading a complex, dual-listed company operating across diverse global markets, positioning him as one of South Africa's highest-paid executives in the financial sector.",
    age: 58,
    country: "South Africa",
    company: "Investec",
    industry: "Financial Services",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Alberto Calderon",
    slug: "alberto-calderon",
    occupation: "CEO",
    salary: 11061102,
    currency: "ZAR",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs8o9ZhNVZ9n7773-C7X-CllREFYQwODAUQg&s",
    description: "Alberto Calderon, aged 63 and originally from Colombia, leads the prominent global gold mining company, AngloGold Ashanti, as its Chief Executive Officer. Steering this major player in the international mining industry involves navigating complex operational and market challenges. His leadership role is compensated with a considerable monthly salary of R 11,061,102. This level of earnings highlights the significant responsibilities associated with managing a large-scale, multinational mining enterprise and his senior standing within the global resources sector based in South Africa.",
    age: 63,
    country: "Colombia",
    company: "AngloGold Ashanti",
    industry: "Mining",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Roy Bagattini",
    slug: "roy-bagattini",
    occupation: "CEO",
    salary: 10205667,
    currency: "ZAR",
    imageUrl: "https://cdn.asp.events/CLIENT_AIS_4ECF9403_5056_B731_4C2E7E25E0DDB2FB/sites/WRC-2023/media/libraries/speakers/roy.png/fit-in/500x500/filters:no_upscale()",
    description: "South African executive Roy Bagattini, at 61 years old, is the Chief Executive Officer of the well-known retailer, Woolworths Holdings Limited. Tasked with leading one of the country's most iconic retail brands, which also has significant operations in Australia, his role demands strategic vision and operational expertise. Mr. Bagattini receives a substantial monthly salary of R 10,205,667. This figure reflects the complexity of managing a large retail group with diverse offerings and a wide geographical footprint, placing him among the top earners in the South African retail industry.",
    age: 61,
    country: "South Africa",
    company: "Woolworths",
    industry: "Retail",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Gary Nagle",
    slug: "gary-nagle",
    occupation: "CEO",
    salary: 9001543,
    currency: "ZAR",
    imageUrl: "https://lh3.googleusercontent.com/xy0Yh22QBQJJ8kBZAyjJK7TVlKf7j8r1Qlq3sNL8Qi-aJSciafBxQgSNHjBo6YUWzFcCCSbJ8kjW3eW9y7oHVcZmhNi2RWf6=s1500-pp",
    description: "Gary Nagle, a 50-year-old South African, serves as the Chief Executive Officer of the multinational commodity trading and mining giant, Glencore Xstrata. Leading such a globally significant player in the resources sector involves immense responsibility and strategic decision-making across diverse commodities and regions. His executive position comes with a notable monthly salary of R 9,001,543. This compensation underlines the scale and complexity of Glencore's operations and Mr. Nagle's critical role in steering one of the world's largest natural resource companies.",
    age: 50,
    country: "South Africa",
    company: "Glencore Xstrata",
    industry: "Mining & Commodities",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Bob van Dijk",
    slug: "bob-van-dijk",
    occupation: "CEO",
    salary: 8984849,
    currency: "ZAR",
    imageUrl: "https://lh3.googleusercontent.com/CKbElWs41tk5SvwfGJukbeSVNL6s_B1KBTEWSQU7bmgj8ObyCIv8s1rCi_tEDX6Agc4Zzy4pnFBwKtO836AYXIBYnbB6-fQUr32f7R_9RBLD=s1500-pp",
    description: "Dutch executive Bob van Dijk, aged 52, leads the global consumer internet group and one of the world's largest technology investors, Naspers, as its Chief Executive Officer. His role involves overseeing a vast portfolio of international internet and technology investments, requiring a keen understanding of global digital trends. For his leadership, Mr. van Dijk earns a significant monthly salary of R 8,984,849. This remuneration reflects the global scale of Naspers' operations and the high stakes involved in navigating the rapidly evolving international technology.",
    age: 52,
    country: "Dutch",
    company: "Naspers",
    industry: "Technology & Media",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Duncan Wanblad",
    slug: "duncan-wanblad",
    occupation: "CEO",
    salary: 7148810,
    currency: "ZAR",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3Xrl7j-dA3SJO4aauXMhGomsosd3dsbsFNw&s",
    description: "At 57, South African Duncan Wanblad holds the position of Chief Executive Officer at the globally diversified mining company, Anglo American plc. Leading this major international mining house requires overseeing operations across multiple continents and commodities, from diamonds to platinum group metals and copper. His extensive responsibilities are reflected in his monthly salary of R 7,148,810. This significant compensation package underscores his critical leadership role within one of the world's largest and most influential mining corporations with deep roots in South Africa.",
    age: 57,
    country: "South Africa",
    company: "Anglo American plc",
    industry: "Mining",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Sim Tshabalala",
    slug: "sim-tshabalala",
    occupation: "CEO",
    salary: 6942000,
    currency: "ZAR",
    imageUrl: "https://www.standardbank.com/static_file/SBG/Assets/Img/Standard%20Bank%20Group/Leadership/2024/GLC/Q3/Sim%20Tshabalala/Sim_not-compressed_Portrait_sq_300x300.jpg",
    description: "Sim Tshabalala, a 57-year-old South African banking executive, serves as the Group Chief Executive Officer of Absa Group Limited. He leads one of Africa's largest diversified financial services groups, overseeing banking operations across numerous countries on the continent. This demanding leadership role comes with a monthly salary reported at R 6,942,000. This substantial figure reflects his responsibility for the strategic direction and performance of a major pan-African banking institution, positioning him as a top earner in the continent's financial services industry.",
    age: 57,
    country: "South Africa",
    company: "Absa Group",
    industry: "Banking",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Lungisa Fihla",
    slug: "lungisa-fihla",
    occupation: "CEO",
    salary: 5825250,
    currency: "ZAR",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWKh1xPfi8lvbN6Haafyyf0Y_n5yEBlZ-kjA&s",
    description: "Leading Africa's largest food retailer, Shoprite Holdings, is 53-year-old South African CEO Pieter Engelbrecht. His role involves managing a vast network of supermarkets and retail outlets across the continent, navigating complex logistics and diverse consumer markets. For steering this retail giant, Mr. Engelbrecht receives a significant monthly salary of R 6,939,333. This compensation highlights the immense scale of Shoprite's operations and the critical leadership required to maintain its market dominance in the highly competitive African retail sector.",
    age: 58,
    country: "South Africa",
    company: "Standard Bank Group",
    industry: "Banking",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Andrew King",
    slug: "andrew-king",
    occupation: "CEO",
    salary: 5486866,
    currency: "ZAR",
    imageUrl: "https://www.mondigroup.com/cdn-cgi/image/f=auto,w=640,sharpen=1/AdaptiveImages/celum/379591/Andrew_King.png?stamp=96fdbab5a66a152eecfdc24af7ce9a17b196c5a1",
    description: "Lungisa Fihla, a 58-year-old South African executive, serves as a Chief Executive Officer within the Standard Bank Group, Africa's largest bank by assets. While the specific division isn't listed, his CEO title within this major financial institution indicates significant leadership responsibilities. Mr. Fihla earns a substantial monthly salary of R 5,825,250. This figure reflects the seniority of his position and the importance of his contribution to the strategic operations and success of one of the continent's most prominent and influential banking organisations.",
    age: 56,
    country: "South Africa",
    company: "Mondi Group",
    industry: "Packaging & Paper",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Pieter Engelbrecht",
    slug: "pieter-engelbrecht",
    occupation: "CEO",
    salary: 6939333,
    currency: "ZAR",
    imageUrl: "https://media.licdn.com/dms/image/v2/C4D03AQEt5xSgAW0wjA/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1516971473807?e=2147483647&v=beta&t=qdpeXKCiWjJwG5kOmoYT1sr8-we2iKZCqmn4WVvQox8",
    description: "Andrew King, a 56-year-old South African executive, leads the international packaging and paper company, Mondi Group, as its Chief Executive Officer. His role involves overseeing a global business focused on sustainable packaging and paper solutions, operating across numerous countries. For this leadership position, Mr. King receives a monthly salary of R 5,486,866. This compensation reflects the global nature of Mondi's operations and the strategic importance of navigating the evolving landscape of sustainable materials and international manufacturing within the industry.",
    age: 53,
    country: "South Africa",
    company: "Shoprite",
    industry: "Retail",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Iain Williamson",
    slug: "iain-williamson",
    occupation: "CEO",
    salary: 2693333,
    currency: "ZAR",
    imageUrl: "https://www.africaglobalfunds.com/static/media/uploads/2020/07/07/ian-williamson.jpg",
    description: "At 52 years old, South African Iain Williamson holds the position of Chief Executive Officer at the prominent pan-African financial services group, Old Mutual Limited. He is responsible for guiding the strategy and operations of this well-established company, which offers a wide range of insurance, investment, and banking services across Africa. Mr. Williamson earns a monthly salary of R 2,693,333. This remuneration reflects his leadership role within a major player in the African financial services sector, overseeing diverse business units and navigating complex market dynamics.",
    age: 52,
    country: "South Africa",
    company: "Old Mutual",
    industry: "Insurance & Finance",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Chris du Toit",
    slug: "chris-du-toit",
    occupation: "CEO",
    salary: 2690000,
    currency: "ZAR",
    imageUrl: "https://media.licdn.com/dms/image/v2/C4E03AQFsCFQtgy8KZQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1579155432265?e=2147483647&v=beta&t=vNJsQEmn2WsgMMT56sh7hTcw7KFyBwVBLEumi_OfRAk",
    description: "Chris du Toit, a 55-year-old South African, serves as the Chief Executive Officer of the leading South African hospitality, gaming, and entertainment group, Tsogo Sun. His role involves managing a diverse portfolio of hotels and entertainment complexes, requiring expertise in the leisure and hospitality industry. Mr. du Toit's leadership position is compensated with a monthly salary of R 2,690,000. This figure reflects the responsibilities associated with steering a major player in South Africa's tourism and entertainment sector through various market conditions and operational challenges.",
    age: 55,
    country: "South Africa",
    company: "Tsogo Sun",
    industry: "Hospitality & Gaming",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Adrian Gore",
    slug: "adrian-gore",
    occupation: "CEO",
    salary: 2359167,
    currency: "ZAR",
    imageUrl: "https://www.internationalinsurance.org/sites/default/files/gbb-uploads/Adrian%20450x450-ads48i.jpg",
    description: "Adrian Gore, the 60-year-old South African founder and Chief Executive Officer of Discovery Limited, leads the globally recognized financial services organization known for its innovative shared-value insurance model. His entrepreneurial vision built the company, which now operates in insurance, wellness, and banking sectors internationally. Mr. Gore receives a monthly salary of R 2,359,167. While substantial, this figure reflects his ongoing leadership in driving innovation and managing the continued expansion and complexity of the Discovery group across different markets and product lines.",
    age: 60,
    country: "South Africa",
    company: "Discovery",
    industry: "Insurance & Healthcare",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Laurence Rapp",
    slug: "laurence-rapp",
    occupation: "CEO",
    salary: 1933333,
    currency: "ZAR",
    imageUrl: "https://lh3.googleusercontent.com/pN6uUrkphrvXfZ3qQATMFiscW5HdxUynDSmQbyAsZU759-yNFCsU19-kLZykUljs16H2pn8599MUqYQpnDtc9H9O6TOVCMfowXsEAkQpIRVlKQ=s1500-pp",
    description: "Laurence Rapp, a 54-year-old South African executive, leads Vukile Property Fund as its Chief Executive Officer. His role involves managing a specialist retail real estate investment trust (REIT) with significant property assets in South Africa and Spain. Steering this property investment company requires expertise in real estate markets and asset management. Mr. Rapp earns a monthly salary of R 1,933,333. This compensation reflects his leadership responsibilities in managing a substantial property portfolio and driving strategy within the competitive real estate investment sector.",
    age: 54,
    country: "South Africa",
    company: "Vukile Property",
    industry: "Real Estate Investment",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Roy Douglas",
    slug: "roy-douglas",
    occupation: "CEO",
    salary: 1863333,
    currency: "ZAR",
    imageUrl: "https://lh3.googleusercontent.com/Bm2UfRii30ATP6xfNmUt_quE98crEaeIKSFpZPyHq-8eWYm3S4aES1pnkQDfKfKt11JhmufbMwkNTmiek7OIfi96Uniscp4=s1500-pp",
    description: "At 61, South African Roy Douglas serves as the Chief Executive Officer of ADvTECH Group, a leading private education and recruitment company in South Africa. His responsibilities include overseeing a diverse portfolio of schools, tertiary institutions, and recruitment agencies, navigating the dynamics of both the education and employment sectors. Mr. Douglas receives a monthly salary of R 1,863,333. This figure reflects his leadership role in managing one of the largest private education and staffing providers on the continent, requiring strategic oversight across multiple brands and services.",
    age: 61,
    country: "South Africa",
    company: "ADvTECH",
    industry: "Education",
    source: "BusinessTech",
    lastUpdated: "2025-04-07"
  },
  {
    id: uuidv4(),
    name: "Nasreddine Nabi",
    slug: "nasreddine-nabi",
    occupation: "Football Coach",
    salary: 783000,
    currency: "ZAR",
    imageUrl: "https://farpost.co.za/wp-content/uploads/2025/04/Nasreddine-during-the-Nedbank-Cup-media-event-780x470.jpg",
    description: "Nasreddine Nabi has quickly become one of the most prominent figures in South African football. Managing Kaizer Chiefs, he earns an impressive R783,000 a month. His strategic approach and leadership have made him the highest-paid coach in the league. Nabi’s vast experience, which includes stints with top clubs in Tunisia, has elevated Kaizer Chiefs to new heights, capturing the attention of millions of fans. His salary reflects his status as a key figure in the PSL.",
    age: 48,
    country: "Tunisia",
    company: "Kaizer Chiefs",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "Manqoba Mngqithi",
    slug: "manqoba-mngqithi",
    occupation: "Football Coach",
    salary: 700000,
    currency: "ZAR",
    imageUrl: "https://cdn.24.co.za/files/Cms/General/d/12772/0ea088646f2c4469815a05d4c80d4555.jpg",
    description: "As the senior coach of Mamelodi Sundowns, Manqoba Mngqithi’s work speaks volumes. He commands over R700,000 a month, a salary that reflects his invaluable contribution to the team’s success. Mngqithi’s calm demeanor and tactical brilliance have made Sundowns a powerhouse in African football. Under his leadership, the team has consistently dominated both locally and internationally. Mngqithi’s ability to build a strong, cohesive team continues to earn him well-deserved recognition and respect in the footballing world.",
    age: 53,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "Rhulani Mokwena",
    slug: "rhulani-mokwena",
    occupation: "Football Coach",
    salary: 700000,
    currency: "ZAR",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/38/Go_Ahead_Eagles_-_Mamelodi_Sundowns_FC_-_53066347575_%28Rhulani_Mokwena%29.jpg",
    description: "Rhulani Mokwena’s managerial career reached new heights with his move to Wydad AC, but it was his previous work at Mamelodi Sundowns that solidified his reputation. Earning over R700,000 a month, Mokwena’s journey has been one of growth and innovation. His time at Sundowns saw him revolutionize the team’s attacking play, making them one of the most feared sides in Africa. His tactical acumen and leadership qualities have made him one of the most sought-after coaches in the region.",
    age: 37,
    country: "South Africa",
    company: "Wydad AC",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "Steve Komphela",
    slug: "steve-komphela",
    occupation: "Football Coach",
    salary: 700000,
    currency: "ZAR",
    imageUrl: "https://img.a.transfermarkt.technology/portrait/big/11044-1688283736.jpg?lm=1",
    description: "Steve Komphela has had a remarkable career in South African football, and his role at Mamelodi Sundowns now sees him earning over R700,000 per month. Known for his disciplined approach, Komphela has brought stability to Sundowns’ technical team. His knowledge of the game and his ability to nurture players has helped the club maintain its dominance. Komphela’s experience both as a former player and coach makes him a vital asset to the team, earning him one of the highest salaries in the league.",
    age: 56,
    country: "South Africa",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "José Riveiro",
    slug: "josé-riveiro",
    occupation: "Football Coach",
    salary: 700000,
    currency: "ZAR",
    imageUrl: "https://img.a.transfermarkt.technology/portrait/big/44214-1730832896.png?lm=1",
    description: "José Riveiro’s tenure at Orlando Pirates has proven successful, and his salary of around R700,000 a month is a testament to his hard work and expertise. The Spanish manager brought with him a fresh approach to South African football, focusing on tactical discipline and high-intensity play. His leadership has seen the Pirates make significant strides in both local and continental competitions. Riveiro’s calm and composed nature on the touchline, paired with his winning mentality, has solidified his position as one of the league’s highest earners.",
    age: 46,
    country: "Spanish",
    company: "Orlando Pirates",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "Eric Tinkler",
    slug: "eric-tinkler",
    occupation: "Football Coach",
    salary: 700000,
    currency: "ZAR",
    imageUrl: "https://img.a.transfermarkt.technology/portrait/big/20913-1635831200.jpg?lm=1",
    description: "Eric Tinkler, known for his fiery passion and tactical insight, leads Cape Town City with great success. Earning around R700,000 per month, Tinkler’s career has seen him rise through the ranks, proving his mettle at clubs across South Africa. His time at Cape Town City has been marked by innovative play and impressive results. Tinkler’s ability to extract the best from his players and create a competitive team in a tough league has earned him both respect and a lucrative salary.",
    age: 54,
    country: "South Africa",
    company: "Cape Town City",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "John Maduka",
    slug: "john-maduka",
    occupation: "Football Coach",
    salary: 600000,
    currency: "ZAR",
    imageUrl: "https://times.mw/wp-content/uploads/2023/09/john-maduka.jpg",
    description: "John Maduka has made waves in South African football, particularly with Royal AM. With a salary exceeding R600,000 per month, Maduka’s influence on the club has been undeniable. Known for his strong leadership and tactical discipline, Maduka has transformed Royal AM into a team to be reckoned with in the league. His experience as a former player has allowed him to connect with his squad on a deeper level, motivating them to perform at their peak. Maduka’s reputation continues to grow, alongside his salary.",
    age: 47,
    country: "Malawi",
    company: "Royal AM",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "Brandon Truter",
    slug: "brandon-truter",
    occupation: "Football Coach",
    salary: 600000,
    currency: "ZAR",
    imageUrl: "https://sundayworld.co.za/wp-content/uploads/2022/09/P22-Brandon-Truter--e1684604492868.jpg",
    description: "Brandon Truter’s leadership of Sekhukhune United has been marked by steady progress, and his monthly salary of over R600,000 reflects his growing stature in South African football. Truter’s ability to adapt to the demands of the PSL has helped Sekhukhune establish themselves as a competitive side. His tactical approach, combined with a focus on team cohesion, has enabled him to overcome challenges and secure important victories. Truter’s rise in the coaching ranks is a testament to his hard work and dedication.",
    age: 51,
    country: "South Africa",
    company: "Sekhukhune United",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "Steve Barker",
    slug: "steve-barker",
    occupation: "Football Coach",
    salary: 400000,
    currency: "ZAR",
    imageUrl: "https://lh3.googleusercontent.com/IcxB3ac5rhoQvZaEV8L2qWcXC2H-8i5Uj452Buo2J49qNOlzn17BlH1GqgB0XGL9V0ZHfBiFUJNDu5iQ0lp6kPCLrgh8x5htO-kpDSzx2tus=s750",
    description: "Steve Barker may not be one of the highest-paid coaches in the league, but his salary of R400,000 per month is still a reflection of his significant contributions to Stellenbosch FC. Barker’s emphasis on building a solid defensive team and his tactical discipline has made Stellenbosch a competitive force. Under his leadership, the club has continued to perform well, consistently securing important points. Barker’s calm, methodical approach to coaching has helped shape the club into a respected side in the PSL.",
    age: 47,
    country: "South Africa",
    company: "Stellenbosch FC",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
    {
    id: uuidv4(),
    name: "Miguel Cardoso",
    slug: "miguel-cardoso",
    occupation: "Football Coach",
    salary: 1500000,
    currency: "ZAR",
    imageUrl: "https://football.fmh.ulisboa.pt/wp-content/uploads/2015/09/MIGUEL_CARDOSO.jpg",
    description: "Miguel Cardoso, the tactical mastermind behind Mamelodi Sundowns, commands an impressive R1.5 million per month. His strategic approach and ability to elevate the team’s performance have made him one of the highest-paid coaches in South Africa. Cardoso’s experience, honed through various roles in Europe and Africa, has brought a fresh, dynamic style to Sundowns. Under his leadership, the club has enjoyed remarkable success, both domestically and internationally. Cardoso’s tactical depth, combined with his passion for the game, ensures that Sundowns remains a formidable force in the PSL.",
    age: 52,
    country: "Brazil",
    company: "Mamelodi Sundowns",
    industry: "Football",
    source: "UGC",
    lastUpdated: "2025-04-08"
  },
  {
    id: uuidv4(),
    name: "Cyril Ramaphosa",
    slug: "cyril-ramaphosa",
    occupation: "President of South Africa",
    salary: 350000,
    currency: "ZAR",
    imageUrl: "https://www.blackpast.org/wp-content/uploads/2024/09/cyril-ramaphosa-e1654285066393.jpg",
    description: "Cyril Ramaphosa leads the country both politically and financially. As President of South Africa, he earns R350,000 per month. This figure tops the list of public salaries and reflects the enormous responsibility his role demands. He’s known not just for his political moves but also for philanthropy, often donating his earnings to causes close to his heart. His experience in business and union negotiations has shaped his leadership style, balancing diplomacy with economic strategy on both national and international stages.",
    age: 72,
    country: "South Africa",
    company: "ANC",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "John Steenhuisen",
    slug: "john-steenhuisen",
    occupation: "Minister of Agriculture",
    salary: 224161,
    currency: "ZAR",
    imageUrl: "https://pbs.twimg.com/profile_images/1807685840279060480/B36E7Bti_400x400.jpg",
    description: "Holding dual responsibilities as DA leader and Minister of Agriculture, John Steenhuisen brings in R224,161 each month. His new role within the Government of National Unity gives him executive oversight in a sector vital to the country’s food systems. Known for his sharp debates and outspoken leadership in opposition, Steenhuisen now has to navigate policy with practical implementation, managing both party leadership and ministerial duties. His presence in the cabinet marks a new political chapter that blends old rivalries with cooperative governance.",
    age: 49,
    country: "South Africa",
    company: "DA",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "John Hlophe",
    slug: "john-hlophe",
    occupation: "Leader of the Opposition",
    salary: 149383,
    currency: "ZAR",
    imageUrl: "https://lh3.googleusercontent.com/eptArYu6F4jWknAx9zkSVwNsj9HbDpeG4Ke26Cp0RR9nUxYHmhenoc2cS8HUy3G4O1fn3_P7-jRwToD0iyXUnWXcl98rO5_u=s1500-pp",
    description: "John Hlophe earns R149,383 monthly in his position as Leader of the Opposition. After a controversial legal career, he’s now the official face of parliamentary resistance for the MK Party. This role gives him a national platform to challenge government policy and offer alternatives. Though not without criticism, his background in law allows him to dissect legislation with unusual precision. His move from the bench to the political arena adds legal firepower to his party’s growing influence in national debates.",
    age: 65,
    country: "South Africa",
    company: "MK",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Julius Malema",
    slug: "julius-malema",
    occupation: "Minority Party Leader",
    salary: 125653,
    currency: "ZAR",
    imageUrl: "https://cdn.britannica.com/67/176667-050-25CBD02D/Julius-Malema.jpg",
    description: "EFF leader Julius Malema commands attention across the political spectrum, earning R125,653 a month. As a Minority Party Leader, his role isn’t part of the executive, but his voice often shakes the foundations of parliamentary order. His fearless calls for land reform and wealth redistribution have made him a polarizing yet undeniable force. Whether in red overalls or addressing rallies, Malema’s presence stirs national conversation and keeps economic justice at the forefront of political dialogue.",
    age: 44,
    country: "South Africa",
    company: "EFF",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Velenkosini Hlabisa",
    slug: "velenkosini-hlabisa",
    occupation: "Minister of COGTA",
    salary: 224161,
    currency: "ZAR",
    imageUrl: "https://pbs.twimg.com/profile_images/1247600968931389444/EMKBgVAp_400x400.jpg",
    description: "As Minister of Cooperative Governance and Traditional Affairs, Velenkosini Hlabisa earns R224,161 monthly. He leads the IFP and bridges the gap between traditional leadership and modern governance. His role involves fostering municipal effectiveness and ensuring rural voices are heard in national planning. Quiet yet strategic, Hlabisa’s leadership is built on community roots and a respect for long-standing cultural structures. His influence extends from local councils to national policy, where he's building a legacy of inclusive development.",
    age: 60,
    country: "South Africa",
    company: "IFP",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Gayton Mckenzie",
    slug: "gayton-mckenzie",
    occupation: "Minister of Sports, Arts and Culture",
    salary: 224161,
    currency: "ZAR",
    imageUrl: "https://www.miningreview.com/wp-content/uploads/2024/07/GaytonM-e1720603601759.jpg",
    description: "Gayton McKenzie, known for his dramatic personal turnaround, now earns R224,161 a month as Minister of Sports, Arts, and Culture. From ex-convict to cabinet minister, his story often inspires—and provokes. McKenzie has promised to donate his salary, stirring both admiration and skepticism. His ministry oversees creative industries and national heritage, with a strong emphasis on local talent. He approaches governance with blunt honesty and streetwise instincts, using his platform to uplift communities through sports and entertainment.",
    age: 51,
    country: "South Africa",
    company: "PA",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Pieter Groenewald",
    slug: "pieter-groenewald",
    occupation: "Minister of Correctional Services",
    salary: 224161,
    currency: "ZAR",
    imageUrl: "https://kiweb.co.za/wp-content/uploads/2024/09/Pieter-Groenewald-2024.jpeg",
    description: "Pieter Groenewald receives R224,161 monthly as Minister of Correctional Services. As FF Plus leader, he’s positioned in a complex portfolio tasked with rehabilitating offenders and improving prison conditions. Groenewald's policy positions often focus on law, order, and protection of minority rights. With a calm demeanor, he rarely seeks the spotlight, but his experience makes him a steady hand in overseeing a department that often escapes public scrutiny. His aim: a justice system that punishes wisely and reforms effectively.",
    age: 69,
    country: "South Africa",
    company: "FF Plus",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Athol Trollip",
    slug: "athol-trollip",
    occupation: "Minority Party Leader",
    salary: 125653,
    currency: "ZAR",
    imageUrl: "https://pbs.twimg.com/profile_images/1577965499291426816/aHAHzlqK_400x400.jpg",
    description: "Athol Trollip, the parliamentary leader of ActionSA, earns R125,653 per month. Though not in the executive, he plays a strategic role in steering opposition discourse in Parliament. Trollip brings experience from his time in Nelson Mandela Bay and uses his local government insight to critique national policies. His straightforward speaking style and no-nonsense tone distinguish him from more theatrical counterparts. Within a growing party, Trollip’s influence helps translate ActionSA’s platform into legislative arguments and civic outreach.",
    age: 61,
    country: "South Africa",
    company: "ActionSA",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Kenneth Meshoe",
    slug: "kenneth-meshoe",
    occupation: "Minority Party Leader",
    salary: 125653,
    currency: "ZAR",
    imageUrl: "https://pbs.twimg.com/profile_images/1026377566662402048/SUzeaQEI_400x400.jpg",
    description: "Kenneth Meshoe, leading the ACDP, earns a monthly salary of R125,653. His presence in Parliament blends politics with faith, advocating for conservative values and moral governance. Meshoe is one of the longest-serving MPs, having built a following around issues like education, family, and anti-corruption. While his party remains relatively small, his consistency and commitment to principles have earned him respect. In a sea of shifting alliances, Meshoe offers a voice grounded in religious conviction and long-term vision.",
    age: 71,
    country: "South Africa",
    company: "ACDP",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Bantu Holomisa",
    slug: "bantu-holomisa",
    occupation: "Deputy Minister of Defence",
    salary: 184602,
    currency: "ZAR",
    imageUrl: "https://lh3.googleusercontent.com/JgAWZtVe4RglUO4ojl1lzmAau4AoQm1briINb2uuy_YGfERSfXXAvtR_Bel95mppd1dwgBs6EW4MG0Mjy7Mm=s1500-pp",
    description: "Bantu Holomisa serves as Deputy Minister of Defence, collecting R184,602 per month. With a military past and decades in politics, Holomisa remains a seasoned figure on the national stage. His leadership of the UDM combines discipline with grassroots sensibility. From oversight of military readiness to parliamentary debates, he stays active in defending democratic processes. His straightforward style and independence have made him a reliable critic and a valuable ally across party lines, reinforcing his reputation for integrity.",
    age: 69,
    country: "South Africa",
    company: "UDM",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Songezo Zibi",
    slug: "songezo-zibi",
    occupation: "Chair of SCOPA",
    salary: 139610,
    currency: "ZAR",
    imageUrl: "https://pbs.twimg.com/profile_images/1900504122123517952/4U6gb06L_400x400.jpg",
    description: "Songezo Zibi earns R139,610 per month as Chairperson of the Standing Committee on Public Accounts. Known for his background in journalism and corporate leadership, Zibi approaches politics with a polished, policy-driven focus. As leader of Rise Mzansi, he promotes a modern and ethical vision for South Africa’s future. His role in overseeing public funds aligns with his long-standing advocacy for accountability. Zibi brings structure, research, and clarity to a Parliament often dominated by loud personalities.",
    age: 49,
    country: "South Africa",
    company: "RISE Mzansi",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Mmusi Maimane",
    slug: "mmusi-maimane",
    occupation: "Chair of the Appropriations Committee",
    salary: 139610,
    currency: "ZAR",
    imageUrl: "https://pbs.twimg.com/profile_images/1187296068662366208/02DeNdW9_400x400.jpg",
    description: "Mmusi Maimane leads BOSA and chairs the Appropriations Committee, earning R139,610 monthly. He continues to focus on building a new political alternative grounded in ethics and service delivery. Maimane’s leadership emphasizes transparency, inclusive growth, and youth empowerment. His committee role gives him direct influence over government spending, a powerful position for ensuring that public funds align with developmental priorities. Maimane’s calm approach and public engagement make him a steady figure in a rapidly changing political environment.",
    age: 44,
    country: "South Africa",
    company: "BOSA",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Vuyolwethu Zungula",
    slug: "vuyolwethu-zungula",
    occupation: "Minority Party Leader",
    salary: 125653,
    currency: "ZAR",
    imageUrl: "https://pbs.twimg.com/profile_images/1798004083896250368/bDE0NG1J_400x400.jpg",
    description: "ATM’s Vuyolwethu Zungula earns R125,653 per month and leads with a blend of activism and assertiveness. His parliamentary speeches often center on African unity, social equity, and justice for underrepresented communities. While the party remains small, Zungula’s focus on reclaiming African values and economic independence resonates with younger voters. His approach is passionate yet structured, reflecting a new generation of leadership determined to challenge traditional party politics.",
    age: 37,
    country: "South Africa",
    company: "ATM",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Ganief Hendricks",
    slug: "ganief-hendricks",
    occupation: "Deputy Minister of Social Development",
    salary: 184602,
    currency: "ZAR",
    imageUrl: "https://image-prod.iol.co.za/16x9/800/EFF-MPs-have-criticised-Deputy-Minister-Ganief-Hendricks-for-not-directly-addressing-gambling-related-questions-calling-for-reforms-and-stronger-oversight-of-ministers-in-Parliament?source=https://iol-prod.appspot.com/image/5e7c36f344af86b207fc4ba4eb10351ce6f2d35f/2000&operation=CROP&offset=0x104&resize=2000x1125",
    description: "Ganief Hendricks serves as Deputy Minister of Social Development, earning R184,602 a month. As the leader of Al Jama-ah, he promotes Islamic values in governance while focusing on public welfare and social cohesion. Hendricks brings a strong grassroots connection, often advocating for the rights of marginalized communities. His role places him at the heart of poverty alleviation and family support programs. Blending faith with policy, Hendricks plays a key role in shaping inclusive social policy.",
    age: 75,
    country: "South Africa",
    company: "Al Jama-ah",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Fadiel Adams",
    slug: "fadiel-adams",
    occupation: "Minority Party Leader",
    salary: 125653,
    currency: "ZAR",
    imageUrl: "https://static.pa.org.za/images/F_Adams.JPG",
    description: "Fadiel Adams leads the National Coloured Congress and earns R125,653 per month. A relatively new figure in Parliament, Adams speaks boldly on issues affecting marginalized coloured communities. His no-filter style of delivery sets him apart in a chamber full of formalities. While his party is still establishing its presence nationally, Adams uses his platform to push for equality and representation. His salary reflects the standard for minority party leaders, but his voice often carries far beyond.",
    age: 48,
    country: "South Africa",
    company: "NCC",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Mzwanele Nyhontso",
    slug: "mzwanele-nyhontso",
    occupation: "Minister of Land Reform and Rural Development",
    salary: 224161,
    currency: "ZAR",
    imageUrl: "https://pbs.twimg.com/profile_images/1467206223208628227/Du3KZ7Nz_400x400.jpg",
    description: "PAC’s Mzwanele Nyhontso serves as Minister of Land Reform and earns R224,161 monthly. He’s responsible for one of the most sensitive and historically rooted portfolios in South Africa. His task is to address land redistribution while balancing legal and economic realities. Nyhontso’s leadership of the PAC brings with it a legacy of Pan-Africanism and radical transformation. He speaks with urgency on land justice, a topic that remains central to the country’s post-apartheid journey.",
    age: 51,
    country: "South Africa",
    company: "PAC",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Lehlohonolo Mahlatsi",
    slug: "lehlohonolo-mahlatsi",
    occupation: "Minority Party Leader",
    salary: 125653,
    currency: "ZAR",
    imageUrl: "https://static.pa.org.za/images/W_Mahlatsi.JPG",
    description: "Leading the United Africans Transformation (UAT), Dr. Lehlohonolo Mahlatsi earns R125,653 per month. A fresh face in national politics, Mahlatsi brings academic insight to his parliamentary role. With a background in criminal justice and community advocacy, he’s focused on building African unity and social equity. His presence in the National Assembly adds intellectual depth to debates and reflects the rise of smaller parties aiming to disrupt the traditional political balance. He represents a new wave of policy-centered leadership.",
    age: 43,
    country: "South Africa",
    company: "UAT",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  },
  {
    id: uuidv4(),
    name: "Patricia de Lille",
    slug: "patricia-de-lille",
    occupation: "Minister of Tourism",
    salary: 224161,
    currency: "ZAR",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJuObxwNShnPoszb1pqaL7KFefNA7cqgzvcw&s",
    description: "Patricia de Lille earns R224,161 per month as Minister of Tourism. With decades in public service and leadership across multiple political parties, she remains one of South Africa’s most enduring political figures. Her current role focuses on revitalizing the tourism sector, an area crucial for economic recovery and job creation. Known for her direct communication and hands-on approach, De Lille blends pragmatism with political savvy. Her ability to cross party lines and remain relevant has earned her both criticism and admiration throughout her dynamic career.",
    age: 74,
    country: "South Africa",
    company: "Good",
    industry: "Politics",
    source: "BusinessTech",
    lastUpdated: "2025-04-09"
  }
];

// Format salary for display
export const formatSalary = (salary: number, currency: string) => {
  return salary.toLocaleString('en-US', {
    style: 'currency',
    currency: currency,
    maximumFractionDigits: 1,
    minimumFractionDigits: 0,
    notation: 'compact',
    compactDisplay: 'short',
  });
};

// Find a celebrity by slug
export const findCelebrityBySlug = (slug: string): Celebrity | undefined => {
  return celebrities.find(celebrity => celebrity.slug === slug);
};

// Get similar celebrities (same industry or similar salary)
export const getSimilarCelebrities = (celebrity: Celebrity, limit: number = 5): Celebrity[] => {
  return celebrities
    .filter(c => 
      c.id !== celebrity.id && 
      (c.industry === celebrity.industry || 
       Math.abs(c.salary - celebrity.salary) / celebrity.salary < 0.3)
    )
    .sort((a, b) => {
      // Sort by industry match first, then by salary similarity
      if (a.industry === celebrity.industry && b.industry !== celebrity.industry) {
        return -1;
      }
      if (a.industry !== celebrity.industry && b.industry === celebrity.industry) {
        return 1;
      }
      return Math.abs(a.salary - celebrity.salary) - Math.abs(b.salary - celebrity.salary);
    })
    .slice(0, limit);
};
