import { NetWorthPerson } from './index';

export const djs: NetWorthPerson[] = [
  {
    id: "djs-1",
    name: "DJ Vlad",
    gender: "male",
    netWorth: 10000000,
    currency: "USD",
    occupation: "Interviewer, journalist, director",
    dateOfBirth: "1973-06-28",
    country: "United States of America",
    industry: "Disc jockey",
    company: "VladTV",
    description: "DJ Vlad is an Internet personality, journalist, director, and former DJ who has a net worth of $10 million. DJ Vlad is best known for his eponymous YouTube channel on which he hosts interviews with a variety of celebrities. He has amassed over 5.5 million subscribers since launching the channel in 2006. Elsewhere, DJ Vlad created the news website VladTV.com, directed episodes of the BET documentary series \"American Gangster,\" and directed the documentary film \"Ghostride the Whip.\"",
    source: "Celebrity Net Worth",
    lastUpdated: "2025-04-09",
    imageUrl: "https://vz.cnwimg.com/thm/_XadMMYielH_UKyoiWoRHOVLOlA=/600x300/center/top/filters:format(webp)/2014/06/dj-vlad.jpg",
    slug: "dj-vlad-net-worth",
    categories: ["celebrities", "djs"]
  },
  {
    id: "djs-1",
    name: "Alan Walker",
    gender: "male",
    netWorth: 15000000,
    currency: "USD",
    occupation: "Disc jockey",
    dateOfBirth: "1997-08-24",
    country: "Norway",
    industry: "Disc jockey",
    company: "MER Musikk",
    description: "Alan Walker is a Norwegian DJ and record producer who has a net worth of $15 million. Alan Walker was born in Northampton, England in August 1997. In 2018 DJ Mag ranked him as #36 on the Top 100 DJS of the year. Walker released his debut studio album Different World in 2018 which reached #1 in Norway and Finland. It also reached #15 in Sweden, #31 in Switzerland, and #36 in the Netherlands.",
    source: "Forbes",
    lastUpdated: "2025-04-10",
    imageUrl: "https://vz.cnwimg.com/thm/Wv1agTlA2yvwt2NWCG0awk4pR_Q=/600x300/center/top/filters:format(webp)/2019/01/Alan-Walker.jpg",
    slug: "alan-walker-net-worth",
    categories: ["celebrities", "djs"]
  },
  {
    id: "djs-1",
    name: "Tim Westwood",
    gender: "male",
    netWorth: 8000000,
    currency: "USD",
    occupation: "Presenter, Disc jockey, Radio personality",
    dateOfBirth: "1957-10-03",
    country: "United Kingdom",
    industry: "Disc jockey",
    company: "Independent",
    description: "Tim Westwood is an English DJ and radio and TV personality who has a net worth of $8 million. Tim Westwood established himself as one of the UK's most influential hip-hop DJs during his lengthy career spanning over two decades at the BBC.",
    source: "Celebrity Net Worth",
    lastUpdated: "2025-04-11",
    imageUrl: "https://vz.cnwimg.com/thm/plE0geoS6s1eIQJIQdFVU_tJ9WU=/600x300/center/top/filters:format(webp)/2011/01/GettyImages-475328637.jpg",
    slug: "tim-westwood-net-worth",
    categories: ["celebrities", "djs"]
  },
  {
    id: "djs-1",
    name: "Steve Wright",
    gender: "male",
    netWorth: 6000000,
    currency: "USD",
    occupation: "Radio personality",
    dateOfBirth: "1954-08-25",
    country: "United Kingdom",
    industry: "Disc jockey",
    company: "BBC Radio 2",
    description: "Steve Wright was an English radio personality and disc jockey who had a net worth of $6 million. Steve Wright was best known as one of radio's most popular and entertaining presenters, formatting his broadcasts to include a host of zany characters. His cheery demeanor and easygoing love of life brought joy to radio audiences for over four decades.",
    source: "Celebrity Net Worth",
    lastUpdated: "2025-04-12",
    imageUrl: "https://vz.cnwimg.com/thm/UJJJpx2X5X5oXbmbkXnrl5Gm2wI=/600x300/center/top/filters:format(webp)/2018/07/Steve-Wright.jpg",
    slug: "steve-wright-net-worth",
    categories: ["celebrities", "djs"]
  }
];
